### ISSUE TITLE
seems no performance increase

### ISSUE THREAD

**Issue by sgf** [narzoul/DDrawCompat#10]
Try a bit seems to be no performance increase.
CPU usage is almost the same.

**Comment by narzoul** [comment]
Err... which issue/game are you referring to? You'll need to give a bit more info...

**Comment by sgf** [comment]
the legend of mir ......a old mmorpg

**Comment by narzoul** [comment]
I found at least 4 different "The Legend of Mir" or related titles from a quick search:
The Legend of Mir Project69
Mir Arcadia
The Legend of Mir 2
The Legend of Mir 3

Which one are you referring to? Please add a link where I can download and test the right game.

What operating system and graphics card are you using?

Performance doesn't increase compared to what? Did it run better on another version of Windows or on a different GPU/system? Which parts of the game are problematic?

Which version(s) of DDrawCompat did you test?

Please attach the ddraw.log file that is created in the game directory when you run the game.

**Comment by narzoul** [comment]
I'm closing this issue because the author seems to have abandoned it and I have insufficient info to go on. Feel free to reopen it anytime if you can provide the necessary information.
