### ISSUE TITLE
Empire Earth Freeze with v0.3.1

### ISSUE THREAD

**Issue by EEP-SleePer** [narzoul/DDrawCompat#100]
If i wanna start a game in EE Multiplayer - EE Freeze
if i go to Singleplayer -> Random Map - > EE Freeze

(Win10, 1920x1080px, Empire Earth Retail)

**Comment by narzoul** [comment]
I tested the GOG version briefly, I get no freezes. There is a firewall popup, isn't that stopping your game somehow? Does it work fine without DDrawCompat?

**Comment by EEP-SleePer** [comment]
the game just freezes when i click on "play" in multiplayer.  and I don't even come back to the desktop, I can only log out and log in again with Ctrl + Alt + F4, otherwise nothing reacts anymore.
I forgot to say, I also used DREXMOD2.0 (if it tells you something).

The first thing I noticed positively about your v0.3.1 script is that the cursor in the EE lobby moves much more smoothly and does not stutter.

here is log file:
22:13:27.452 Process path: C:\Sierra\Empire Earth\Empire Earth.exe
22:13:27.452 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation"
22:13:27.452 Loading DDrawCompat statically from C:\Sierra\Empire Earth\DDRAW.DLL
22:13:27.470 DDrawCompat loaded successfully
22:13:27.605 Installing display mode hooks
22:13:27.609 Installing registry hooks
22:13:27.609 Installing Direct3D driver hooks
22:13:27.611 Installing Win32 hooks
22:13:27.614 Hooking user mode display driver: C:\WINDOWS\System32\DriverStore\FileRepository\u0367492.inf_amd64_dc9dba40afc0f9b5\B367342\aticfx32.dll+0x60520
22:13:27.631 Dynamic vertex buffers are available
22:13:27.631 Dynamic index buffers are available
22:13:27.633 Checking source color key support: passed
22:13:27.634 Incorrect z-buffer bit depth capabilities detected; changed from "16, 32" to "16, 24"
22:13:27.636 Installing DirectDraw hooks
22:13:27.637 Installing Direct3D hooks
22:13:27.640 Installing GDI hooks
22:13:27.652 Finished installing hooks

maybe something will bring you

**Comment by narzoul** [comment]
Please reproduce the issue with the ReleaseWithDebugLogs build (in the debug zip file) and attach the logs from that (compressed, if possible).

A crash dump could be needed also, but logs are easier to get and might be enough in itself, we'll see.

**Comment by EEP-SleePer** [comment]
i testet on GOG Version now to, same Problem, EE freeze, what i make wrong, do i need anything extra?

**Comment by EEP-SleePer** [comment]
here is the .log file
https://drive.google.com/file/d/1yBOLpL4QKsE1x-LWSAjzkek0YQDzT8dZ/view?usp=sharing

**Comment by narzoul** [comment]
It seems to be a deadlock on the main thread, but it also happens suspiciously directly after some NeoEE related overlay(?) window is closed. Did you check the GOG version without any external mods or patches? Could you please upload logs from a clean install without mods?
