### ISSUE TITLE
Titanic Adventure Out of Time Shows Blank Screen When Save Dialog Or Quit Dialog Comes Up

### ISSUE THREAD

**Issue by x1fu** [narzoul/DDrawCompat#102]
Thank you very much narzoul for this awesome program! It works great with the original Grim Fandango and The Longest Journey!

Unfortunately, when I try to save in Titanic Adventure Out of Time (DirectX Version) the screen is blank and only shows a vertical scroll bar see attached picture. When I quit the game, the screen is blank when it should show a "Are you sure you want to quit?" dialog box. When I hit Enter, then it shows "Do you want to save?" dialog box just fine. I think the game uses DirectX 5. That was the version included with the disc. Here is the log:

19:03:42.119 Process path: C:\CyberFlix\DirectX Version\Titanic\TI.EXE
19:03:42.119 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation HighDpiAware 640X480 DetectorsXP"
19:03:42.119 Loading DDrawCompat statically from C:\CyberFlix\DirectX Version\Titanic\DDRAW.dll
19:03:42.126 DDrawCompat loaded successfully
19:03:43.666 Installing display mode hooks
19:03:43.675 Installing registry hooks
19:03:43.675 Installing Direct3D driver hooks
19:03:43.675 Installing Win32 hooks
19:03:43.680 Hooking user mode display driver: C:\Windows\SYSTEM32\igdumdim32.dll+0x1000
19:03:43.687 Dynamic vertex buffers are not available
19:03:43.687 Dynamic index buffers are not available
19:03:43.688 Checking source color key support: passed
19:03:43.689 Installing DirectDraw hooks
19:03:43.690 Installing Direct3D hooks
19:03:43.693 Installing GDI hooks
19:03:43.698 Finished installing hooks
19:04:19.525 DDrawCompat detached successfully

![titanicsavescreen](https://user-images.githubusercontent.com/85190609/120371212-6287f300-c30d-11eb-9f69-21bcc3c436ea.jpg)

**Comment by narzoul** [comment]
I don't have this issue with the save dialog, and on first try I didn't with the quit dialog either. But on further tries I could reproduce it with the quit dialog at least. I'll look into it later. Meanwhile you can try moving the window (by grabbing the title bar) as a workaround, it seems to cause the window to show up properly.

I think it has something to do with incorrect Z-order between the real window and DDrawCompat's presentation overlay window, which probably gets shuffled behind it somehow at first.

**Comment by x1fu** [comment]
Thanks for looking into this issue! Unfortunately, when I move around the window by grabbing the title bar, there is no change to what is shown on screen. Let me know if you want any debug logs or more screen pics.

Here are my system specs if it helps:

Windows 8.1
CPU: Intel i5-4210U
GPU: Intel HD 4400
RAM: 8GB

**Comment by narzoul** [comment]
Fixed in v0.4.0.
