### ISSUE TITLE
Beach Life game is flickering

### ISSUE THREAD

**Issue by JoeIbr** [narzoul/DDrawCompat#110]
Hey Narzoul, thanks for the files and fixes!

I have downloaded the DDraw.dll for Beach Life (32 bit) by Eidos on Windows 10.
The game stopped lagging, and I can tell it is running great after pasting the dll file - However, the game is flickering every time I run it, and the screen is always shaking and showing black lines.

Is there a fix for that? Or is there a step I missed?

Below are my computer's specs for reference:
Device name	DESKTOP-E765GR9
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	104B9AD1-05C9-41F7-B138-BD7EAC8B3DF1
Product ID	00330-80000-00000-AA531
System type	64-bit operating system, x64-based processor

**Comment by narzoul** [comment]
Why did you close the issue? Did you find a solution?
I tested it briefly with v0.3.1 on both my dedicated Radeon RX 480 and integrated Intel HD 4600, and didn't notice any graphical issues with either. Do you have a dedicated GPU in your system?

**Comment by narzoul** [comment]
Ah ok, managed to reproduce it now. It only happens in multi-monitor setups with extended desktop mode. I guess it's the usual issue with the game not respecting surface pitch vs width differences.

I have a solution in the works already, but the next release is probably a few weeks/months away still. The only workaround is to use single monitor desktop mode in the meantime.

**Comment by JoeIbr** [comment]
Actually, it was a silly issue - The HDMI cable was connected to my laptop, and whenever I had a second display on my system it flickered. When the cable is unplugged, the game works fine
