### ISSUE TITLE
Anti-Aliasing Performance (Tom Clancy's Rainbow Six: Rogue Spear)

### ISSUE THREAD

**Issue by B00TP** [narzoul/DDrawCompat#115]
Firstly, thank you for such an accurate wrapper.

I usually like to tweak and enhance graphical settings in the NVIDIA Control Panel and NVIDIA Profile Inspector, in particular with regarding to an anti-aliasing, anisotropic filtering, and texture filtering. When using the wrapper (with Rogue Spear) I can force anti-aliasing and it takes effect, but I have noticed that even setting the anti-aliasing to 2x results in a massive performance drop. Obviously, games of this era can normally be run at 8x anti-aliasing (and 8x transparency) without issue. I wondered if this performance drop is expected behaviour indicative of using the wrapper, is game specific, or if I am missing something else?

For reference, my GPU is an NVIDIA GeForce GTX 1060 6GB.

**Comment by narzoul** [comment]
I don't have an NVIDIA GPU for testing this, and forcing antialiasing in AMD Radeon drivers doesn't seem to do anything.
I will be adding antialiasing and some other features to the next release though (no ETA). I don't know how it will perform with NVIDIA, but I still get maxed FPS (144) on Radeon with 8x MSAA.

**Comment by narzoul** [comment]
Antialiasing setting has been added in v0.4.0. Let me know if it still has poor performance for you, but it seems to work fine on my end with an older NVIDIA GPU.
