### ISSUE TITLE
The Sims 1 immediately crashes when using two monitors

### ISSUE THREAD

**Issue by Demiresh** [narzoul/DDrawCompat#119]
Greetings!

The Sims 1 immediately crashes when using two monitors, but if change "Expend these displays" to "Duplicate these displays" in multiple display settings, then the game will start OK, but it isn't comfortable to me. Is there any way to fix it?

Sorry if my English is not well, it's not my language.

**Comment by narzoul** [comment]
Is this on Windows 10 with DDrawCompat v0.3.1? Works fine for me with "Extend these displays". Please attach debug logs from the crash with the ReleaseWithDebugLogs build (in the debug version).

You can also try "Show only on 1" or "Show only on 2", no need to duplicate displays, if that's better.

**Comment by Demiresh** [comment]
Here.
[DDrawCompat-Sims.log](https://github.com/narzoul/DDrawCompat/files/7516386/DDrawCompat-Sims.log)

The game doesn't start either with "Show only on" mode, only with "Duplicate these displays" for some reasons.
Here's log with this mode.
[DDrawCompat-Sims (Show only on).log](https://github.com/narzoul/DDrawCompat/files/7516400/DDrawCompat-Sims.Show.only.on.log)

**Comment by narzoul** [comment]
Thanks! The logs are very similar to the ones in this other issue: https://github.com/narzoul/DDrawCompat/issues/65
Do you have G-sync enabled? Try disabling it in NVIDIA control panel, at least for this game (or any other game that you use with DDrawCompat). I'm thinking that using "Duplicate these displays" probably disables it automatically, that's why it works.

**Comment by Demiresh** [comment]
Yeah, G-sync was the problem. Disabling it for the game and enable after is an uncomfortable solution either, but more better than previously one.
Thanks for the help. I don't think I would have figured it out on my own.

**Comment by narzoul** [comment]
You shouldn't have to disable it globally every time you launch the game. It should be possible to add an application-specific profile that disables it only for Sims.exe. I haven't had an NVIDIA GPU for a long time, so I'm not sure how to do it nowadays, but you should be able to find some guide online about how to add application profiles.

**Comment by Demiresh** [comment]
Oh, yes, I knew about possibility to add an application-specific profile, but I didn't think about possibility to disable G-sync from there, and it's actually possible! Now the issue is solved I'm very grateful for helping me and, taking the opportunity, I would like to say thank you for this project!
