### ISSUE TITLE
Thank you for the great works.

### ISSUE THREAD

**Issue by mnii1** [narzoul/DDrawCompat#12]
Hello.

I would like to appreciate your works of the ddraws for old directx. having registered this site to write a bit words of thanks.

I've been using a win8.1 laptop(intel hd5500 & nvidia840m optimus), and struggled with running old flight sim games which are combat flight simulator 1,2 and jane's IAF.

Now I could run these games with proper graphics and more smooth fps. (Rowan's mig alley works too. Although fps during flying over the terrain is unplayable, couldn't even go to the cockpit screen in the past.)

Thank you very much again.

**Comment by narzoul** [comment]
Thank you for the kind words and sorry about the late reply! I do usually read every comment within a day or so because I get e-mail notifications about them, even if I don't respond immediately.

I tried to look into Mig Alley a while back since I found a demo version of it somewhere on the internet, but I've been unable to get it to work so far. The main menu appears largely broken even initially, and once I try to start a new game it goes almost completely black with just a small dot around the middle and I have no idea where to click to proceed.

Looks like it might be some GDI issue on a first guess. I might give it another go in the future, but I have plenty of other issues to work on already and I haven't been in the mood lately to spend most of my (limited) free time on them, so progress has been quite slow.

**Comment by mnii1** [comment]
Thank you for the reply and dealing with Mig Alley game. I've held off posting a reply because if I post, it might be another kind of burden to a developer. (Nevertheless it seems I was too late.)

I just tried this game by chance a few days ago, and it seemed worked. I'm not sure what happened on my laptop for several months though. Frame rate was low, however the same issue was also there on a win7 PC I had before.

Thank you.

**Comment by pts85** [comment]
Hi

Very nice work narzoul!

DDrawCompat seems to fix video/mouse -color issues running fallout 1 demo (i guess it works on full version too) on Windows 7 64bit, when accompanied with following compability flags: 
- WIN98 
- Layer_ForceDirectDrawEmulation. 

Latter is hidden setting, reg-file:

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"C:\\fallout1demo\\falldemo\\Falldemo.exe"="WIN98 Layer_ForceDirectDrawEmulation"

**Comment by narzoul** [comment]
As far as I know Fallout should work without extra compatibility settings too, but I admit I haven't been able to test anything on Windows 7 for a very long time.

At least the second option is definitely suspicious as it should be explicitly ignored by DDrawCompat (since I actually found severe compatibility issues with it). Isn't the following line written in the log?
`Suppressed a request to create an emulated DirectDraw object`

**Comment by pts85** [comment]
> 
> 
> As far as I know Fallout should work without extra compatibility settings too, but I admit I haven't been able to test anything on Windows 7 for a very long time.
> 
> At least the second option is definitely suspicious as it should be explicitly ignored by DDrawCompat (since I actually found severe compatibility issues with it). Isn't the following line written in the log?
> `Suppressed a request to create an emulated DirectDraw object`

This was the original fallout 1 demo (https://archive.org/details/FalloutDemo).

- Without "ddraw.dll" and with only "WIN98" compability setting, i get green videos and black screen problem, where in the game screen goes black and you can only see game screen by moving mouse all around, until it almost immediately goes black again (game is unplayable).

- Without "ddraw.dll" and with "WIN98" and "Layer_ForceDirectDrawEmulation" settings , i get green videos and cannot get even to main menu.

- With "ddraw.dll" and only "WIN98" setting, videos are rightly colored, but black sreen problem remains.

It seems that when using "ddraw.dll" and setting "Layer_ForceDirectDrawEmulation" (and "WIN98") the black screen problem goes away and everything seems ok. 

Logs:

Without Layer_ForceDirectDrawEmulation:
4700 19:51:39.054 Process path: C:\fallout1demo\falldemo\Falldemo.exe
4700 19:51:39.054 Loading DDrawCompat from C:\fallout1demo\falldemo\DDRAW.dll
4700 19:51:39.054 DDrawCompat loaded successfully
4700 19:51:42.330 Installing DirectDraw hooks
4700 19:51:42.424 Installing GDI hooks
4700 19:51:42.424 Installing registry hooks
4700 19:51:42.424 Finished installing hooks
4700 19:51:43.610 GDI used DC cache size: 1
4700 19:52:17.874 Detaching DDrawCompat
4700 19:52:17.889 DDrawCompat detached successfully

With Layer_ForceDirectDrawEmulation:
3544 19:58:26.587 Process path: C:\fallout1demo\falldemo\Falldemo.exe
3544 19:58:26.587 Loading DDrawCompat from C:\fallout1demo\falldemo\DDRAW.dll
3544 19:58:26.587 DDrawCompat loaded successfully
3544 19:58:28.599 Installing DirectDraw hooks
3544 19:58:28.615 Installing GDI hooks
3544 19:58:28.615 Installing registry hooks
3544 19:58:28.615 Finished installing hooks
3544 19:58:29.800 Failed to create a GDI DC: -2005532087
3544 19:58:53.546 Detaching DDrawCompat
3544 19:58:53.562 DDrawCompat detached successfully

Error "Failed to create a GDI DC: -2005532087"  didn't seem to affect gameplay or atleast i didn't notice anything...

**Comment by realmofevil** [comment]
Hey, thanks for this tool. Just wanted to mention if you were not aware of this https://github.com/crozone/DirectDraw-Compatibility-Changer which I think is the same person that made the http://www.nma-fallout.com/resources/directdraw-compatibility-tool.95/

**Comment by narzoul** [comment]
I tried to fix the performance issues in Rowan's Mig Alley in the latest experimental release. It runs at solid 50 fps (which seems to be the cap) on my AMD Radeon RX480 now. Unfortunately I could not test any Nvidia GPU. Hopefully those run well too. If you notice any graphical glitches or it's still too slow in same places, please let me know.

This should also fix 3D performance issues in some other games, such as Midtown Madness 2.

**Comment by mnii1** [comment]
I've tried your latest and experimental version with Mig Alley in my laptop. My game version was BDG 0.85F and which version is needed to work joystick in win XP and after. My system was the same as before, graphic detail levels were 800x600 res and almost max for other options, also all(max) of texture filtering option. I played it in win XP2 compatibility mode.

In a quickplay mode like Hotshot of the game, fps was as high as 50 and I would like to say it was fantastic. Shot down a Mig 15 without issues, seemed no graphic glitchies. I don't think I've ever played such high fps in the game before. 

And then went to campaign mode and tested first scenario and first mission. On the runway of Taegu air base in South Korea with 3 wingmen to take off, fps was still as high as 50 while I looked around in cockpit screen. So I increased 12 wingmen to 3 (total 15) to see how fps would be going in the same mission, and fps went around 20 on the runway. I think it was playable as well in such number of planes around and close to my plane, with my old laptop. 

Besides the 3d world, there was flicking screen issue on 2d map screen whenever mouse cursor was moving over icons. Other than that, it seemed other noticeable issues weren't found on it. (If I see other issues later, I will post about them.)

So far and overall I think this latest version is obviosly remarkable step for Mig Alley game, perhaps for other games too. I really appreciate your works and skills have been there for a long time. 

Honestly I didn't think any driver or program for the game's framerate would be made because Mig Alley wasn't that popular unlike Midtown Madness series or so. 

Thank you very much!!

**Comment by narzoul** [comment]
Thanks for the report!

That flashing was way too annoying, so I fixed that already. Check the updated experimental release.

I know there are still a few 2D glitches around, like things that are supposed to be rectangular (tooltip frames, combo and edit boxes) have a diagonal line across them and missing some other edges instead. The main menu is not fully redrawn when exiting from the campaign map. Also things are a bit (ok, maybe a lot) more sluggish when drawing these windows/controls than without DDrawCompat. Improving these things could take a lot longer though, for now it should be at least playable.

I would like some help with setting up the scenario the way you did though. The campaign planning part is way too confusing for me. All I could figure out so far is how to enter a mission by pressing the Frag button in the toolbar, and then Fly. But how do you increase the number of wingmen to 15?

**Comment by mnii1** [comment]
Yes, I have those 2D glitches too, and some fonts are disappeared when selecting mission types or options in quick mission mode. Those don't seem to affect gameplay that much fortunately. Flickering issue is now gone away by using new experimental driver. 

I have attached 3 images that are about how to add wingmen up to 15 on map screen, which way was found by chance while I was fiddling with map screen. My paper manual didn't seem to tell about it well enough as far as I know. 

In addition to that, objects like buildings and airfields, bridges etc can be seen by going into 3d world from 2d map screen directly. When clicking on any building etc icon on map, then Dossior menu will pop out and there is a Photo button which leads to 3d world view of those objects. But result of pressing the button will be freezing of the game, or maybe need to reboot the OS. Which crash won't happen if get into 3d world(like by doing a quickgame regardless of time of play) once before pressing the button.

Thank you! 

![MA01](https://user-images.githubusercontent.com/25895857/83119736-0e9b6a80-a10b-11ea-9f88-f3532dac5770.jpg)
![MA02](https://user-images.githubusercontent.com/25895857/83119743-10652e00-a10b-11ea-99b6-1b4213e341a5.jpg)
![MA03](https://user-images.githubusercontent.com/25895857/83119744-10fdc480-a10b-11ea-80a6-d40bdd3a03b7.jpg)

**Comment by narzoul** [comment]
Done another round of performance fixes, should get FPS up to at least 30 with 15 wingmen around. This seems to be about the max I can get out of it for now.

I was actually able to go all the way up to 50, but only by practically forcing triple buffering on the game, which I'm not sure I want to do without adding a config option for it (so not until after the next major release at least). I think this means the game would actually be running somewhere between 50 and 60 fps now if it wasn't internally limited to 50. So on a 60 Hz display like mine it gets halved to 30 fps due to v-synced double buffering. If you have a high refresh rate monitor (100+Hz) you might actually get 50 fps even with double buffering.

Windows 8 compatibility mode should no longer be needed either, and disabling it might improve performance a bit also. For me, disabling it was needed to get stable 50 fps with triple buffering.

I still need to look into the 2D glitches and the system instability when clicking on the Photos button.

**Comment by mnii1** [comment]
I tested the driver in both XP2 and without compatibility modes.(Enabled DPI setting and adiministrator on both). With 15 wingmen on runway, about 34 and 41 of each were the lowest fps. Overall I got noticeable good results and the later was 6-7 frames higher than XP2 mode. One reason that XP2 compatibility has been used for the game was speech sounds that have worked in the mode, but now I saw the sounds also work well with the experimental driver without compatibility mode. 

Unfortunately, Intel HD 5500 in my laptop didn't offer any buffering option to test or change something about them, even after updating its graphic driver by an included manage utility, which utility is only way to update the driver in the laptop. Generic drivers on Intel page failed to do so. I'm sorry about that. Perhaps that is a kind of limitation of the chipset's software so far. 

Mig Alley looks only detects primary graphic hardware like many other old games and HD 5500 is it of the laptop. Nvidia 840m is the secondary. 

In the meantime, there was a small difference without compatibility mode on map screen. Borderlines of popup menu boxes were thicker. I think you already know it. The pic is below. 

![1162](https://user-images.githubusercontent.com/25895857/85363339-a306ba80-b55b-11ea-9459-ab6a58a1b8ca.png)

**Comment by narzoul** [comment]
I think I've fixed all of the reported 2D glitches in the latest experimental release. Speed still needs to be improved there.

I couldn't find a simple way to fix the window borders from the wrapper, but it can be fixed via Microsoft Application Compatibility Toolkit by applying the NoPaddedBorder shim to the game. Simply using Windows 8 compatibility mode on the executable works too, but it applies some other unnecessary fixes that could reduce performance a bit.
Alternatively, there is a way to remove the padded borders via the registry, but that would affect all captioned/resizable windows in the system.

I also couldn't find a way to fix the system freeze when viewing photos, at least not without breaking other games. It'll need a config option in a later release.

**Comment by optimuscream** [comment]
I am able to play Colin Mc Rae 2 with SilentPatchCMR (https://github.com/CookiePLMonster/SilentPatchCMR2) and this DDrawCompat . With only SilentPatch the games run with stutter all the time. Now with this DDrawCompat, I can play the game with all settings maxed out and very smooth fps . Great work sir !!.

**Comment by mnii1** [comment]
Hi. I'm really sorry for not posting anything about Mig Alley over 8 months. I had to do some difficult events etc by myself for months. In addition, all stuffs in my laptop had to be installed again due to error of partition backup recovery. 

I ran the game today with the ddraw file made on Jan 13th, in win8 compatible mode. I think overall it works good now. Perhaps other newer or latest hardwares might have some issues, I hope I get new one near future though. 

I'm sorry again, and I appreciate these efforts and results over years.

**Comment by Alex85006** [comment]
Thank you Narzoul for the work on this project, it is fantastic to get Mig Alley running on my W10 system, I've been trying everything for years, you RULE! V 0.4.0 with the ini set for no palette, resolutions restricted and all filtering in game looks great, loads fast on my old r9 380.
