### ISSUE TITLE
Bad performance in Windows 7 (v0.3.1)

### ISSUE THREAD

**Issue by MiraakThuri** [narzoul/DDrawCompat#120]
Hey, so im running Windows 7 64 bits and have a few old games that run on directx 7
they have fine performance by default (some needed some tweaks, some didn't) but i wanted to try your wrapper to see if i could get better performance.
I tried it on RealMyst and Alien versus Predator 2 but with it, the performance is just awful, the game is running at like 2 fps
Im running all my games in exclusive fullscree

im adding my avp2 log, dunno if u need it
[DDrawCompat-lithtech.log](https://github.com/narzoul/DDrawCompat/files/7557564/DDrawCompat-lithtech.log)
n

**Comment by narzoul** [comment]
This is a known issue for Windows Vista/7 since v0.3.0. I don't have a proper solution yet, but you could try the quick fix attached in this comment to see if it helps: https://github.com/narzoul/DDrawCompat/issues/104#issuecomment-869168178

**Comment by MiraakThuri** [comment]
Yes this is fixing the performance issue, thx

**Comment by narzoul** [comment]
The Windows 7 performance issues have been fixed in v0.4.0.
