### ISSUE TITLE
Crashing when launching Sakura Taisen PC (2006 Windows XP rerelease)

### ISSUE THREAD

**Issue by KingKrouch** [narzoul/DDrawCompat#121]
When I attempt to launch the game using DDrawCompat, the game decides to crash. Figured I'd post my log here if that would be helpful.

Here's what occurs when I launch the release binaries: [DDrawCompat-ADVcore.log](https://github.com/narzoul/DDrawCompat/files/7682216/DDrawCompat-ADVcore.log)

Here's what happens when I attempt to launch it using the binaries in the debug binaries: [DDrawCompat-ADVcore.log](https://github.com/narzoul/DDrawCompat/files/7682234/DDrawCompat-ADVcore.log)

**Comment by narzoul** [comment]
It's crashing in _D3DDDI_DEVICEFUNCS::pfnPresent1. You have to turn G-Sync off for DDrawCompat (more specifically, for exclusive full-screen mode I suppose, but nobody has tested that without DDrawCompat). See https://github.com/narzoul/DDrawCompat/issues/65#issuecomment-625987367.

**Comment by KingKrouch** [comment]
Thanks! This managed to help fix the crashing.
