### ISSUE TITLE
UI elements high contrast

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#122]
When using DDrawCompat, the menu bar elements get a very high contrast and in some cases they are not visible. Under native Windows, or Windows 9X the UI had black text, but now when hovered over the options, they get a different colour contrast. Can you fix this?
![ddrawmenubar](https://user-images.githubusercontent.com/64649734/145598409-61cf3055-2102-4f14-9705-039beea1fa86.png)

**Comment by narzoul** [comment]
Please specify which game and OS you are using. I've never seen this problem in any menus I've tested.

**Comment by BEENNath58** [comment]
> Please specify which game and OS you are using. I've never seen this problem in any menus I've tested.

I am using Windows 11 Pro. The game here is Virtua Cop.

**Comment by narzoul** [comment]
The PC version seems to be a full screen game with no such menus. Are you using an emulator or something with another version? Where is that menu?

**Comment by BEENNath58** [comment]
> The PC version seems to be a full screen game with no such menus. 

The menu bar can be accessed by pressing the Alt key. 

I am using thr Virtual Cop 2 from myabandonware

**Comment by BEENNath58** [comment]
Any update?

**Comment by narzoul** [comment]
It will be fixed in the next release. No ETA.

**Comment by narzoul** [comment]
Fixed in v0.4.0.
