### ISSUE TITLE
Crashes when you try to save

### ISSUE THREAD

**Issue by xpsycox** [narzoul/DDrawCompat#123]
I'm trying an old game (Metal_Knight_Mission_Terminate_Resistance), it crashes every time I try to save

**Comment by MarkSpizu** [comment]
Sorry but his has nothing to do with DDraw.

**Comment by narzoul** [comment]
Indeed, this has nothing to with DDrawCompat, but I found a solution here:
https://www.reddit.com/r/abandonware/comments/z4gmj7/i_was_finally_able_to_play_my_first_ever_rts_in/?rdt=64126

In short, you have to create a "sav" directory inside the game directory to fix the crash.
