### ISSUE TITLE
Issues in Icy Tower

### ISSUE THREAD

**Issue by LeftyyGD** [narzoul/DDrawCompat#124]
First of all here's the invite to the Icy Tower Discord Server so you can download the game: https://discord.gg/TC9J8GreEZ

Version 0.2.1 fixes the slow motion issues on Windows 10 but also introduces some issues too:
In-Game screenshot feature doesn't work,
You can't record the game with OBS unless it's windowed mode.

Versions newer than 0.2.1 introduce micro-stutter into the game.

Please fix, thank, 
      Regard, Leftyy,

**Comment by MarkSpizu** [comment]
Screenshots or records it's the game fault. Bad coding.

**Comment by narzoul** [comment]
I haven't noticed any stuttering with v0.3.1. Is it still stuttering with v0.4.0?
OBS cannot record ddraw games running in exclusive fullscreen mode, I think. v0.4.0 changes the fullscreen mode to borderless by default, which should be more compatible with recorders.
Screen shots don't work for me even natively, does it work for you without DDrawCompat?

**Comment by narzoul** [comment]
Closing due to no response.
