### ISSUE TITLE
Black background in Galshell

### ISSUE THREAD

**Issue by orobas0** [narzoul/DDrawCompat#125]
Game: Galshell BloodRedSkies 2.0
DDrawCompat version: 0.3.1
OS: Windows 10

After starting a new game, the moment you press the shot button (SHIFT or Z) the background disappears and remains black.
As far as I've seen, the rest of the game seems to run as expected.
The game is freeware (NSFW warning).

Let me know if you need any other info.
Thank you in advance.

**Comment by MarkSpizu** [comment]
Tested and it's working fine with v0.2.1

**Comment by orobas0** [comment]
@MarkSpizu
Thanks, just tested with v0.2.1 as you suggested, it's working fine here too.

**Comment by narzoul** [comment]
Strange, it works fine for me even with v0.3.1. Is this still an issue in v0.4.0?

**Comment by narzoul** [comment]
Closing due to no response.
