### ISSUE TITLE
Sims 1 crashes on launch

### ISSUE THREAD

**Issue by Fierce-Deity-Link** [narzoul/DDrawCompat#127]
Whenever I try using DDrawCompat to launch the game, it crashes about a second after the load music starts playing. I've used another basic laptop however that runs the game with this wrapper without issues.

My main computer (that crashes with DDrawCompat)-

- Windows 10
- Intel i7-8700K CPU
- 64 GB RAM DDR4 2666 MHz
- Nvidia GeForce GTX 1080

The laptop that can run Sims 1 and the wrapper without issues:

- Windows 10
- AMD Ryzen 5 3500U
- 6 GB RAM
- (Integrated graphics)

Is there something I have to adjust on my end for it to work? Or is this a hardware incompatibility?

**Comment by narzoul** [comment]
If you have g-sync enabled, try turning it off. If that works, you can make an application profile for it in NVIDIA control panel, there is no need to turn it off globally.

**Comment by Fierce-Deity-Link** [comment]
Looks like that got it working ok now, thanks for the help.
