### ISSUE TITLE
Does DDrawCompat work with Win11?

### ISSUE THREAD

**Issue by Beats24-7** [narzoul/DDrawCompat#128]
Hi there,
I have tried to use DDrawCompat 0.31 with Stronghold HD on Win11. The game immediately crashes upon startup though. The log file shows  

18:41:13.586 Process path: E:\Stronghold HD\Stronghold.exe
18:41:13.586 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation"
18:41:13.586 Loading DDrawCompat statically from E:\Stronghold HD\DDRAW.dll
18:41:13.596 DDrawCompat loaded successfully
18:41:13.622 Installing display mode hooks
18:41:13.627 Installing registry hooks
18:41:13.627 Installing Direct3D driver hooks
18:41:13.627 Installing Win32 hooks
18:41:13.641 Hooking user mode display driver: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_642e50d7b66aa2a4\nvldumd.dll+0x98a0
18:41:13.717 Dynamic vertex buffers are available
18:41:13.717 Dynamic index buffers are available
18:41:13.720 Checking source color key support: passed
18:41:13.722 Installing DirectDraw hooks
18:41:13.722 Installing Direct3D hooks
18:41:13.726 Installing GDI hooks
18:41:13.735 Finished installing hooks
18:41:13.762 Suppressed a request to create an emulated DirectDraw object

It works on fine on Win10. Is there any fix for Win11? Thanks in advance! 

Kind regards

**Comment by narzoul** [comment]
It should work on Windows 11 too. The GOG version works fine for me. Does it crash without DDrawCompat? Did it work on Windows 10 without DDrawCompat?

I'm not getting the "Suppressed a request to create an emulated DirectDraw object" log, so your version must be different.

If it doesn't crash without DDrawCompat, please get debug logs from the ReleaseWithDebugLogs build.

**Comment by Beats24-7** [comment]
Hey, thanks for your reply. I don't get the "Suppressed a request to create an emulated DirectDraw object" text anymore either now. It still doesn't work though.
It works fine without DDrawCompat on Windows 11. On Windows 10 it works with and without DDC. Didn't they change sth. with DirectDraw in Win11? I attached the debug log for you. 

Thanks again

**Comment by narzoul** [comment]
Oh, it crashes in pfnPresent1. You probably have G-Sync enabled now and didn't have it on Windows 10. It's not compatible with exclusive full-screen mode. You'll have to disable it for now until I find some other solution for it (like a borderless windowed mode or something).

**Comment by Beats24-7** [comment]
Yes, you are right. It's working without G-Sync! Thanks for the quick check and reply. Ok, that would be cool if you could fix this with a borderless window mode or sth. in the future. Thanks again

**Comment by narzoul** [comment]
Borderless windowed mode has been added and enabled by default in v0.4.0. It should solve the G-Sync problem.
