### ISSUE TITLE
More help with MiG Alley please! (WIndows 10)

### ISSUE THREAD

**Issue by jsdnav** [narzoul/DDrawCompat#129]
Hi! This looks wonderful. After years of assuming I would never get MiG Alley working in Windows 10, I'm inspired to see that other people have managed it! However, I can't.... :( 

I've opened a new issue here, rather than follow TheSilkMan's existing conversation. I don't think our problems are the same.

My system is a  i7-1165G7 laptop with RTX 3070 GPU, displaying through a widescreen monitor via Display Port. MiG Alley is selected to use the RTX 3070 rather than the i7 CPU's integrated graphics (Windows graphics settings). Only the monitor is showing as active in Windows when I try to run the game (ie the laptop display is not visible in display settings, the laptop is closed with the screen asleep, and Windows shows I am in single display mode). WIndows 10 and Nvidia drivers are up to date.

I have installed MIG Alley (1.1 exe), patched to 1.23 and BDG 0.85F. I have moved/modified files to play without CD in drive, per instructions found elsewhere. I haven't tried other methods of getting this to run yet, I've come straight to DDrawCompat, at v0.3.1.

The closest I can get to making the game work is with the first modified 0.3.1 dll you provided to TheSilkMan (where you removed enumeration of 8 and 32 bit display modes). Running in Win 98 compatibility mode and as administrator, the main game menu works perfectly, with the correct 4:3 ratio centered in my widescreen display. I can access game preferences, campaign map, single mission launcher etc. The campaign map stretches to fullscreen, correctly scaled and usable across the entire screen.

When I try to launch a mission I see the blue/red aircraft loading screen (in fact there are two windows displayed on my monitor). I then get a resolution change to fullscreen, and can see and move the brown in-game pointer for a few seconds before CTD. 

Here's the main menu (fully functional):

![IMG_2183](https://user-images.githubusercontent.com/103973827/163916812-14722aee-41bb-47c7-becd-07037edd2859.jpg)

Here's the campaign map, correctly scaled and stretched to my widescreen display and with full function:

![IMG_2185](https://user-images.githubusercontent.com/103973827/163916827-54106523-ee73-475b-9e2e-194760a0c7c5.jpg)

Here's the loading screen with two windows, prior to CTD:

![IMG_2182](https://user-images.githubusercontent.com/103973827/163907725-0ddae443-504b-4dc6-a974-a015e499e4c7.jpg)

The crash dump log seems to highlight an issue with nvd3dum.dll. Presumably that's connected with the Nvidia driver, but at this point I have run out of knowledge.

If I try other compatibility settings I get worse results, ranging from  immediate CTD, to a grey window when trying to launch a mission (instead of the red/blue aircraft graphics) and CTD before seeing the in-game mouse pointer. 

The later modified 0.3.1 versions you provided to TheSIlkMan don't get me as far, the first modified 0.3.1 you posted for him works best for now. And I get the same results explained above with 0.2.1.

I guess this could be caused by a conflict between the integrated CPU graphics versus the Nvidia 3070 GPU.... Or the monitor display versus the laptop display, although I am running in single display mode (only the monitor is active, not the laptop screen).... However, it feels like something more fundamental. Other games work fine, without any conflict between integrated CPU graphics and GPU.

I'd be grateful for any help you can provide. This looks like a fantastic way to get this game running, I feel like I'm close but I'm not expert enough to make any more progress here.

I've attached the contents of the relevant crash dump log as a .txt file.

Thank you for your help!

[MiG Alley_19 April _Crash Dump 0.3.1.txt](https://github.com/narzoul/DDrawCompat/files/8509657/MiG.Alley_19.April._Crash.Dump.0.3.1.txt)

**Comment by narzoul** [comment]
If you have G-Sync enabled, turn it off for the game. It's a known issue with NVIDIA in exclusive fullscreen mode.

If that's not the problem, please use the ReleaseWithDebugLogs build from the debug zip to reproduce the crash, and attach the DDrawCompat log file (compressed).

**Comment by jsdnav** [comment]
Outstanding, thank you for the quick reply! Turning off G-Sync and Win 98 compatibility fixed this! 

I've installed the final modified 0.3.1 you supplied for TheSilkMan to fix missing textures/colours and it is working exactly as advertised.

I need to tinker with the Nvidia control panel to see if I can maintain aspect ratio during gameplay. At the moment the image is stretched to fill the screen, rather than displaying in 4:3 as it originally did. It's quite extreme on a 21:9 ultrawide monitor!

But right now it's just amazing to see and hear this game after so many years... Thanks again!

**Comment by narzoul** [comment]
Both the G-Sync issue and aspect-correct scaling should be solved in v0.4.0 with the default settings.
