### ISSUE TITLE
make it compatible with overlay game recorder

### ISSUE THREAD

**Issue by jcgo16** [narzoul/DDrawCompat#13]
hi its me again, i forgot to tell you that bandicam and other game capture app are not working on your ddraw.dll compatibility

http://o2jam.intgamerz.net

**Comment by narzoul** [comment]
Are there still any issues with overlays/recorders? From my limited testing, things that still don't work generally also don't work without DDrawCompat. I'm not sure I can improve compatibility any further in any case.

**Comment by narzoul** [comment]
Fullscreen recording should be ok now in v0.4.0. as long as the default borderless fullscreen mode is used. I'm not planning on further support for external hooks for now anyway.
