### ISSUE TITLE
Feature Request: Adding Scaling Modes to DDrawCompat

### ISSUE THREAD

**Issue by RedFalcon10** [narzoul/DDrawCompat#131]
Thanks a lot for your work on DDrawCompat as it is the only tool that makes Rainbow Six: Rogue Spear fully functional. However, I would really appreciate it if you can add a stretched, keep aspect ratio scaling mode to keep 4:3 forced menus like the main menu and others in their original 4:3 aspect ratio to avoid the constant resolution changes from in-game resolution to menu resolution as it is a really annoying thing in most old games. Other than that, DDrawCompat is working great with Rogue Spear so far.

Thanks!

**Comment by narzoul** [comment]
Display scaling was added in v0.4.0. It's enabled by default. Check the wiki for details.
