### ISSUE TITLE
problem with Deadly Dozen Pacific Theater

### ISSUE THREAD

**Issue by Pablo198989** [narzoul/DDrawCompat#132]
Deadly Dozen Pacific Theater working slow on my powerful pc.
Someone told me to use DDrawCompat, but when put the .dll file on game folder and run ,exe i had error not found entry point SymAddincludeInlineTrace in C:\WINDOWS\SYSTEM32\dbgeng.dll file

**Comment by narzoul** [comment]
If there is a dbghelp.dll file in the game directory, try renaming/removing it.

**Comment by narzoul** [comment]
I'm going to assume this has been fixed. With v0.4.0, there may be no need to delete the dbghelp.dll file either.

**Comment by Pablo198989** [comment]
yes its done, but more correct fix are written herehttps://www.gog.com/forum/deadly_dozen_pacific_theater/low_fpsOd: "narzoul" ***@***.***&gt;Do: "narzoul/DDrawCompat" ***@***.***&gt;; Wysłane: 22:44 Wtorek 2022-09-27Temat: Re: [narzoul/DDrawCompat] problem with Deadly Dozen Pacific Theater (Issue #132)

I'm going to assume this has been fixed. With v0.4.0, there may be no need to delete the dbghelp.dll file either.
