### ISSUE TITLE
Sims 1 crashing on launch

### ISSUE THREAD

**Issue by kttx9** [narzoul/DDrawCompat#133]
For quite a while I'm experiencing a crash when I try to run The Sims 1 using this wrapper. The game crashes on startup, and the stkdmp file logs this error:
`Exception code: C0000005 ACCESS_VIOLATION
Thread ID: 3044
Sound exec count: 0
`

**Comment by narzoul** [comment]
Does that mean it was working before, with the same version of DDrawCompat? What has changed on your system since then?

Please attach the debug logs of DDrawCompat using the ReleaseWithDebugLogs build.

**Comment by kttx9** [comment]
Exactly, not really sure what changed, I'd say nothing (apart from maybe a windows 10 update). Here's the log:

[DDrawCompat-Sims.log](https://github.com/narzoul/DDrawCompat/files/8627229/DDrawCompat-Sims.log)

**Comment by narzoul** [comment]
It looks like the "typical" crash when G-Sync is enabled in DirectDraw exclusive fullscreen mode. Try turning it off for the game, if it's on.

**Comment by kttx9** [comment]
You're 100% right! Turning off g-sync fixed the issue. Thanks!

**Comment by narzoul** [comment]
The G-Sync issue should also be solved in v0.4.0 when using the FullscreenMode=borderless setting, there should be no need to disable it manually anymore.
