### ISSUE TITLE
Add a rationale into the ReadMe or the wiki

### ISSUE THREAD

**Issue by KOLANICH** [narzoul/DDrawCompat#135]
A person that has accidentially run into this project, can have the following questions:

* What's wrong with the orignal DirecX? Why do I need this software? Are there any benchmarks prooving performance gains?
* Are there any unneeded side effects?
* Which cases I should use it?
* What does it exactly do?
* Is it related to Wine anyhow? Can it be used in Wine? Does it have any benefits when used within Wine?

**Comment by narzoul** [comment]
I've added a Support section to the readme to clarify some things (e.g. Wine, though not sure why anyone would think Wine is supported when the requirements already clearly stated Windows only). For the rest of the points, I'm not planning to add any additional documentation.

**Comment by KOLANICH** [comment]
Thanks.
