### ISSUE TITLE
Stuck at "Loading DDrawCompat dynamically"

### ISSUE THREAD

**Issue by yxles-dev** [narzoul/DDrawCompat#136]
I installed this on The Sims 1 Complete Collection but when I tried opening it, there's no windows showing up but the process is running in background. Opening the log shows this:

18:46:05.915 Process path: C:\Program Files (x86)\Maxis\The Sims\Sims.exe
18:46:05.915 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation RunAsAdmin WinXPSp2"
18:46:05.915 Loading DDrawCompat dynamically from C:\Program Files (x86)\Maxis\The Sims\DDRAW.DLL

It seems that it got stuck at loading DDrawCompat. Is there a way to fix this?

**Comment by narzoul** [comment]
Please attach the logs taken with the ReleaseWithDebugLogs build from the debug zip file. What OS are you using?

**Comment by yxles-dev** [comment]
> Please attach the logs taken with the ReleaseWithDebugLogs build from the debug zip file. What OS are you using?

Hi, I'm on Windows 11 and using ReleaseWithDebugLogs still outputs the same thing
[DDrawCompat-Sims.log](https://github.com/narzoul/DDrawCompat/files/9016267/DDrawCompat-Sims.log)

**Comment by narzoul** [comment]
Could you please create a crash dump from the process? Right click on Sims.exe in the Details tab of Task Manager while it's stuck, and choose "Create dump file". Compress and attach it.

Does the game launch natively without DDrawCompat? (You may have to enable Reduced color depth: 16-bit in the Compatibility settings on Sims.exe).

I'm assuming your system ddraw.dll (C:\Windows\SysWOW64\ddraw.dll) is the native Windows one. Maybe there is some other 3rd party tool interfering. The game works fine for me on Windows 11 except for the mouse cursor disappearing when moving it over the exit dialog box (which happens without DDrawCompat also).

Oh, also if there is a dbghelp.dll file in the game directory, try renaming or removing it.

**Comment by yxles-dev** [comment]
1. Sure, here is the crash dump
[Sims.zip](https://github.com/narzoul/DDrawCompat/files/9017132/Sims.zip)
2. Yes, I could play the game normally (if you don't count the graphical issues)
3. Afaik, I don't have any apps installed that can cause any interference (Mica for Everyone maybe I'm not sure)
4. I don't have dbghelp.dll on my directory

**Comment by narzoul** [comment]
Looks like you're on an Insider Preview build of Windows 11 23H2, which has some changes to dbgeng that causes the hang. It could be a bug that will be fixed in the normal release, or it could be a feature that will cause DDrawCompat to hang for everyone at that point. Unfortunately, I'm not an insider (and not interested in becoming one), so it looks pretty impossible for me to debug this until 23H2 (or whichever previous insider update introduced the issue) is released for normal users.

**Comment by betaxab** [comment]
@narzoul Now that 22h2 is the final version, can you see what's causing it?

**Comment by narzoul** [comment]
Should be fixed in both new releases (v0.3.2 and v0.4.0) now.
