### ISSUE TITLE
Grand Prix World - Windows 11 - Stuck at "Loading DDrawCompat statically"

### ISSUE THREAD

**Issue by Priyantha** [narzoul/DDrawCompat#137]
Hi,

I am trying to run the game Grand Prix World with the 2022 mod(https://gpmplanet.proboards.com/thread/197) created by 'Meanie'.
I replaced the ddraw.dll from that release already with the latest with Debugging enabled to provide some logs.
[gpw.zip](https://github.com/narzoul/DDrawCompat/files/9101065/gpw.zip)

So I have done a crash dump of the process(Task manager > Create dump file).
And the content of the logfile named "DDrawCompat-gpw.log" is copy/pasted below:

333c 11:54:38.398 Process path: F:\GPW2022\gpw.exe
333c 11:54:38.398 Environment variable __COMPAT_LAYER = ""
333c 11:54:38.398 Loading DDrawCompat statically from F:\GPW2022\DDRAW.dll

I am running:
Windows 11, Version 22H2 (OS Build 25151.1010)
Nvidia driver: 472.12

**Comment by Priyantha** [comment]
Thanks :-)
Will wait then when this build has become stable.

**Comment by narzoul** [comment]
Should be fixed in both new releases (v0.3.2 and v0.4.0) now.
