### ISSUE TITLE
Massive performance issues in Panzer Dragoon PC (1996)

### ISSUE THREAD

**Issue by nf33** [narzoul/DDrawCompat#138]
You can go find it on archive.org here:

https://archive.org/details/pdg-pc

**Comment by nf33** [comment]
Yeah I'm on windows 7 with a 1070, since Windows 10/11 is moving you to signed binaries, aka enjoy denuvo levels of drm in future apps going forward and being permanently spied on your webhabits while beaming that info to microsoft and the IP enforcement authorities.

**Comment by narzoul** [comment]
So, did the temporary fix work?

**Comment by nf33** [comment]
> 

Yup you're a genius!!  I thank you for helping us preserve old stuff.

**Comment by narzoul** [comment]
v0.4.0 should also contain the fix now.
