### ISSUE TITLE
DDraw deixou muito mais leve o game

### ISSUE THREAD

**Issue by oicoa** [narzoul/DDrawCompat#141]
Boa noite ddraw deixou muito mais leve o game porém alguns npcs ou mobs começam a sumir. consegue ajudar?

**Comment by mdsmendes94** [comment]
Qual o jogo?

**Comment by oicoa** [comment]
chama-se Laghaim um jogo do ano 2000


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Matheus ***@***.***>
Enviado: domingo, 28 de agosto de 2022 14:46
Para: narzoul/DDrawCompat ***@***.***>
Cc: oicoa ***@***.***>; Author ***@***.***>
Assunto: Re: [narzoul/DDrawCompat] DDraw deixou muito mais leve o game (Issue #141)


Qual o jogo?

**Comment by oicoa** [comment]
infelizmente ele sofre incompatibilidade com a atualidade, mesmo sendo um game leve acaba travando muito


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: iGoR R.Munhoz ***@***.***>
Enviado: sexta-feira, 2 de setembro de 2022 23:44
Para: narzoul/DDrawCompat ***@***.***>; narzoul/DDrawCompat ***@***.***>
Cc: Author ***@***.***>
Assunto: RE: [narzoul/DDrawCompat] DDraw deixou muito mais leve o game (Issue #141)

chama-se Laghaim um jogo do ano 2000


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Matheus ***@***.***>
Enviado: domingo, 28 de agosto de 2022 14:46
Para: narzoul/DDrawCompat ***@***.***>
Cc: oicoa ***@***.***>; Author ***@***.***>
Assunto: Re: [narzoul/DDrawCompat] DDraw deixou muito mais leve o game (Issue #141)


Qual o jogo?

**Comment by oicoa** [comment]
sabe se tem algo que podemos fazer?

**Comment by narzoul** [comment]
Sorry, I don't support online games anymore.
