### ISSUE TITLE
Deadlock 2 Shrim Wars is not working

### ISSUE THREAD

**Issue by sniper8952** [narzoul/DDrawCompat#142]
Hi narzoul

I bought Deadlock 2 Shrine Wars on Steam. On Windows 10 it worked with your solution. However, I have now installed Windows 11 on my PC and when I start the game I get the error message "DirectDraw Init FAILED".  Do you have any idea what this could be?

Here, I send you the ddraw.log
33840 11:24:26.260 Process path: C:\Program Files (x86)\Steam\steamapps\common\Deadlock2\DEADLOCK.EXE
33840 11:24:26.260 Loading DDrawCompat from C:\Program Files (x86)\Steam\steamapps\common\Deadlock2\DDRAW.dll
33840 11:24:26.265 DDrawCompat loaded successfully
33840 11:24:28.435 Installing DirectDraw hooks
33840 11:24:28.526 Installing GDI hooks
33840 11:24:28.651 Installing registry hooks
33840 11:24:28.651 Finished installing hooks
33840 11:24:29.603 Failed to create the real primary surface
33840 11:24:40.042 Detaching DDrawCompat
33840 11:24:40.125 DDrawCompat detached successfully

DdrawCompat-Deadlock.log:
11:04:36.718 Process path: C:\Program Files (x86)\Steam\steamapps\common\Deadlock2\DEADLOCK.EXE
11:04:36.718 Environment variable __COMPAT_LAYER = "RunAsAdmin 640X480 HighDpiAware 16BitColor WinXPSp3"
11:04:36.718 Loading DDrawCompat statically from C:\Program Files (x86)\Steam\steamapps\common\Deadlock2\DDRAW.dll
11:04:38.109 DDrawCompat loaded successfully
11:04:39.470 Installing display mode hooks
11:04:40.199 Installing registry hooks
11:04:40.199 Installing Direct3D driver hooks
11:04:40.199 Installing Win32 hooks
11:04:40.290 Hooking user mode display driver: C:\Windows\System32\DriverStore\FileRepository\u0370468.inf_amd64_5e4260b11257b6e9\B370372\aticfx32.dll+0x5ddc0
11:04:40.354 Dynamic vertex buffers are available
11:04:40.354 Dynamic index buffers are available
11:04:40.364 Checking source color key support: passed
11:04:40.367 Incorrect z-buffer bit depth capabilities detected; changed from "16, 32" to "16, 24"
11:04:40.402 Installing DirectDraw hooks
11:04:40.409 Installing Direct3D hooks
11:04:40.413 Installing GDI hooks
11:04:40.458 Finished installing hooks
11:04:42.554 ERROR: Failed to create the real primary surface: 0x80070057
11:04:46.640 DDrawCompat detached successfully

**Comment by narzoul** [comment]
The GOG version still works fine for me on Windows 11. Could you please attach debug logs taken with the ReleaseWithDebugLogs build (from the debug.zip file)?

**Comment by sniper8952** [comment]
Thank you for your fast response. In this OneDrive Folder you can see the log. I hope it is the right one. If not you can tell it to me. https://optimio-my.sharepoint.com/:f:/p/dominic_johonyak/EkiTm4Hzh5tHnoXIxac-Du8BErpueVz8tEBRjTkHpv40fQ?e=aYg7on

**Comment by narzoul** [comment]
Thanks! The primary surface creation fails in your display driver. Maybe it doesn't support exclusive fullscreen mode on whatever display you're trying to put the game on. Do you have some unusual display setup, like a TV or secondary monitor attached or something? Try if it works on your primary monitor, without any extra devices attached.

**Comment by sniper8952** [comment]
Thanks! I tried to play the game only on the Notebook display. That is working. But if I wan't to play the game on my 32" Predator display with 2K resolution the game is not starting.

The command -w is working but the game is windowed in the left upper corner.

**Comment by narzoul** [comment]
How is your external monitor connected to the desktop? I think something like Duplicate may not work (I never really tried it), but Extend or "Second screen only" should work (Win+P shortcut). Although Extend may also require that your external monitor is set as the primary in Windows display settings.

**Comment by sniper8952** [comment]
I have connected my notebook via a Lenovo dock with USB-C. On this dock is a 24" and the 32" display. The 32" display is the main display. My screens are extended.

**Comment by narzoul** [comment]
Does the game start up in fullscreen mode on your 32" display without DDrawCompat?

**Comment by sniper8952** [comment]
No, it doesn't.

**Comment by narzoul** [comment]
It's probably a driver issue. I guess it can't handle exclusive fullscreen mode through USB-C for whatever reason. I don't think I can do anything about that. But the next release of DDrawCompat will have borderless fullscreen mode by default, which should work fine.

In the meantime, doesn't windowed mode kind of work like fullscreen if you set its compatibility settings to run in 640x480? At least this works for me with some annoyances, e.g. alt-tabbing to desktop or exiting the game doesn't restore the native resolution automatically.

**Comment by sniper8952** [comment]
I have also already updated the Nvidia driver. That didn't help either. When will you release the new version?

**Comment by narzoul** [comment]
Not sure, maybe in the next couple of weeks, depending on how many more issues I find and how long it takes to fix them. I might also just wait for the next Windows 11 update, because according to some reports it will be incompatible with DDrawCompat, so it would need a quick fix too.

Based on your logs, the game is using AMD display drivers, not NVIDIA. Maybe another side effect of using the USB connection? Does it use NVIDIA drivers when the monitor is plugged in directly through HDMI? You can see it in the "Hooking user mode display driver:" line of the log.

**Comment by sniper8952** [comment]
I tried to deaktivate my AMD onboard graficcard. And now if i started the game is shows me only a black screen but i can hear the sound. I tried it also with 640x480 and Windows XP Mod.

**Comment by narzoul** [comment]
v0.4.0 has been released, does it fix the issue?

**Comment by sniper8952** [comment]
With this Version its working! Thank you! Where you from? Magyar?
