### ISSUE TITLE
God of Nea, we still need your help

### ISSUE THREAD

**Issue by FaustGoN** [narzoul/DDrawCompat#143]
Hi narzoul,

I don't know if you remember but you helped me a few years ago for my game God of Nea (an old game that uses DirectX7 and DirectDraw).
You had produced a ddraw.dll adapted to this game, so that players with Windows 10 can play properly with a very low drawing and therefore a fluid game!
We use this ddraw.dll https://mega.nz/file/DspD2aza#jXNlcEfPh6iMAF-V_f0mearMo5zPZxjAqzCWdGagttc (I can't remember what version number is attached to this dll, but we also tried with the latest version available here) .

### The problem:
The player under Windows 10 with multiple screens AND who uses the ddraw.dll, obtains a black screen when he opens the game.
If he removes the dll, the screen is no longer black, but once in game, the drawing is too high (50ms).

_Do you have any idea how to proceed to be able to use the dll + have multiple screens?_

Best Regards,
Faust,
godofnea.com

```
17:12:38.489 Process path: D:\Program Files (x86)\God of Nea\gon.exe
17:12:38.490 Environment variable __COMPAT_LAYER = ""
17:12:38.490 Loading DDrawCompat statically from D:\Program Files (x86)\God of Nea\DDRAW.dll
17:12:38.514 DDrawCompat loaded successfully
17:12:38.584 Installing display mode hooks
17:12:38.591 Installing registry hooks
17:12:38.591 Installing Direct3D driver hooks
17:12:38.591 Installing Win32 hooks
17:12:38.598 Hooking user mode display driver: C:\WINDOWS\System32\DriverStore\FileRepository\u0382658.inf_amd64_03ff8c2b52214376\B382613\aticfx32.dll+0x5dcb0
17:12:38.653 Dynamic vertex buffers are available
17:12:38.653 Dynamic index buffers are available
17:12:38.658 Checking source color key support: failed (test result pattern is incorrect: 0xfa9f)
17:12:38.664 Incorrect z-buffer bit depth capabilities detected; changed from "16, 32" to "16, 24"
17:12:38.668 Installing DirectDraw hooks
17:12:38.669 Installing Direct3D hooks
17:12:38.672 Installing GDI hooks
17:12:38.682 Finished installing hooks
```

**Comment by narzoul** [comment]
Sorry, I don't support online games anymore.
