### ISSUE TITLE
Rex And The Treasure of Pirates doesn't work

### ISSUE THREAD

**Issue by OgnistyPoland** [narzoul/DDrawCompat#144]
Hi, the game is crashing with the newest version of ddraw. It was working with the v0.2.1, but I didn't see my mouse cursor, so I tried new version and it doesn't work at all.

DebugLog
[DDrawCompat-ReksioPiraci.log](https://github.com/narzoul/DDrawCompat/files/9540855/DDrawCompat-ReksioPiraci.log)

NormalLog
```
18:24:00.410 Process path: C:\Program Files\AidemMedia\Reksio Piraci\ReksioPiraci.exe
18:24:00.410 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation WinXPSp2"
18:24:00.410 Loading DDrawCompat statically from C:\Program Files\AidemMedia\Reksio Piraci\DDRAW.dll
18:24:00.423 DDrawCompat loaded successfully
18:24:00.502 Installing display mode hooks
18:24:00.507 Installing registry hooks
18:24:00.508 Installing Direct3D driver hooks
18:24:00.508 Installing Win32 hooks
18:24:00.511 Hooking user mode display driver: C:\Windows\System32\DriverStore\FileRepository\nvlt.inf_amd64_da008533bb297082\nvldumd.dll+0x22560
18:24:00.603 Dynamic vertex buffers are available
18:24:00.603 Dynamic index buffers are available
18:24:00.605 Checking source color key support: passed
18:24:00.607 Installing DirectDraw hooks
18:24:00.607 Installing Direct3D hooks
18:24:00.609 Installing GDI hooks
18:24:00.613 Finished installing hooks
```

**Comment by narzoul** [comment]
Based on the debug logs, I'm guessing you have G-Sync enabled, which is known to crash with DirectDraw fullscreen exclusive mode. Try turning it off.
Does it really not crash with v0.2.1 when G-Sync is enabled? Then it might be an issue with DDrawCompat after all, I always thought it was just an NVIDIA driver bug.

The game works fine for me with either v0.2.1 or v0.3.1, the cursor should be visible either way.

**Comment by narzoul** [comment]
v0.4.0 should fix the G-Sync related crash too as long as the FullscreenMode setting is left on "borderless".

**Comment by OgnistyPoland** [comment]
Thanks, it work like a charm, right now
