### ISSUE TITLE
Tie Fighter 95 no mouse cursor.

### ISSUE THREAD

**Issue by r2rangel** [narzoul/DDrawCompat#145]
Hello There !

I'm trying this on the Steam version (Remastered but is the win95 version), to see if the dreadful 3d hardware bug, that comes with the ddraw version they ship gets solved.
Only problem is, I got no mouse arrow using DDrawCompat. So can't even get to the actual 3d part of the game to test it out. Wondering what I could be doing wrong ? Game got updated recently also, and the ddraw that comes with, cursor works fine out of the fresh install. When in DDrawCompat mouse seems to work fine only in the overlay with shift+f11, but as I exit, back to no cursor.

Is there a config I'm missing out ? I looked for in the wiki page, but no luck
Thx again, great piece of app you got here !

**Comment by narzoul** [comment]
I only have the GOG version, but it has the same issue. There is no cursor with native ddraw or dgVoodoo2 either, so I'm starting to think it's not a DDrawCompat issue. Maybe the default ddraw wrapper hacks in its own cursor somehow.

Anyway, I found a workaround on GOG forums: https://www.gog.com/forum/star_wars_xwing_and_tie_fighter_series/missing_cursor

The launcher is called TIESTART.EXE for me, and it has a Use Software Cursor setting under Advanced Options. You have to start the game through the launcher to make it work.
Alternatively, create a shortcut for TIE95.EXE with the /softwarecursor command line option, and start the game through that one.

**Comment by r2rangel** [comment]
I will tried it out ! worked like a charm ! Pretty much just added /softwarecursor into launch options on the proprieties menu ! Thx for the info ! and the great app !
