### ISSUE TITLE
0.4 config settings

### ISSUE THREAD

**Issue by Volcanotron** [narzoul/DDrawCompat#146]
with this new update to ddrawcompat the new config settings don't seem to be load correctly for Rogue Spear you mention it should be loading from %localappdata or programdata% but after some looking around for RS it dumps its files into another location and says it cant load its settings. 
C:\Users\NAME\AppData\Local\VirtualStore\Program Files (x86)\Red Storm Entertainment\Rogue Spear

i did try to manually make those locations but it didn't seem to do anything still

we try to make all folks who play r6/rs to install it to the C: drive so it should be dumping those files into 
C:\Program Files (x86)\Red Storm Entertainment\Rogue Spear

registry location 
Computer\HKEY_USERS\S-1-5-21-221065903-726844514-363796904-1001\Software\Classes\VirtualStore\MACHINE\SOFTWARE\WOW6432Node\Red Storm Entertainment\Rogue Spear

i can use the overlay ingame which is very cool and great job for making that a thing. 
[DDrawCompat-RogueSpear.log](https://github.com/narzoul/DDrawCompat/files/9660633/DDrawCompat-RogueSpear.log)

![Screenshot 2022-09-28 114419](https://user-images.githubusercontent.com/37210517/192668503-dd605810-4c74-4db6-af0c-dcc00b657dea.jpg)
![Screenshot 2022-09-28 114435](https://user-images.githubusercontent.com/37210517/192668514-0cbc3438-175d-43fe-a633-751faac70eb7.jpg)

**Comment by LPDaVinci** [comment]
would be cool if you add to the zip file a default configuration

**Comment by narzoul** [comment]
I didn't want to add any more files to the release, but now you can get it from the Tools directory in the source code:
https://github.com/narzoul/DDrawCompat/blob/master/Tools/DDrawCompat.ini
