### ISSUE TITLE
Crash on Startup (Windows 7)

### ISSUE THREAD

**Issue by MiraakThuri** [narzoul/DDrawCompat#149]
Hey, so i just updated from 0.31 (the W7 special version) to 0.4
And now all my games wich were working fine before crash on startup
(AOE1, AVP2, RealMyst)

Tried without custom settings and with custom settings, same result 
(i tried to change DisplayResolution=app
DpiAwareness=app
FullscreenMode=exclusive)

[DDrawCompat-lithtech.log](https://github.com/narzoul/DDrawCompat/files/9710181/DDrawCompat-lithtech.log)
here is the log file from avp2, dunno if it might help u

**Comment by narzoul** [comment]
Please change the LogLevel setting to debug and upload the log with that. Thanks!

**Comment by MiraakThuri** [comment]
[DDrawCompat-lithtech.log](https://github.com/narzoul/DDrawCompat/files/9711486/DDrawCompat-lithtech.log)
Here it is with debug mode

**Comment by narzoul** [comment]
Ok, I think I found the culprit. Please try this test version:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/9717782/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/9717785/diff.txt) compared to v0.4.0)

**Comment by MiraakThuri** [comment]
Ok, so RealMyst is working now but AOE1 and AVP2 are still crashing, but not at the same time
before it would crash instantly, now the screen turn black 1 sec, like the game would start normally, then it crash
[DDrawCompat-lithtech.log](https://github.com/narzoul/DDrawCompat/files/9725808/DDrawCompat-lithtech.log)

**Comment by narzoul** [comment]
Hmm, it seems to crash in SetCursor, but I'm not sure what could crash there. Could you please collect a crash dump also? I have some instructions here: https://github.com/narzoul/DDrawCompat/issues/50#issuecomment-520162844
Please also attach the new debug logs again with the crash dump.

**Comment by MiraakThuri** [comment]
Here you go
[lithtech.exe.7128.dmp.zip](https://github.com/narzoul/DDrawCompat/files/9729111/lithtech.exe.7128.dmp.zip)
[DDrawCompat-lithtech.log](https://github.com/narzoul/DDrawCompat/files/9729112/DDrawCompat-lithtech.log)

**Comment by narzoul** [comment]
Thanks! Unfortunately, the crash dump seems to get created after the original exception, so I still don't see what exactly is causing it. But at least I noticed an extra dinput.dll in your game directory. Where is that from? It might be installing some hooks that interferes with DDrawCompat. Can you try running the game without it?

**Comment by MiraakThuri** [comment]
It's a wrapper to convert dinput to dinput8 (that game has some mouse issues) but i still get the crash without it
And AOE1 don't have any additional wrappers, ill send you the log and dump from that game this time, maybe it will give better infos
[DDrawCompat-Empires.log](https://github.com/narzoul/DDrawCompat/files/9734894/DDrawCompat-Empires.log)
[Empires.exe.6056.dmp.zip](https://github.com/narzoul/DDrawCompat/files/9734895/Empires.exe.6056.dmp.zip)

**Comment by narzoul** [comment]
It looks the same. I found the issue anyway. The GetCursor function has an early call instruction with relative addressing on Windows 7, which wasn't patched up when moving it to the trampoline during hooking. This should fix it:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/9736501/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/9736503/diff.txt) compared to v0.4.0)

**Comment by MiraakThuri** [comment]
Yes it working just fine now
Thx for your time on this

**Comment by narzoul** [comment]
Great, thanks for the reports! I'll add the fixes to the next release.

**Comment by narzoul** [comment]
Win 7 startup crashes have been fixed in v0.5.0.
