### ISSUE TITLE
Feature request: Deframer

### ISSUE THREAD

**Issue by ZellSF** [narzoul/DDrawCompat#151]
Some games have problems with artifacting on screen borders when antialiasing or resolution is forced. Is it possible to implement a setting to render the outmost X pixels as just black? As of now I've noted this is a problem in:

Arcturus: The Curse and Loss of Divinity
Etherlords
Nerf Arena Blast
Plane Crazy

But I assume there's many more. Especially since Nerf Arena Blast is a Unreal engine game, so I'm guessing other Unreal engine games share this problem.

**Comment by narzoul** [comment]
I haven't tested any of those games yet, but I've seen a few with a 1-pixel border issue. As I recall, all of them were fixable by the AlternatePixelCenter option though. Isn't that the case here?

**Comment by ZellSF** [comment]
You're right, I didn't think to test that setting for this issue.

**Comment by narzoul** [comment]
Well, I thought "horizontal or vertical lines" included the screen edges, but I added a small clarification to the wiki to specifically mention the screen edges anyway.
