### ISSUE TITLE
Not work on the DirectX7 games. Could you help me.

### ISSUE THREAD

**Issue by dzdhome** [narzoul/DDrawCompat#153]
I have a funny tank game. It run well in the Win XP,  Which was programed Base on the DirectX7. 
With the ddraw.dll which you provide, It can be run in the Win10 well. But it not work in the Win11.
Could you have a look.
Below link is the game.
[https://wws.lanzouy.com/iOMiQ0dntqvi](url)

**Comment by narzoul** [comment]
I have Windows 11 and the game works just fine in both windowed and fullscreen mode. What does "not work" mean in your case? Does it not start? Does it crash? Is there some graphics issue?

Please enable the LogLevel=debug setting and attach the debug logs (DDrawCompat-Tank.log).

**Comment by dzdhome** [comment]
Thank you for your reply.
below link is the video when I open the game.
https://youtu.be/SSPi5lFlf9E

Logs from  DDrawCompat-Tank.log
15:32:30.036 Process path: D:\D\Games\Tank\Tank.exe
15:32:30.036 Loading DDrawCompat dynamically from D:\D\Games\Tank\DDraw.dll
15:32:30.036 Environment variable __COMPAT_LAYER = ""
15:32:30.036 Loading global config file: C:\ProgramData\DDrawCompat\DDrawCompat.ini
15:32:30.036   File not found, skipping
15:32:30.036 Loading user config file: C:\Users\Conra\AppData\Local\DDrawCompat\DDrawCompat.ini
15:32:30.036   File not found, skipping
15:32:30.036 Loading directory config file: D:\D\Games\Tank\DDrawCompat.ini
15:32:30.036   File not found, skipping
15:32:30.036 Loading process config file: D:\D\Games\Tank\DDrawCompat-Tank.ini
15:32:30.036   File not found, skipping
15:32:30.036 Loading overlay config file: D:\D\Games\Tank\DDrawCompatOverlay-Tank.ini
15:32:30.036   File not found, skipping
15:32:30.036 Final configuration:
15:32:30.036   [default] AlignSysMemSurfaces   = on
15:32:30.036   [default] AltTabFix             = off
15:32:30.036   [default] AlternatePixelCenter  = off
15:32:30.036   [default] Antialiasing          = off
15:32:30.036   [default] BltFilter             = point
15:32:30.036   [default] ConfigHotKey          = shift+f11
15:32:30.036   [default] CpuAffinity           = 1
15:32:30.036   [default] DesktopColorDepth     = initial
15:32:30.036   [default] DisplayFilter         = bilinear(0)
15:32:30.036   [default] DisplayRefreshRate    = app
15:32:30.036   [default] DisplayResolution     = desktop
15:32:30.036   [default] DpiAwareness          = permonitor
15:32:30.036   [default] FontAntialiasing      = app
15:32:30.036   [default] ForceD3D9On12         = off
15:32:30.036   [default] FpsLimiter            = off
15:32:30.036   [default] FullscreenMode        = borderless
15:32:30.036   [default] LogLevel              = info
15:32:30.036   [default] PalettizedTextures    = on
15:32:30.036   [default] RemoveBorders         = off
15:32:30.036   [default] RenderColorDepth      = app
15:32:30.036   [default] ResolutionScale       = app(1)
15:32:30.036   [default] ResolutionScaleFilter = point
15:32:30.036   [default] SoftwareDevice        = rgb
15:32:30.036   [default] SpriteDetection       = off
15:32:30.036   [default] SpriteFilter          = app
15:32:30.036   [default] SpriteTexCoord        = app
15:32:30.036   [default] SupportedResolutions  = native, 640x480, 800x600, 1024x768
15:32:30.036   [default] TextureFilter         = app
15:32:30.036   [default] ThreadPriorityBoost   = off
15:32:30.036   [default] VSync                 = app
15:32:30.036   [default] WinVersionLie         = off
15:32:30.063 DPI awareness was successfully changed to "permonitor" via SetProcessDpiAwarenessContext
15:32:30.063 DDrawCompat loaded successfully
15:32:30.063 Installing display mode hooks
15:32:30.068 Installing registry hooks
15:32:30.068 Installing Direct3D driver hooks
15:32:30.074 Hooking user mode display driver: C:\Windows\SYSTEM32\D3D9on12.dll+0x10b10
15:32:30.180 Dynamic vertex buffers are available
15:32:30.180 Dynamic index buffers are available
15:32:30.180 Supported z-buffer bit depths: 16
15:32:30.180 Supported MSAA modes: msaa(2), msaa2x(0), msaa4x(0), msaa8x(0)
15:32:30.181 Supported resource formats:
15:32:30.181   {D3DDDIFMT_A8R8G8B8,0xdae09f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_X8R8G8B8,0xdaec9f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_R5G6B5,0xca6c9f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_X1R5G5B5,0xca609f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_A1R5G5B5,0xca609f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_A4R4G4B4,0xc2409f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_A8,0xc2409f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_X4R4G4B4,0xc2409f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_A2B10G10R10,0xca609f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_A8B8G8R8,0xdae09f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_G16R16,0xc2409f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_A2R10G10B10,0x8a609f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_A16B16G16R16,0xca609f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_L8,0xc2409f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_A8L8,0xc2409f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_V8U8,0xc30007,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_Q8W8V8U8,0xc30007,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_V16U16,0xc30007,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_D24S8,0x8200c5,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_D24X8,0x8200c5,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_D16,0x8200c7,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_L16,0xc2409f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_D24FS8,0x8200c5,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_Q16W16V16U16,0xc30007,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_R16F,0xc2409f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_G16R16F,0xe2409f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_A16B16G16R16F,0xca609f,0x8b,0x8b,0}
15:32:30.181   {D3DDDIFMT_R32F,0xe2409f,0x0,0x0,0}
15:32:30.181   {D3DDDIFMT_G32R32F,0xe2409f,0x0,0x0,0}
15:32:30.181   {D3DDDIFMT_A32B32G32R32F,0xe2409f,0x0,0x0,0}
15:32:30.181   {FOURCC(P010),0x7000,0x0,0x0,32}
15:32:30.181   {FOURCC(ATI1),0x829007,0x0,0x0,8}
15:32:30.181   {FOURCC(DXT1),0x828007,0x0,0x0,0}
15:32:30.181   {FOURCC(NV12),0x7000,0x0,0x0,16}
15:32:30.181   {FOURCC(YV12),0x7000,0x0,0x0,16}
15:32:30.181   {FOURCC(ATI2),0x829007,0x0,0x0,8}
15:32:30.181   {FOURCC(DXT2),0x828007,0x0,0x0,0}
15:32:30.181   {FOURCC(YUY2),0x7000,0x0,0x0,16}
15:32:30.181   {FOURCC(DXT3),0x828007,0x0,0x0,0}
15:32:30.181   {FOURCC(DF24),0x8200c5,0x8b,0x8b,0}
15:32:30.181   {FOURCC(DXT4),0x828007,0x0,0x0,0}
15:32:30.181   {FOURCC(DXT5),0x828007,0x0,0x0,0}
15:32:30.181   {FOURCC(DF16),0x8200c7,0x8b,0x8b,0}
15:32:30.181   {FOURCC(ATOC),0x4000,0x0,0x0,0}
15:32:30.181   {FOURCC(NULL),0x83401f,0x8b,0x8b,0}
15:32:30.181   {FOURCC(AYUV),0x407000,0x0,0x0,32}
15:32:30.181   {FOURCC(RESZ),0x0,0x0,0x0,0}
15:32:30.181   {FOURCC(INTZ),0x8200c5,0x8b,0x8b,0}
15:32:30.183 Installing DirectDraw hooks
15:32:30.185 Installing Direct3D hooks
15:32:30.188 Installing GDI hooks
15:32:30.195 Finished installing hooks
15:33:36.562 DDrawCompat detached successfully

**Comment by dzdhome** [comment]
My PC information:
 Operating System: Windows 11 家庭中文版 64-bit (10.0, Build 22000) (22000.co_release.210604-1628)
Language: Chinese (Simplified) (Regional Setting: Chinese (Simplified))
System Manufacturer: LENOVO
 Processor: 12th Gen Intel(R) Core(TM) i7-12700H (20 CPUs), ~2.3GHz
Memory: 32768MB RAM
DirectX Version: DirectX 12
Internal GPU: Intel(R) Iris(R) Xe Graphics
GPU2: NVIDIA T1200 Laptop GPU

**Comment by dzdhome** [comment]
DebugLevel log

[DDrawCompat-Tank.zip](https://github.com/narzoul/DDrawCompat/files/9763183/DDrawCompat-Tank.zip)

**Comment by narzoul** [comment]
Ok, thanks! I can reproduce the issue now by enabling the ForceD3D9On12 setting. On your system, I suppose it's enabled by default because your Intel driver doesn't have native Direct3D 9 support. See here:
https://www.intel.com/content/www/us/en/support/articles/000091239/graphics.html

Even though you also have an NVIDIA GPU, as far as I know there is no way to use that for Direct3D 8 and older APIs. See here:
https://nvidia.custhelp.com/app/answers/detail/a_id/3733/~/games-based-on-directx-8-and-older-versions-of-directx-will-only-run-on

Unfortunately, D3D9On12 doesn't work well with this game even without DDrawCompat, so the issue is at least partially on that side, although the artifacts are different than with DDrawCompat. I'll try to improve compatibility with D3D9On12 in the future, but I'm not sure when I'll be able to get to it.

**Comment by dzdhome** [comment]
Thank you for your checked. It's seems really difficult. I have the patience to wait.  wish you success. Thanks again.

**Comment by narzoul** [comment]
Let's keep this open until I can fix it, so that I don't forget about it.

**Comment by narzoul** [comment]
This particular game seems to work well now in v0.5.0.

**Comment by dzdhome** [comment]
Yes. It's work. Thank you very much.
