### ISSUE TITLE
how to scale image to fullscreen?

### ISSUE THREAD

**Issue by ghost** [narzoul/DDrawCompat#157]
been looking at the configuration page but not understanding how to use the settings settings, is it possible to scale a games image to fit the screen without the black bars? only one setting mentioned aspect ratio but after putting that in the ini file i still get black bars on the game i'm trying.

is DisplayFilter not the right setting? i also put in DisplayResolution = 1920x1080

**Comment by narzoul** [comment]
DisplayFilter only changes the filter, not the aspect ratio. Like the wiki says, pixel aspect ratio is always kept at 1:1 to avoid stretching the screen unevenly. Is that really what you want? I could add a setting for it.
If you use DisplayResolution=app, your monitor or GPU will do the scaling, which might already support such an option. Look for GPU scaling in your graphics control panel.

**Comment by Crugnok** [comment]
ah i see. what i'd really like is an option to stretch to fit the screen. i tried it with "app" which makes it fullscreen with no bars, but it crops off the edges of the screen image. if you could add a stretch to fit setting that would great :)

**Comment by Crugnok** [comment]
for games like rainbow six and rogue spear all the menus are 4:3, with dgvoodoo i can change the scaling to stretched so it fits the entire screen, the downside of that wrapper is everytime i load a map it minimizes the game and i have to click in the tray to get i back.

also there are some minor graphics glitches.

game runs fine and looks great on your wrapper though, just wish it had a fullscreen stretch setting.

**Comment by narzoul** [comment]
Added a [DisplayAspectRatio](https://github.com/narzoul/DDrawCompat/wiki/Configuration#displayaspectratio) setting in v0.5.0.
