### ISSUE TITLE
Can this ifle help solve input delay on steam games like halo mcc ?

### ISSUE THREAD

**Issue by itakeudown97** [narzoul/DDrawCompat#168]
Hi, halo is an old game and was just recently remastered for pc on steam but in has incredibly high input delay and I wonder if it can fix that

**Comment by narzoul** [comment]
No, Halo uses DirectX 9, this project is only for DirectX 7 and older. You can usually find info about the used DirectX version on mobygames: https://www.mobygames.com/game/halo-combat-evolved/techinfo
Or you can use a tool like process explorer to check what DLLs are loaded. If ddraw.dll is not among them, then DDrawCompat won't help.
