### ISSUE TITLE
Microsoft Golf 1998/1999 Image freezing

### ISSUE THREAD

**Issue by CarstenK1991** [narzoul/DDrawCompat#17]
First of all, thanks for you amazing work!

I tried the wrapper with great success on one of my favourite old games, MS Golf 1999, which was unplayable otherwise. (Windows 10)

The game runs perfectly smooth with the newest experimental release, however the image freezes after ca. 30 seconds. The game itself keeps on running (Audio still playing, buttons still function etc) but the image doesn't. 
I found out that it starts working again if you switch to the desktop and then back to the game, but only for like 30 seconds, then it freezes again. Same problem with the v0.2.1 release. 

The game works with the v0.2.0 release, altho not as smoothly as with v.0.2.1 and escpecially the experiemental one.

Would be greatly appreciated if you could take a look at what might be causing the freezing :)

**Comment by narzoul** [comment]
Do you use Intel HD graphics? I've seen a similar issue with Dungeon Keeper 2 but only when using Intel HD, not with my dedicated GPUs. I think it was also broken by a commit between v0.2.0 and v0.2.1. I've tracked it down before, but I didn't understand how that change could cause such behavior. I'll take another look when I can.

**Comment by CarstenK1991** [comment]
Yes, I'm using Intel HD Graphics (on my Laptop). Thanks a lot, that'd be awesome! :)

**Comment by narzoul** [comment]
I couldn't get MS Golf 1999 working yet, but I still have the issue with DK2 using v0.2.1, so I used that for testing.
However it seems that my latest local commits have fixed the issue already somehow, so I pushed those changes now and updated the experimental release. Please check if it fixes the issue for you too.

**Comment by CarstenK1991** [comment]
It works!! Thanks so much for fixing this!

**Comment by narzoul** [comment]
Thanks for the feedback! I'll close this issue then.
