### ISSUE TITLE
Nascar Road Racing

### ISSUE THREAD

**Issue by ghotik** [narzoul/DDrawCompat#171]
This old game shows a very peculiar effect that appears both using DxWnd or using DDrawCompact.
When the 3D part of the race starts, the camera seems to be positioned below the road level with crazy effects of transparencies and invisible scenery.
That could easily accounted by a game bug, but the fact is that dropping the dgVoodoo2 dlls on the game folder everything works perfectly!
Have a look:
![nrr1](https://user-images.githubusercontent.com/26228875/207636653-5452c963-2a92-4681-acbd-1acaf30f95cc.png)
![nrr2](https://user-images.githubusercontent.com/26228875/207636663-d95abb1c-a3f7-48f2-8ea2-f009a5eb9c2a.png)

**Comment by narzoul** [comment]
I get the same results with dgVoodoo2.

How did you get past the initial crash? The game creates a second primary surface while the first one is still alive, and that causes a crash for me. Multiple simultaneous primary surfaces were never supported by DDrawCompat. I worked around it by suppressing the creation of the second primary, which gets me to the race.

After that, I just see the same issue as with dgVoodoo2: game looks fine at first, until the camera goes under the map and then it looks like on your screenshot. Did you use some special dgVoodoo settings to get it working?

**Comment by ghotik** [comment]
All my tests were done with DxWnd control (I didn't want to use compatibility modes to run the game on a 32bit desktop) so probably it was DxWnd taking care of the multiple primary open, since in emulation mode it opens a single real primary surface and returns to the application a virtual primary surface mapped on a offscreen memory surface. 
I now notice that the game also tries to use overlays, so I'll make more tests because I'm adding to DxWnd a sort of overlay emulation (as you already read in my Godfather posts).
The game also seems to use multiple windows or something like that, because when the race starts I see only a black frame, but minimizing and restoring the window resumes the 3D scene.
But, finally, this was another oddity: the 3D scene starts with a "below-ground-level point of view" both with and without DDC, but curiously this doesn't happen when dropping in the game folder the ddraw.dll file from dgVoodoo2.
To answer your question, I used just the ddraw.dll file from dgVoodoo2.63.1, no configuration added.
Since the minimize-restore action is necessary also with DgVoodoo2, I couldn't tell if dgVoodoo2 fixes the initial "below-ground-level" phase by fixing some fow parameter or if it simply quickly skips all bogus frames, anyway I thought it may interest you. I'll do more accurate tests.

**Comment by BEENNath58** [comment]
The camera issue looked like the physics issue found in modern day games due to excessive FPS. IIRC, the game has a frame rate setting inside the settings, which probably maxes out at 30. I fixed the "camera going under the map" issue by limiting the FPS to 30.
