### ISSUE TITLE
more about D3DDDI hacking and Jimmy Neutron 

### ISSUE THREAD

**Issue by ghotik** [narzoul/DDrawCompat#172]
Please, ignore this message. I think I understood what's going on (at least, in part ...). The reason in the next post.

I stumbled on a strange situation where perhaps you may help me (in the hope that there could be a possible payback and find something that could help you improve DDrawCompat as well).
Related to my attempts to fix Godfather, I used an experimental dxwnd.dll version that with my surprise was useless for its target, but fixed perfectly "Jimmy Neutron Boy Genius" the version with HW rendering.
I'll have to show some pieces of code to explain myself, but I'll attach the full c++ file in the end.
The fix was using this switch in the pfnCreateDevice D3DDDI callback:
```

	if(dxw.dwDFlags2 & EXPERIMENTAL4){
		if(args->pDeviceFuncs->pfnPresent != extPresent){
			OutTrace("%s: pfnPresent hooked\n", ApiRef);
			pfnPresent = args->pDeviceFuncs->pfnPresent;
			args->pDeviceFuncs->pfnPresent = extPresent;
		}
	}

```
Believe it or not, it works: if I enable the EXPERIMENTAL4 flag I get the traces in the log proving that the program went through here. After the logging I save  args->pDeviceFuncs->pfnPresent and redirect the call to extPresent.
This is the extPresent wrapper:

```
HRESULT WINAPI extPresent(HANDLE hDevice, const LPGENERIC(D3DDDIARG_PRESENT *)unnamedParam2)
{
	ApiName("pfnPresent");
	OutTrace("%s: hdevice=%#x\n", ApiRef, hDevice);
	uPresentKount++;
	return (*pfnPresent)(hDevice, unnamedParam2);
}

```
the wrapper does nothing special: it traces the event and call the original pfnPresent.
All this could perfectly be bugged, I know, but the very strange thing is that two scenarios happen:
1) with EXPERIMENTAL4 turned off, the game runs with the usual problems (some missing textures and other oddities)
2) with EXPERIMENTAL4 turned on, the game renders perfectly, though I see no logs for the pfnPresent invocation and the wrapper itself does quite nothing.

I don't really know how to explain all this.
[d3dumddi.zip](https://github.com/narzoul/DDrawCompat/files/10238646/d3dumddi.zip)

**Comment by ghotik** [comment]
The reason why I didn't get PfnPresent invocations in the log is because to make the game work we had to force HEL mode, so the first log messages were originated while the game was trying to get support from some HAL mode and, in the end, since no mode was available, it turned to GDI completely bypassing all the DirectX stack. 
I still don't understand why the D3DDDI hoking attempts fixed some GDI handling, but at least half of the story is clear.

**Comment by BEENNath58** [comment]
> The reason why I didn't get PfnPresent invocations in the log is because to make the game work we had to force HEL mode, 

If you are talking about the "render using RGB/Ramp/MMX" part, I am not sure if they belong to HEL. What I know (or know incorrectly) that HEL is just software based HAL. While RGB/Ramp/MMX are itself software devices. I thought I should add it so that there's no misunderstanding.

**Comment by ghotik** [comment]
issue closed without using D3DDDI hooking.
Thank you anyway, laying down the questions helped to focus and open our minds.
