### ISSUE TITLE
rdsh fullscreen support ?

### ISSUE THREAD

**Issue by rynetang** [narzoul/DDrawCompat#173]
As we all known, remote desktop to windows via rdsh does not support directdraw, all games launch at full screen mode will get error, can we use DDrawcompact to fix this problem?

![image](https://github.com/rynetang/imgstore/raw/main/screenshot-20221221-182942.png)

**Comment by narzoul** [comment]
I don't think so, at least it's not intended for that. I have no idea how remote desktop works though.
Also, your screenshot is showing DirectX 11, which has nothing to do with DirectDraw. DirectDraw is DirectX 7 or older, mostly used by games released around 1997-2000.
