### ISSUE TITLE
Not working in newer Windows 11 Insider Preview builds.

### ISSUE THREAD

**Issue by jbara2002** [narzoul/DDrawCompat#181]
I have some problems with DDrawCompat in Windows 11 Insider Builds (22567.rs_prelease).
So, it gets again deadlock (app is running, and nothing is not showing in the screen)
Another thing, before deadlock problems, some games it does not get in full screen.

**Comment by narzoul** [comment]
As the readme says, Insider builds are not supported. I can only debug it if/when the breaking change makes it to release builds.
