### ISSUE TITLE
how can i make games run a bit slower?

### ISSUE THREAD

**Issue by Buechnerstod** [narzoul/DDrawCompat#184]
I was just trying DDraw compat with the old buka game "Napoleon's Battles" and it just runs a little too fast - i notice there are options to tweak ddrawcompat in the options log. -thats just the log though, how do i actively use such options?

i notice the FPS limiter is off, if i could put it on, it might fix the speed issue

**Comment by narzoul** [comment]
Read the [Configuration wiki](https://github.com/narzoul/DDrawCompat/wiki/Configuration).
