### ISSUE TITLE
Low fps in the game

### ISSUE THREAD

**Issue by Nikqz** [narzoul/DDrawCompat#189]
hello
there is such a rather old game Space Empires 5, it is still sometimes interesting to launch and play it, but surprisingly, the more modern equipment and computer, the slower it works. When you start the game in Direct3D HAL mode at a high resolution of 1920x1080 and open several windows inside the game, where there are a lot of small images and text, the game fps drops to 20 frames per second on a modern 6800 XT video card and a Windows 10/11 x64 system, when there are fewer windows and text, then the number of frames per second is somewhere around 40-80
Such indicators can be achieved using your library and with certain settings that slightly add AlignSysMemSurfaces and ForceD3D9On12 frames to the enabled mode, DesktopColorDepth and RenderColorDepth to the 16-bit mode with anti-aliasing turned off. Without your library, the performance is even worse
I tried all the other settings both in your library and in the game itself, but I did not achieve the best result.
I remember that a few years ago, when I had Haswell and then Ivy processors, then on the integrated graphics of these processors and on the first Intel drivers for them (IntelGraphics_win64_15.33.37.4242) and (IntelGraphics_win64_15.33.46.4885), I was able to raise fps is noticeably higher, but as soon as I installed the latest driver, the fps values sagged a lot, now I have a Kabi-Lake processor, but I didn’t find good drivers
Maybe you can suggest something or see this application

**Comment by Nikqz** [comment]
after I wrote this post, I began to look for other possible sets of libraries on the resource and successfully!
this library helped with this resource
https://github.com/elishacloud/dxwrapper/wiki/Configuration#ddrawcompat
when enabled setting DDrawCompat = 1
the frame rate no longer drops critically in scenes with a lot of pictures and text, even at 32-bit color depth and on the built-in processor driver with a UHD 630 video card

**Comment by Nikqz** [comment]
I noticed that with your library version 0.3.2 / 0.3.1 the game also works quickly, but with version 0.4.0 it slows down

**Comment by narzoul** [comment]
Please upload your DDrawCompat log file for v0.4.0. Does ForceD3D9On12 really increase performance, or why did you enable it? I've only seen it decrease performance and possibly cause graphical issues and crashes with anything I tried. But I haven't had a "proper" Intel GPU (i.e. one that isn't using D3D9On12) in a long time, so I can't try it with one.

**Comment by Nikqz** [comment]
ForceD3D9On12 slightly raised the frame rate on the 6800XT video card, but the UHD 630 video card, on the contrary, was worse
[v0.3.2+DDrawCompat-se5.log](https://github.com/narzoul/DDrawCompat/files/10419102/v0.3.2%2BDDrawCompat-se5.log)
[v0.4.0_DDrawCompat-se5.log](https://github.com/narzoul/DDrawCompat/files/10419103/v0.4.0_DDrawCompat-se5.log)

**Comment by Nikqz** [comment]
> Please upload your DDrawCompat log file for v0.4.0. Does ForceD3D9On12 really increase performance, or why did you enable it? I've only seen it decrease performance and possibly cause graphical issues and crashes with anything I tried. But I haven't had a "proper" Intel GPU (i.e. one that isn't using D3D9On12) in a long time, so I can't try it with one.

Hi
did you see something in the logs, why does the hal connect on version 0.4.0 and the game slows down, but on version 0.3.2 it goes fast?

**Comment by narzoul** [comment]
Could you try the test version in this comment?
https://github.com/narzoul/DDrawCompat/issues/147#issuecomment-1268756660
