### ISSUE TITLE
Can this dll support Chinese Characters Input tool?

### ISSUE THREAD

**Issue by godking232** [narzoul/DDrawCompat#191]
Hi bro ,Can this dll support Chinese Characters Input tool?
Now the problem is in the Game win i input Characters it dosen't appear the Characters Option that I can choose which on is the correct words i input。appreciate

**Comment by narzoul** [comment]
I'm not sure what you mean. I don't have a Chinese keyboard so this may be difficult to reproduce for me. Could you send a screenshot of what the expected result is supposed to look like, and what it looks like with DDrawCompat instead?
