### ISSUE TITLE
cannot find input file detours.lib

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#192]
I am trying to compile a 3 year old version of DDrawCompat (I am searching for the build DDrawCompat fixed D3D Ramp). After copying the detours.h file to the Include folder of Windows Kits, I removed one problem, but now VC wants detours.lib

Where do I get the file?

**Comment by BEENNath58** [comment]
I will try to build Detours, thanks.

Previously testing I was copying both ddraw.dll and d3dim.dll and it wasn't working; but now removing ddraw.dll the game works fine.

I am not sure if Ramp was removed, because most applications still run using Ramp without the old d3dim.dll file. Some apps such as Shadows of the Empire fail on Ramp (I am yet to test old d3dim.dll here). At least the ones using Direct3D Retained Mode (check dx6 and dx7 sdk) through Ramp device work natively.

Apps on Ramp look almost the same texture-wise, such as:
![twist3d](https://user-images.githubusercontent.com/64649734/212724352-bd937281-fd9c-4204-9334-af8cc4ec352d.png)

**Comment by narzoul** [comment]
Yes, that's exactly what broken Ramp looks like. Here's what it should look like (taken from an XP VM):
![twist](https://user-images.githubusercontent.com/16432233/212730423-2c0cd7c9-ca57-4ff5-8dd9-058156dfac00.jpg)

Yes, the apps still "work", if you can call it that. But I haven't seen any that render correctly. If you find one, let me know.

Just compare the debug symbols (function names) e.g. with IDA and you'll see what I mean. All the `Ramp_TexRead_*` functions have been removed. Only a handful of the `_Ramp_Spans_*` functions are left, and those aren't even referenced anymore, etc. It looks pretty gutted to me, and I doubt it's left in a functional/recoverable state. Perhaps only the texturing part is removed, but that's more than enough...

**Comment by BEENNath58** [comment]
Ok I managed to find an IDA Pro only to check this one. There is a significant difference in the list of functions between the two files. I doubt they will ever come back, so I should just keep on using the old file, until the day it stops working (maybe by then DDrawComppor dgVoodoo2 will be mature enough?)
