### ISSUE TITLE
Bitmap Brothers Z95 / Z Expansion XP now working but with menu flickering

### ISSUE THREAD

**Issue by d3vilsadvocate** [narzoul/DDrawCompat#196]
Thanks to DDrawCompat the old game Z95 / Z Expansion XP now works on Windows now works on WIndows 11.

All that is needed is Antares' installer, WinZMod and this ddraw file. WinZMod.exe then runs just fine. 

However, the main menu is flickering like crazy while the main game is running totally fine. Any idea as to why that would be? I have to click my way through the menu using keyboard commands but at least it works...

I went through all the settings that can be changed according to the Wiki but it won't change anything.

Any help appreciated.

**Comment by narzoul** [comment]
Someone must have thought that changing the display mode every time a WM_PAINT event is received must be a good idea.

It seems like it would take a lot of effort to "properly" fix this on DDrawCompat side, for now I just made a quick workaround:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10551187/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10551188/diff.txt) compared to v0.4.0)

It works fine other than some minor glitches in the main menu, e.g. the background image takes a while to load. But at least there's no more flickering.

**Comment by d3vilsadvocate** [comment]
How wow you're a genius. Thanks, the game is almost flawless now.
  
I'll put up a guide on GOG/Steam/VOGONS, a few abandonware websites soon.

**Comment by narzoul** [comment]
Fixed in v0.5.2.
