### ISSUE TITLE
Starcraft briefings black screen

### ISSUE THREAD

**Issue by uzernaem** [narzoul/DDrawCompat#206]
Starcraft version 1.16.1
DDrawCompat version 0.4.0, default settings.
Briefings screens before the missions are not visible - black screen appears instead. Everything else seems to be fine. It is possible to press enter on the black screen and the mission starts normally.

**Comment by narzoul** [comment]
It seems that smackw32.dll creates and realizes an empty palette when the briefing begins, which is currently unintentionally applied to the hardware palette also. In DirectDraw exclusive fullscreen mode, RealizePalette is not supposed to affect the hardware palette. I'll fix it in the next release, meanwhile here is a temp fix for it:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10831386/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10831387/diff.txt) compared to v0.4.0)

**Comment by narzoul** [comment]
Fixed in v0.5.0.
