### ISSUE TITLE
Interpolation behavior/issue (look at closed issue #104)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [narzoul/DDrawCompat#208]
Hello Narzoul!
I have a question about my past topic: https://github.com/narzoul/DDrawCompat/issues/104

DDraw compat (release version 0.4.0) has much more blurry and worse interpolation 
compared to dll (27-june-2021) you compiled for me for testing:
https://github.com/narzoul/DDrawCompat/issues/104#issuecomment-869168178

Interpolation comparsion. Emulators output image must look like left picture:

![ddraw_compat_x](https://user-images.githubusercontent.com/13199529/220204868-93dc51a8-dcf1-4669-92a8-e9d5f806b86a.png)

Is there a setting for going back to the old interpolation method?

**Comment by narzoul** [comment]
It looks like the right side uses sRGB gamma-corrected filtering. It was only meant to be used by the display scaling filters, but I think it can accidentally get enabled for some blits too.

Does this quick fix solve it?
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/10798637/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/10798639/diff.txt) compared to v0.4.0)

Note: this also disables gamma correction for the display scaling filters (not relevant for windowed mode).

**Comment by eugene-s-nesdev** [comment]
Yes, this fix solved the issue

**Comment by narzoul** [comment]
Fixed in v0.5.0.
