### ISSUE TITLE
Mouse cursor turns to black sold square after a few minutes playing B17 The Mighty Eighth

### ISSUE THREAD

**Issue by theersink** [narzoul/DDrawCompat#209]
After a few minutes of playing the pointer changes to a solid black box. Unfortunately I couldn't get a screenshot as alt tab crashes the game.

Win 11, RX6800xt, Ryzen 5 3600, 32gigs ram

Not really game breaking just annoying. Log attached:

[DDrawCompat-B17Setup.log](https://github.com/narzoul/DDrawCompat/files/10811047/DDrawCompat-B17Setup.log)
[DDrawCompat-Start.log](https://github.com/narzoul/DDrawCompat/files/10811050/DDrawCompat-Start.log)

**Comment by narzoul** [comment]
There is a temporary fix for it here: https://github.com/narzoul/DDrawCompat/issues/148#issuecomment-1362097968

Closing this as a duplicate.
