### ISSUE TITLE
Fury3 Support?

### ISSUE THREAD

**Issue by OpenRift412** [narzoul/DDrawCompat#211]
Would it be possible to implement support for Fury3? As of right now, DDrawCompat doesn't seem to recognize the game at all.

**Comment by narzoul** [comment]
Generally, you can check if a game uses DirectDraw with Process Explorer:
https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer

In the view menu, make sure "Show Lower Pane" is enabled and "Lower Pane View" is set to "DLLs". Then you can see the list of DLLs loaded by the process. If it doesn't have ddraw.dll there (you can sort it by clicking on the Name column), then of course DDrawCompat won't do anything.

Are you sure the game has a DirectDraw mode at all? I can't see the system ddraw.dll being loaded.

**Comment by OpenRift412** [comment]
Huh. I guess it doesn't? But it's still a windows software-rendered game, so I wonder what API it uses...

**Comment by narzoul** [comment]
gho has it listed as a WinG32 app, which is supposedly just a wrapper over GDI.
https://sourceforge.net/p/dxwnd/discussion/general/thread/2227213f/#9773

**Comment by narzoul** [comment]
Bit more info on wiki, which also lists Fury3: https://en.wikipedia.org/wiki/WinG

**Comment by OpenRift412** [comment]
> Bit more info on wiki, which also lists Fury3: https://en.wikipedia.org/wiki/WinG

Well, damn. Looks like I'm not gonna find a wrapper for that one any time soon. I'm surprised Windows 11 still has native WinG support.
