### ISSUE TITLE
The Sims 1 CTDs for Pre-Windows-10 users after 0.3.2

### ISSUE THREAD

**Issue by voicemxil** [narzoul/DDrawCompat#217]
This did not occur before version 0.4.0. This was originally mentioned in https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/issues/61.
I then tested Windows 8.1 to see if the issues @Gaerthal-Estelmist mentioned were related to it, and encountered the same crash to desktop with a variety of configs including CPU affinity, borderless vs exclusive mode, and `DisplayResolution=app`. I have not been able to reproduce the same crash on later Windows versions such as 11 which I personally use with no issues.

The [DDC log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/issues/61#issuecomment-1475662508) lists no errors. [The Sims error log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/issues/61#issuecomment-1476409655) is unhelpful and simply lists "access_violation" as the error.

**Comment by narzoul** [comment]
Unfortunately, I don't have Windows 8.1 anymore, so I can't debug the issue on my end.

Please try to get a crash dump as described here: https://github.com/narzoul/DDrawCompat/issues/50#issuecomment-520162844
Also, enable debug logs by setting LogLevel=debug in DDrawCompat.ini, and attach the debug logs along with the crash dump.

**Comment by voicemxil** [comment]
[Sims.exe.3032.dmp.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/11053357/Sims.exe.3032.dmp.zip)
[DDrawCompat-Sims.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/11053361/DDrawCompat-Sims.log)

According to [this post](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/issues/61#issuecomment-1480405943), the "dirty" version of 0.4.0 fixed it for Windows 7, but did not help here on 8.1.

**Comment by voicemxil** [comment]
[DDrawCompat-Sims.log](https://github.com/narzoul/DDrawCompat/files/11054643/DDrawCompat-Sims.log)
[Sims.exe.3724.dmp.zip](https://github.com/narzoul/DDrawCompat/files/11054653/Sims.exe.3724.dmp.zip)

**Comment by voicemxil** [comment]
Thanks, I will test again when I get home in a couple of hours!

**Comment by voicemxil** [comment]
That worked! (low fps is just from running in VM.)
It needs `CPUAffinity=all` and especially `AltTabFix=keepvidmem` in order to be fully stable.
![image](https://user-images.githubusercontent.com/69059862/227407090-7d45a75c-68b1-4e22-bc55-3dcbd484bccd.png)

**Comment by narzoul** [comment]
I don't get it. Why didn't it work with just the Windows 7 fix then? The debug log fix shouldn't be needed unless someone's running the game with LogLevel=debug, and that's the only other issue I fixed compared to the Win7 patch.

**Comment by voicemxil** [comment]
> I don't get it. Why didn't it work with just the Windows 7 fix then? The debug log fix shouldn't be needed unless someone's running the game with LogLevel=debug, and that's the only other issue I fixed compared to the Win7 patch.

You asked me to enable the debug logs. Without that, the windows 7 fix only works.

**Comment by narzoul** [comment]
Yes, but in one of your posts in the widescreen patch issue, you said that the Win7 patch didn't work on 8.1:

> Interesting choice to upgrade to an even older version lol. Sadly that file did not fix the problem for 8.1.

Or did you also have debug logs enabled back then?

**Comment by narzoul** [comment]
The Win 7/8 crashes are fixed in v0.5.0.
