### ISSUE TITLE
DirectX 6 renderer crashes on startup

### ISSUE THREAD

**Issue by PlayNeth** [narzoul/DDrawCompat#218]
Another issue I forgot to report that you reminded me of in the previous issue: DirectX 6 doesn't seem work in NFS IV at all, crashes upon startup every single time, but at least this time I was able to obtain a crash dump from the .exe: 

[nfshs.exe.5576.zip](https://github.com/narzoul/DDrawCompat/files/11057341/nfshs.exe.5576.zip)
And the log file:
[DDrawCompat-nfshs.log](https://github.com/narzoul/DDrawCompat/files/11057759/DDrawCompat-nfshs.log)

I'm sure it has to do with DirectX 6 because whenever I use the vanilla d3da.dll (DX6) from NFS IV in NFS 3 it crashes there as well
Using the latest version of ddrawcompat

**Comment by BEENNath58** [comment]
I had a similar issue but it was fixed with DxWnd. There were performance issues, and DDC fixed both the crash as well as the performance together.
https://github.com/narzoul/DDrawCompat/issues/166

**Comment by narzoul** [comment]
@PlayNeth Can you confirm if the fix mentioned by @BEENNath58 works or not?

**Comment by narzoul** [comment]
The crash dump you originally attached is definitely the same issue, so the patched ddraw.dll should fix it. I see you're using some integrated Intel GPU though, so there may be other bugs with it also. Please attach another crash dump and debug log with the patched ddraw.dll from the other issue.

**Comment by PlayNeth** [comment]
Alright. By the way, this laptop I'm using has a dual GPU configuration, iGPU main discrete nvidia second. Just in case this piece of info might come in handy in the future
[nfshs.exe.6044.zip](https://github.com/narzoul/DDrawCompat/files/11301777/nfshs.exe.6044.zip)

**Comment by narzoul** [comment]
Odd, it crashes at the same place still. I've added some extra debug logs, please use this version:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/11301856/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/11301857/diff.txt) compared to v0.4.0)

Attaching the debug log file will be enough this time.

**Comment by PlayNeth** [comment]
It isn't instantly crashing anymore so that is definitely some good progress. Now it's behaving the same exact way in the previous issue, as in freezing with a black screen in borderless mode and working flawlessly in exclusive

**Comment by narzoul** [comment]
So the fix from #166 is working after all. I guess you were using the wrong ddraw.dll before?

The latest issue is indeed the same one which was solved in #218, I just forgot to include that fix in the patch above. Here's a combined version with both fixes:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/11301973/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/11301974/diff.txt) compared to v0.4.0)

**Comment by PlayNeth** [comment]
Probably, think I got mixed up with the dll files lol, my bad.
Anyways, seems to be working like a charm now. Many thanks once again

**Comment by narzoul** [comment]
Fixed in v0.5.0.
