### ISSUE TITLE
If play game use Full screen ,playing game crash ,THX software can play lots of old game!!

### ISSUE THREAD

**Issue by xingbarking** [narzoul/DDrawCompat#220]
log file error:
14:06:41.329 Installing DirectDraw hooks
14:06:41.336 Installing Direct3D hooks
14:06:41.339 Installing GDI hooks
14:06:41.350 Finished installing hooks
14:06:41.662 Using Direct3D device type: IID_IDirect3DHALDevice
14:06:42.278 ERROR: Failed to create repository surface: 0x80070057 {0x1007,0,0,0,0,0,0,0,null,{0x40,0x0,16,0xf800,0x7e0,0x1f,0x0},{0x5000,0x0,0x0,0x0},0}
14:09:50.501 ERROR: Failed to create the compat primary surface: 0x88760091

**Comment by narzoul** [comment]
Could you specify which game you're talking about? It's hard to tell anything from just those logs, I need to be able to reproduce the issue.
