### ISSUE TITLE
Anything special about the "5" key?

### ISSUE THREAD

**Issue by WesCov** [narzoul/DDrawCompat#222]
I have been running Mig Alley for several months now (thanks to your help) and all of a sudden key presses of the keyboard "5" are being ignored but only during the simulation.  In the preferences interface the 5 produces input.  Because it only happens during simulation I wondered if there was some special function assigned to the number 5 in the ddraw.dll.

In DDrawCompat.ini I have  the line ConfigHotkey=none to disable the Shift F11 hot key but nothing to do with 5.

If I delete the settings.mig file the issue goes away until I restart the game (settings.mig is created during program close).  I don't know what the implications are of that.

**Comment by narzoul** [comment]
No, there is nothing special about the 5 key. The only hotkey currently handled by DDrawCompat is the ConfigHotkey. If everything was working fine previously, then maybe you installed some other software whose hotkeys are interfering?

**Comment by WesCov** [comment]
Thanks.  It is so strange.  It works fine for one session, but after closing the game and restarting the issue pops up.  Thanks for the reply so I can cross one thing off the list.
