### ISSUE TITLE
Feature request: GPU Selector

### ISSUE THREAD

**Issue by PlayNeth** [narzoul/DDrawCompat#224]
Noticed some hard frame drops in some games so I decided to investigate, and it seems like DDrawCompat isn't picking up my nvidia GPU whatsoever, seems to be always rendering from the iGPU despite having the game's .exe selected to high performance in both the nvidia control panel and windows's gpu selector
![image](https://user-images.githubusercontent.com/82559127/235282983-16bc9231-1738-45fe-8380-76f8462a6b58.png)
![image](https://user-images.githubusercontent.com/82559127/235283018-e87bb40c-1801-45ae-83a8-a0a438b06454.png)
![image](https://user-images.githubusercontent.com/82559127/235283053-ae245cd5-e4e5-4b79-96f6-7bc5b422dc21.png)

**Comment by narzoul** [comment]
I can't do much about it, it's a documented restriction:
https://nvidia.custhelp.com/app/answers/detail/a_id/3733/~/games-based-on-directx-8-and-older-versions-of-directx-will-only-run-on

Maybe ForceD3D9On12 can work around it, but I don't have an Optimus laptop to try it. Also compatibility with D3D9On12 is not the best at the moment, and performance is generally worse than native.

**Comment by PlayNeth** [comment]
But does DDC not wrap most API calls to dx9's though? in theory that should work to just get the GPU to detect the game

**Comment by narzoul** [comment]
No. This is covered at the very beginning of the [README](https://github.com/narzoul/DDrawCompat/blob/master/README.md):

> There is no API conversion involved, most of the rendering is still done by the native DirectDraw/Direct3D 1-7 and GDI libraries.

**Comment by PlayNeth** [comment]
I see. There is not a single day that passes where I don't regret not going with the AMD variant of my laptop. Thanks for the info though
