### ISSUE TITLE
Colin McRae Rally 1 (1998) doesn't launch

### ISSUE THREAD

**Issue by Nustat0** [narzoul/DDrawCompat#232]
Game closes instantly on startup.

GPU: Intel HD 530 + GTX 960M (Optimus laptop)

OS: Windows 10 Home 22H2 (19045.3086)

DDrawCompat: v0.4.0

Debug log:
[DDrawCompat-Rally.log](https://github.com/narzoul/DDrawCompat/files/11817036/DDrawCompat-Rally.log)

**Comment by narzoul** [comment]
Indeed, there is a bug in DDrawCompat which causes the last GetAttachedSurface method call to fail, which leads to a crash. This quick fix should solve it for now:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/12137333/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/12137334/diff.txt) compared to v0.4.0)
