### ISSUE TITLE
Claw 1997

### ISSUE THREAD

**Issue by ahmed-sameh1** [narzoul/DDrawCompat#233]
When I press Windows on the keyboard and go back everything disappear 
![image](https://github.com/narzoul/DDrawCompat/assets/132032325/966a5018-1cc6-4161-b3d4-635d35233148)

**Comment by narzoul** [comment]
This issue only seems to affect the CrazyHook modded 1.4.4.4 version. The official 1.3 patch works fine.

AltTabFix=keepvidmem setting fixes this issue but there is still a double cursor side effect, which may be a bug in either DDrawCompat or the game, it needs more investigation.

**Comment by ahmed-sameh1** [comment]
Where to get the 1.3

**Comment by narzoul** [comment]
Try here: https://www.patches-scrolls.de/patch/756/7/20887

**Comment by narzoul** [comment]
I don't know. Back it up, just in case.

**Comment by ahmed-sameh1** [comment]
It is a virus dude

**Comment by narzoul** [comment]
What? VirusTotal reports nothing on any of those files:
https://www.virustotal.com/gui/file/39bd0515c5878a52667c7cdb7140e1895f2efb595be889e98dba07dae1069541
https://www.virustotal.com/gui/file/00fe919bd562de233f813870bd9e0cd454175e2f661659e90b6d7746261e3e35
https://www.virustotal.com/gui/file/cd0f1ac4d0009fcae4faded0d106a0c5acd0c3bf17a048314230a05f2d429f39

**Comment by ahmed-sameh1** [comment]
Malwarebytes find it as onr

**Comment by narzoul** [comment]
Strange, PCGamingWiki has a copy of the exact same archive:
https://www.pcgamingwiki.com/wiki/Claw
And so does the fan site that distributes the Claw v1.4.4.4 'CrazyHook' version that you're currently playing, apparently:
https://captainclaw.net/en/downloads.html

So what does your Malwarebytes say exactly? Isn't it just a heuristic? And in which file exactly? You only need claw.exe.

Anyway, it's up to you what to do with it. If you don't trust it, I don't want to force any solutions on you.

**Comment by ahmed-sameh1** [comment]
It says it is malware sandbox

**Comment by ahmed-sameh1** [comment]
Abd ges thats where i got it

**Comment by narzoul** [comment]
I found a workaround for the double cursor issue that should work for Claw 1.4.4.4 too. Here's a test build:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/12012567/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/12012568/diff.txt) compared to v0.4.0)
You still need to use the AltTabFix=keepvidmem setting.

**Comment by ahmed-sameh1** [comment]
Ima give it a shot

**Comment by ahmed-sameh1** [comment]
Github is bad tho i didn't use this acc since i made it js for the student pavk lol

**Comment by ahmed-sameh1** [comment]
Give me 1h

**Comment by ahmed-sameh1** [comment]
still the same sorry for late reply i got an emergency..

**Comment by ahmed-sameh1** [comment]
The original one or the fixed version

**Comment by narzoul** [comment]
The fixed one of course.

**Comment by ahmed-sameh1** [comment]
good morning
here is the log and my setti
![Screenshot 2023-07-14 120758](https://github.com/narzoul/DDrawCompat/assets/132032325/1a98c3a4-a30c-4e32-a687-6a7e59e71fd0)
ng
[DDrawCompat-CLAW.log](https://github.com/narzoul/DDrawCompat/files/12048214/DDrawCompat-CLAW.log)

**Comment by ahmed-sameh1** [comment]
i guess it will be better in you tried this yourself and try to update the ddraw fixed

**Comment by ahmed-sameh1** [comment]
tbh urs is the best so far but just this issue with claw thanks for your efforts narzoul

**Comment by ahmed-sameh1** [comment]
[DDrawCompat-CLAW[2].log](https://github.com/narzoul/DDrawCompat/files/12048259/DDrawCompat-CLAW.2.log)
this was there too in case u need it

**Comment by ahmed-sameh1** [comment]
Ok let me see

**Comment by ahmed-sameh1** [comment]
Worked !!

**Comment by ahmed-sameh1** [comment]
Thank you man i appreciate it u rlly helped me

**Comment by ahmed-sameh1** [comment]
Oh u still remember me

**Comment by ahmed-sameh1** [comment]
Can u send the file

**Comment by narzoul** [comment]
You can download it under [releases](https://github.com/narzoul/DDrawCompat/releases/tag/v0.5.0) as usual.

Direct link: https://github.com/narzoul/DDrawCompat/releases/download/v0.5.0/DDrawCompat-v0.5.0.zip

Also, please try not to "spam" messages here, I (and probably other people) get e-mail notifications about every new message.
