### ISSUE TITLE
Astrobatics by Kraisoft Entertainment fix

### ISSUE THREAD

**Issue by GabrielMontesa** [narzoul/DDrawCompat#237]
THANK YOU for the people who made this DLL together for fixing my childhood game! I cannot express the happiness I finally got for months or even after 1 year of trying to find some patches! You are a blessing from the heavens!

**Comment by narzoul** [comment]
Well, since this isn't an issue per se, I'll proceed to close this so it doesn't clutter the already long list of open issues further. But thanks for the kind words, I'm glad you found this project useful!
