### ISSUE TITLE
Barbie Generation Girl Gotta Groove massive problems

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#242]
This game has massive graphical problems. The only place I got it to work is in Win98SE with PCem Voodoo2 or in WinME through WineD3D wrapper in the SoftGPU package.

I used DDC by just copying the CD to HDD and placing ddraw.dll there (the game exxutable runs directly off the CD).

The photos will be explanatory, there are a lot of graphical issues but here are some:
![Screenshot 2023-08-11 120505](https://github.com/narzoul/DDrawCompat/assets/64649734/89354dbf-d710-4f95-89fa-cbd58f94a214)

![Screenshot 2023-08-11 120640](https://github.com/narzoul/DDrawCompat/assets/64649734/ecb7e905-bf94-40b2-8c17-35ea1d0b31a8)

**Comment by BEENNath58** [comment]
Randomly asking, did you try it anytime?

**Comment by narzoul** [comment]
I don't think it's a ddraw or D3D issue. If you block the Direct3D HAL device from enumeration, then the game doesn't even use Direct3D at all, and uses its own software renderer instead. All it does is lock a 640x480 surface to render into via CPU, unlock it, then blit (copy) it to the primary surface. And yet it has the same graphical corruptions as with D3D, so it must be some internal engine issue. Whatever it is, I don't want to reverse engineer the game to find out, so I'll pass on this one.
