### ISSUE TITLE
Transparancy , ddraw issues black borders, legend  of mir 3

### ISSUE THREAD

**Issue by Xzoviac** [narzoul/DDrawCompat#243]
Hi, thank you for all your hard work firstly, and i hope you can help me since a windows 10 update i get black boarders  around the ui, like the transparency  has broken in the game 

If i turn on DdrawFixByteAlignment      = 0  - turns off  it fixes the black borders  but all the background ui disappears and it makes everything see-through 
![image-28](https://github.com/narzoul/DDrawCompat/assets/68870883/6776ce62-d4b0-452b-8856-947199f7c1ca)
![image-34](https://github.com/narzoul/DDrawCompat/assets/68870883/9b2ca937-2123-4f33-b3af-4159a1a3e125)

I hope you can help!
https://drive.google.com/file/d/1VC-Ls4iwfPYR91yVJktJRMpPP4sgJrBs/view?usp=drivesdk
This is the game if you need to test anything

**Comment by FaustGoN** [comment]
hi, same problem on windows 11

**Comment by narzoul** [comment]
Quoting myself from the README:

For various reasons, the below cases are not supported:
- Games that require an internet connection
- ...
