### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by midtown96** [narzoul/DDrawCompat#248]
Is it still possible to download the direct draw fixes?
I have many more old games to fix but I cant find where I can download the fixes.
Which I know, the latest fix is 0.40.
Where can I download DirectDrawCompact 0.40?
Where can I download ThirteenAG/WidescreenFixesPack for Sonic heroes?

**Comment by narzoul** [comment]
You can generally find downloads under the **Releases** section of each project. The link to **Releases** is on the right side of the main page (click the "**<> Code**" tab above to go to the main page):

![releases](https://github.com/narzoul/DDrawCompat/assets/16432233/652f4999-ea83-490f-907d-55c52980adb2)

Then you'll find download links under **Assets** at the bottom of each release. You may have to click on **Assets** first to show the actual downloadable files.

Direct links to the releases you asked for:
https://github.com/narzoul/DDrawCompat/releases/tag/v0.4.0
https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/sonicheroes
