### ISSUE TITLE
C&C Tiberian Sun Alt+Tab issue on windows 10

### ISSUE THREAD

**Issue by FunkyFr3sh** [narzoul/DDrawCompat#25]
Sometimes you can't get back into the game after Alt+Tab, clicking on the taskbar icon to maximize the game doesn't work (No reaction)

This time I'm prepared, logs are below!
https://drive.google.com/drive/folders/0B5by5H1Q2PxEN2NyTm9fM3k5UDA?usp=sharing

So what I did is the following:
1) Start the game
2) Go into skirmish with 1 AI
3) Alt+Tab a few times

I tried it with C&C Red Alert too, but it didn't seem to happen there (Will do some more testing soon)

**Edit:
The first time seems to work always for any reason.
When the bug occurs and you wait 30-40 seconds then it will eventually maximize again
I attached a third log where the game maximized again after very long waiting time**

**Comment by FunkyFr3sh** [comment]
Found a workaround, 

ActivateAppHandler.c -> LRESULT CALLBACK ddWndProc

```
                case WM_ACTIVATE:
		{
			if (wParam == WA_INACTIVE)
			{
				ShowWindow(hwnd, SW_MINIMIZE);
			}
			break;
		}
```

**Comment by narzoul** [comment]
I can't reproduce this with the latest experimental release. I assume it's been fixed already. If it's not the case. please reopen this.
