### ISSUE TITLE
[Bug] Point display filtering not working

### ISSUE THREAD

**Issue by OpenRift412** [narzoul/DDrawCompat#252]
Was testing out the new release and found that the point option for display filtering doesn't seem to be working at all. It seems to just be using whatever the default is.

**Comment by narzoul** [comment]
You're right, I must have broken it with one of the recent changes before release. I also forgot to document that downscaling was changed to use convolution for all existing filters too, which means it would apply a box filter for the "point" option.

Well, luckily this isn't the most important filter, but I'll try to fix it.

**Comment by OpenRift412** [comment]
> Well, luckily this isn't the most important filter, but I'll try to fix it.

I would argue otherwise, but that's ultimately up to you.

**Comment by narzoul** [comment]
It seems to have been a simple issue, here's a quick fix until the next release:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/13341812/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/13341815/diff.txt) compared to v0.5.0)

**Comment by narzoul** [comment]
Fixed in v0.5.1.
