### ISSUE TITLE
[Suggestion] Option to Disable Direct3D Wrapping

### ISSUE THREAD

**Issue by OpenRift412** [narzoul/DDrawCompat#253]
Just an idea for the sake of modularity, having the ability to let other wrappers handle the direct3D portion might be a good idea in terms of versatility. Don't know if this is feasible or not, but I thought I might as well make the suggestion.

**Comment by narzoul** [comment]
Not feasible in DDrawCompat. Besides, as the README already states, mixing with other wrappers/hooks is not supported, and this is unlikely to ever change.

Direct3D 7 and older versions are so tightly integrated with DirectDraw that I doubt any other wrappers would support this either, anyway.
