### ISSUE TITLE
Superbike 2001 always crashes

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#254]
The game fails with whatever I try. If I run natively, I get a Primary surface error and the game crashes.

If I run with dgVoodoo2 or DxWnd, the game plays the EA logo and then crashes.

If I use DDC, the game freezes after the EA logo.

I logged the game using DxWnd, there is a DDERR_UNSUPPORTED relative to a UNSUPP(orted) return value from DxWnd that only relates to the screen position and resolution (saying because I never saw an error in this form).

I also attached the DDC log.
[DDrawCompat-SBK2001.log](https://github.com/narzoul/DDrawCompat/files/13345374/DDrawCompat-SBK2001.log)

**Comment by narzoul** [comment]
It seems to suffer from random memory errors. I got farther with the FaultTolerantHeap shim, but it still randomly locks up in the menu, and it always freezes at the end of loading a track.

**Comment by narzoul** [comment]
With dgVoodoo, the first frame of the race can be seen, then it crashes in mssds3ds.m3d, which seems to be a component of Miles Sound System. But even after I turned sound and music off, it still crashes there. This looks like a fairly hopeless case.

**Comment by BEENNath58** [comment]
Apparently the game works when run through a debugger and an error is skipped 
https://sourceforge.net/p/dxwnd/discussion/general/thread/83109ba2ef/#9464

**Comment by BEENNath58** [comment]
Update: The crash seems to be fixed with Win98 mode, that unfortunately didn't do anything for me (Win11 EmulateHeap?)

However DDC runs the game at 4x speed than dgV2 on Win10.
