### ISSUE TITLE
Rich4 DDrawCompat-v0.5.0 displays black screen

### ISSUE THREAD

**Issue by horxd33** [narzoul/DDrawCompat#256]
Rich4 v3.11 (game) opens the game with DDrawCompat-v0.4.0 (ddraw.dll) default settings and can display normally, load the game and play

Rich4 v3.11 (game) will display a black screen when opening the game with DDrawCompat-v0.5.0 (ddraw.dll) default settings, but there will be a sound to confirm that the game can be loaded.
I fiddled with the settings but still can't display the screen properly.
I tried forcing ForceD3D9On12 settings. The loading menu will not display a black screen, but there will be some graphics errors after entering the game.

The following are relevant logs
https://mega.nz/folder/MGRgSaaR#n1sVRZwityvJL6lKFrhVUQ

Maybe a little irrelevant discussion
https://sourceforge.net/p/dxwnd/discussion/general/thread/98e13c2ffe/

**Comment by narzoul** [comment]
From a quick look, it's the same issue as #255. Hopefully when I figure that one out, it'll fix this too.

**Comment by narzoul** [comment]
Please try the fix candidate posted under the other issue and let me know if it works any better.

**Comment by horxd33** [comment]
@narzoul I tried DDrawCompat-v0.5.0-debug-previous-builds.7z from https://github.com/narzoul/DDrawCompat/issues/255

v0.4.0-29-g12c4f87c (the last version that can display normally without black screen)

v0.4.0-30-gdefdfafe (from this version onwards, a black screen will be displayed)

Log added
https://mega.nz/folder/MGRgSaaR#n1sVRZwityvJL6lKFrhVUQ

DDrawCompat-Rich4(DDrawCompat-v0.5.0-debug-previous-builds_v0.4.0-29-g12c4f87c).log
DDrawCompat-Rich4(DDrawCompat-v0.5.0-debug-previous-builds_v0.4.0-30-gdefdfafe).log

**Comment by horxd33** [comment]
@narzoul Tried https://github.com/narzoul/DDrawCompat/issues/255#issuecomment-1813390855 and it still displays a black screen.

Log added
DDrawCompat-Rich4(issuecomment-1813390855).log

**Comment by narzoul** [comment]
Please check the new fix in the other issue, apparently it worked for the other guys: https://github.com/narzoul/DDrawCompat/issues/255#issuecomment-1815469410

**Comment by horxd33** [comment]
@narzoul Tried https://github.com/narzoul/DDrawCompat/issues/255#issuecomment-1815469410 The black screen problem has been fixed
But new problems were found, compared with DDrawCompat-v0.4.0
In issuecomment-1815469410 & v0.4.0-7-g246108bb, there is a crash problem when moving the mouse quickly

v0.4.0-6-g66ad6db3 (the last version that does not crash when moving the mouse quickly)

v0.4.0-7-g246108bb (This version begins to crash after moving the mouse quickly)

Log added
issuecomment-1815469410
DDrawCompat-Rich4(issuecomment-1815469410).log
DDrawCompat-Rich4(issuecomment-1815469410-debug).log

Rich4 issuecomment-1815469410 & v0.4.0-7-g246108bb crashes after moving the mouse quickly
DDrawCompat-Rich4(issuecomment-1815469410-debug_Crash dump).log
DDrawCompat-Rich4(issuecomment-1815469410-debug_Crash dump).dmp
DDrawCompat-Rich4(DDrawCompat-v0.5.0-debug-previous-builds_v0.4.0-6-g66ad6db3).log
DDrawCompat-Rich4(DDrawCompat-v0.5.0-debug-previous-builds_v0.4.0-7-g246108bb).log
DDrawCompat-Rich4(DDrawCompat-v0.5.0-debug-previous-builds_v0.4.0-6-g66ad6db3-debug).log
DDrawCompat-Rich4(DDrawCompat-v0.5.0-debug-previous-builds_v0.4.0-7-g246108bb-debug).log

**Comment by narzoul** [comment]
Ok, that last issue has nothing to do with Intel drivers at least. I don't remember what game I made the fix for that caused this crash for you, but I reverted it anyway for now. I guess I'll revisit it when I bump into the original issue again.

Please try the new v0.5.1 release, hopefully it solves all of the above issues.

**Comment by horxd33** [comment]
@narzoul After testing DDrawCompat-v0.5.1 version, it is confirmed that the crash problem after moving the mouse quickly has been solved.
Thanks for the instant fix

**Comment by narzoul** [comment]
Great, thanks for the detailed reports!
