### ISSUE TITLE
how to enable anti aliasing?

### ISSUE THREAD

**Issue by reignerdeustcher** [narzoul/DDrawCompat#258]
i just added the ddraw file inside superbike 2001 and now the game runs great! but i would like to enable anti aliasing, i don't see any config file for that

**Comment by narzoul** [comment]
Did you check the [Configuration wiki](https://github.com/narzoul/DDrawCompat/wiki/Configuration)?

**Comment by BEENNath58** [comment]
Helped here
https://www.vogons.org/viewtopic.php?p=1212225#p1212225

**Comment by reignerdeustcher** [comment]
> Helped here https://www.vogons.org/viewtopic.php?p=1212225#p1212225

thanks!!!
