### ISSUE TITLE
C&C Tiberian Sun Menus Invisible on windows 10

### ISSUE THREAD

**Issue by FunkyFr3sh** [narzoul/DDrawCompat#26]
Menus are invisible since a recent update. 

The following commit is causing the issue: https://github.com/narzoul/DDrawCompat/commit/3f1fa0fae1f20bec86bcb5fef9771a9f47aff4d1

I justed tested it and it seems to happen only in window mode as guessed by @narzoul 

To start the game in window mode you'll have to pass a "-win" parameter to game.exe

**Comment by narzoul** [comment]
Fixed in latest experimental release.
