### ISSUE TITLE
A surface not drawn correctly in Red Alert 2 and Yuri's Revenge

### ISSUE THREAD

**Issue by tomsons26** [narzoul/DDrawCompat#261]
![image](https://github.com/narzoul/DDrawCompat/assets/1433426/eb34bf18-7141-475f-82db-6860fcacb0f9)
You can test this quickly by starting a new short skirmish game and selling off the Construction Yard.
The Victorious/Defeated surface isn't drawn at the correct size and is overlaid by a white box.

I'm on a iGPU, i'm being told this doesn't happen with dedicated GPUs.
This occurs in fullscreen, borderless and windowed modes.
This occurs with default ini settings(ie no ini at all).

As a community reverse engineer on these games i can't really say what makes this different to all other surfaces.
For the white box my only guess is Tiberian Sun drew GDI text on game win/loss not a image.
The code for drawing the text may still be active here and just drawing a blank text, which the surface of for some reason doesn't get keyed out.

**Comment by narzoul** [comment]
I can't reproduce the issue on my end with NVIDIA or AMD dedicated GPUs. I don't have any integrated ones to test at the moment.
Please reproduce the issue with LogLevel=debug and upload the debug log.

Has this been an issue with older releases like v0.4.0 too? In which release did it first appear? Does it work natively without DDrawCompat?

**Comment by tomsons26** [comment]
0.5.0 didn't work at all, game just resulted in a lockup and black screen was then informed that there's a fix for iGPUs in 0.5.1.
Seems no dice on the log, it grows to over 1GB too quick, by the time i make it ingame it's over 1GB

**Comment by tomsons26** [comment]
seems i have a local corrupt file, sorry for the trouble
