### ISSUE TITLE
Harry Potter and the Chamber of Secrets (Issue)

### ISSUE THREAD

**Issue by Sergiut99** [narzoul/DDrawCompat#264]
I used your latest version 0.5.1. The game splash screen starts and the keyboard freezes... We can't control the game.
The latest version of the program that doesn't have this issue is DDrawCompat v0.2.1. But this old version ddraw.dll doesn't work well with the game. The game lags already in the options, if you move the cursor of the game.
Please fix. because it is impossible to play. And we really need  for the game the performance, stable fps in all locations.
The game uses DirectX7 renderer.
In default.ini
```
[Engine.Engine]
GameRenderDevice=D3DDrv.D3DRenderDevice
```

The game was tested on Windows 7 (64-bit)... The game's resolution was set to 1280x960 (4:3)

**Comment by Sergiut99** [comment]
log
[DDrawCompat-Game.log](https://github.com/narzoul/DDrawCompat/files/13453057/DDrawCompat-Game.log)

**Comment by narzoul** [comment]
It was broken by https://github.com/narzoul/DDrawCompat/commit/2f52e1028b45f3874dcd99fef74b95ab36c2a334
Oh well, I guess there is no good solution to that other problem, but it's not that important.

I'll fix this for the next release, for now here's a quick fix you can test:
[ddraw.zip](https://github.com/narzoul/DDrawCompat/files/13453238/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/13453242/diff.txt) compared to v0.5.1)

**Comment by Sergiut99** [comment]
This fix works!!! Thank you very much !!!

**Comment by narzoul** [comment]
Fixed in v0.5.2.
