### ISSUE TITLE
How to mix GDI and Direct3D

### ISSUE THREAD

**Issue by elishacloud** [narzoul/DDrawCompat#269]
There is a long standing issue that was caused in an update to Windows 10 a few years ago (specifically in Windows 10 [Fall Creators Edition](https://blogs.windows.com/windowsexperience/2017/10/17/whats-new-windows-10-fall-creators-update/)) and still manifests itself in Windows 11.  The issue is that once you call `Present()` onto a window from Direct3D9 when running in exclusive fullscreen mode it will overwrite all GDI on the screen.  Even if later you try and draw things in GDI then it will not be seen at all.

This used to work, and according to the [Microsoft documentation](https://devblogs.microsoft.com/directx/dxgi-flip-model/#when-should-i-use-blt-model) this should work.  It also works fine on Direct3D8 (and older) and on DirectDraw (as you know).  But the issue only manifests itself if using Direct3D9 and exclusive fullscreen mode.  The reason this is an issue is because I have been working to convert older Direct3D into Direct3D9 and some games play their video or show text on the screen using GDI, which completely disappears when upgrading it to Direct3D9.

I have already tried setting DisableMaxWindowedMode, which I thought should solve it but it does not.  The only solution I have been able to come up with is to build a fullscreen windowed mode option.  But this causes other issues.

There are some additional details about this [here](https://github.com/crosire/d3d8to9/issues/61) and in this thread starting [here](https://github.com/elishacloud/dxwrapper/issues/177#issuecomment-1507289679).

I know you are not an expert at Direct3D, but this question is not directly related to DirectD3, rather the interaction between things created in GDI vs Direct3D.

Any ideas or thoughts you have here would be appreciated.

**Comment by narzoul** [comment]
I followed the registry changes (except for the GameDVR_FSEBehavior key, which I don't have) here:
https://www.reddit.com/r/pcgaming/comments/ck13z9/psa_windows_10_1903_will_now_ignore_the_disable/

After restarting my PC (not sure if needed), Indiana Jones now uses "Hardware: Legacy Flip" mode with d3d8to9, and indeed a top-level window is no longer visible above it (but the cursor still changes, so I know it's there). Unless the top-level window was already above the game window around the time when the game entered fullscreen mode, in which case it uses "Hardware Composed: Independent Flip" instead, and the other top-level window becomes visible again. What a mess...

However, I still couldn't figure out how to enable maximized windowed mode for D3D9.

**Comment by elishacloud** [comment]
> I still couldn't figure out how to enable maximized windowed mode for D3D9

[Here](https://github.com/elishacloud/dxwrapper/blob/b72ab666fd8dc045b6a04c358e7a883182f9aa4a/d3d9/d3d9.cpp#L169-L217) is some code I made to set maximized windowed mode for D3D9.

**Comment by elishacloud** [comment]
BTW: I also noticed that D3D9 creates a new window and puts that window at the top of all other windows.  I caught this by hooking the CreateWindowEx() functions.

**Comment by narzoul** [comment]
> [Here](https://github.com/elishacloud/dxwrapper/blob/b72ab666fd8dc045b6a04c358e7a883182f9aa4a/d3d9/d3d9.cpp#L169-L217) is some code I made to set maximized windowed mode for D3D9.
> 
> Edit: I tested this code and it did work in disabling maximized windowed mode.

I mean we're looking for a way to enable it, not disable it. It should be disabled by default. With disabled, GDI won't work I think. It doesn't work with DirectDraw either, except in maximized windowed mode.

**Comment by elishacloud** [comment]
I thought you could just call `Direct3D9EnableMaximizedWindowedModeShim` to enable it?  When I looked at the code in a debugger it was set to '1' by default.  When I [set it to '0'](https://github.com/elishacloud/dxwrapper/blob/b72ab666fd8dc045b6a04c358e7a883182f9aa4a/d3d9/d3d9.cpp#L207) it disables it.  When I tested it last I could see a difference between the two modes.

**Comment by elishacloud** [comment]
Ok, I think I figured something out.  If I hook [Direct3D9SetSwapEffectUpgradeShim](https://github.com/crosire/reshade/commit/3fe0b050706fb9f3510ed48d619cad71f7cb28f2) then I can see a call to this function when the application starts with a parameter of `0`.  If I drop the call and not pass it to the dll then the game runs and GDI can be seen on fullscreen exclusive mode.

**Comment by narzoul** [comment]
Well, I have no idea anymore. I've never heard of these shims before. What shim is supposed to call this function? I can't find any references to it. Does it change the presentation mode according to PresentMon?

**Comment by elishacloud** [comment]
First of all, thank you for the response and looking into this.  Your comments helped me search for this solution.  I have never heard of these extra shims either.

PresentMon is showing as "Hardware: Legacy Flip" when I call `Direct3D9SetSwapEffectUpgradeShim(0)`.

**Comment by elishacloud** [comment]
Closing

**Comment by mirh** [comment]
First time I hear about this shim.. Though I guess it makes sense it exists, considering microsoft wanted to uplift everything to flip. 
Though, you should always interpret any windows 10 behaviour detail to be just a data point, only applying to the specific version/build that was tested (and even then with not that much of a strong confidence, considering just how contrived some conditional checks can be). See for instance the lost [big epic](https://github.com/crosire/d3d8to9/pull/143#issuecomment-1463246398) of d3d8 exclusive fullscreen.

**Comment by elishacloud** [comment]
> only applying to the specific version/build that was tested (and even then with not that much of a strong confidence, considering just how contrived some conditional checks can be

Yeah.  For this I check the following:

1. Make sure it is a System32 dll.
2. Load the address with the specific ordinal.
3. Make sure the address is going to an unnamed ordinal.
4. Add a [dxwrapper option](https://github.com/elishacloud/dxwrapper/blob/6aeb0773c3d759056c812b44f5ede21417dcde88/d3d8/d3d8.cpp#L224) to disable this if needed in the future.

Hopefully, Microsoft will not remove this function and add a different hidden function with the same ordinal as this one was.  I don't see that as very likely.  I suspect if Microsoft creates other unnamed functions they will give them different ordinal numbers.  There are plenty of numbers out there to use...

**Comment by mirh** [comment]
I meant the conditions that triggers such or such behaviors to begin with (i.e. when conversely the fixes are required)
Not something that would concern you implementation-wise. 
(I just mentioned the d3d8 thing because the linked comment in the second post wasn't exactly fresh)

**Comment by elishacloud** [comment]
> I meant the conditions that triggers such or such behaviors to begin with (i.e. when conversely the fixes are required)

When a game tries to display GDI (like a bik movie) to the screen when it is in Direct3D9 fullscreen exclusive mode then it just shows a black screen and nothing can be seen.  This could also happen when a game writes text to the screen using GDI rather than DirectX and then game is in Direct3D9 fullscreen exclusive mode.

However, the issue here is that I need to call this `Direct3D9SetSwapEffectUpgradeShim(0)` before creating the d3d9 device, which also happens to be before the issue happens.  Meaning I need to call this API before knowing whether I need to call it.

**Comment by mirh** [comment]
Can't you later reset the swapchain/device? (and yes this is a brazen drop-in because I'm trying to spread the load, and awareness)

```C++
CSwapChain::Reset{
	// stuff for HybridChildDevice
	// surprisingly one _D3D8RestoreDevice call too?
	if ((??? != 0) && RequiresSwapEffectUpgrade){ // see below IsMaximizedWindowedModeSwapEffectUpgradesEnabled
		if (??? != 0)){
			???? = CEnum::IsSwapEffectUpgradeFormatSupported(whatever){
				GetProxyFormat
			}
		}
	}
	//gotos I'm skipping the SetSwapChainDisplayMode branch that I believe is FSE
	//SetDialogBoxMode error if back buffer format isn't GDI friendly"
	///SetDialogBoxMode error if no D3DMULTISAMPLE_NONE
	////SetDialogBoxMode error if no D3DSWAPEFFECT_DISCARD
	/////SetDialogBoxMode error if no backbuffers are lockable
	
	if (IsWindowedInternal(this)) {
		CreateWindowed{
			if (???) DirectFlipCandidate{
				DirectFlipModeMatch{
					DirectFlipModeMatch + LuidMatch + other params
				}
			}
			CSwapChain::CheckWorkarounds // ?????????
			UseProxyFlip
		}
	} else {
		CreateFullscreen{
			// maybe this is FSE when you don't need (or already) changed resolutions?
			// nothing really special - except one funny IsDX9LBackBufferBehavior
		}
	}
	IsMaximizedWindowedModeSwapEffectUpgradesEnabled{
		UpdateMaximizedWindowedModeShimState{
			QueryGameConfigStoreSettings{
				 LoadLibraryExW("ext-ms-win-core-resourcepolicy-l1-1-0.dll")
				 GameConfigStore::Init
				 QueryDxgGameConfigStoreGPropDisableMaxWinMode
				 QueryDxgGameConfigStore
			}
			if (MaximizedWindowedFullscreenGame){
				g_MaximizedWindowedModeShim = (MaximizedWindowedShimInfo)0x1
				g_SwapEffectUpgradesShim = (MaximizedWindowedShimInfo)0x1 // ordinal 18 maybe?
				QueryRegKeys("MaximizedWindowedMode","Software\\Microsoft\\Direct3D\\Shims\\MaximizedWindowedMode")
			}
		}
	}
	IsMaximizedWindowedModeShimEnabled{
		//it seems pretty much equal to UpdateMaximizedWindowedModeShimState tbh
	}
	CD3D9TelemetryHelper::LogResetSwapChainEvent{
		// this seems just logging, but one variable is type "Variant_D3D9_GameConfigStore_Override"
	}
}
```
FWIW this is whatever logic I could make out of the d3d9.dll strings in bumpkin-pseudocode. This is less than 1% of the functions (and so much was around them even when I didn't make any specific comment) but it should finally give an idea of all the mad knobs involved.

p.s. `CreateDeviceImpl` also has a `IsMaximizedWindowedModeEnabled{RequiresMaximizedWindowedMode}` and `RequiresSwapEffectUpgrade` thingy but they both end up relying on the usual functions lied down above.
