### ISSUE TITLE
Thief Gold and Thief 2: The Metal Age (issue)

### ISSUE THREAD

**Issue by Sergiut99** [narzoul/DDrawCompat#272]
Hello developer.  I've tested your ddraw.dll many times and it always shows excellent results in older games. Friezes and microlags simply disappeared in games!

But I encountered a serious problem with friezes and microlags in the legendary classic stealth games: Thief Gold and Thief 2. The modern patch 1.27 for these games turned out to be useless. Unable to find and contact the engine developer for fixing patch. I did hundreds of tests and spent a whole month trying to fix the problem through the game config. But I couldn't do anything, because I'm not a programmer
Here in this topic I described the problem in detail. The game runs on DirectX6 and DirectX9
https://www.ttlg.com/forums/showthread.php?t=152466

https://youtu.be/Oiuv6PtiNrs

Maybe it is possible to create ddraw.dll for this game.

**Comment by BEENNath58** [comment]
> The game runs on DirectX6 and DirectX9

If I am not wrong, the T2fix updates changes the engine to use DirectX9, not supported by DDrawCompat.

If you use the original DX6 renderer, that is by removing T2fix, you'll need a lot more things to get the game running: single core affinity, registering LGVID.AX on every game run, 60FPS cap.

**Comment by Sergiut99** [comment]
Can you advise which of the programmers i can contact for help on github?
I know for sure, what causes the conflict is the original gen.osm file. the code in this file, as I understand it, runs various scripts in the game. For example, this file is necessary for the main character of the game to speak, once in a certain location of the game. 
Deleting this file breaks the game, but removes microlags and stuttering.

**Comment by Sergiut99** [comment]
Я отключил в игре DirectX9 через конфиг. Игра запустилась на одном ядре. Но проблема не ушла

[DDrawCompat-Thief2.log](https://github.com/narzoul/DDrawCompat/files/13773345/DDrawCompat-Thief2.log)

**Comment by BEENNath58** [comment]
I am not sure how the T2fix affects the game. 

I do the following for Thief 2:

Install the cd game. Update it to the newer version.
Hook DxWnd to it with fake fullscreen + vsync + single core process affinity
Register LGVID.AX
Add dgVoodoo2 to fix the stats issue in the first mission

**Comment by narzoul** [comment]
Is this still an issue with v0.5.2?
