### ISSUE TITLE
Report a visual problem about game The Sims 1.

### ISSUE THREAD

**Issue by star2056** [narzoul/DDrawCompat#275]
My OS : Win10 (22H2)
My Game : The Sims 1
My OS Language : Simplified Chinese

What is the Problem:
1. I download latest version of DDrawCompat v0.5.1 and put it in game folder.
2. Run The Sims 1
3. alt-tab back to windows, and then back to game, all fonts in game become little bit blur and little bit hard to read.
4. use shift+f11 and checking DisplayFilter option, but none of them made fonts clear.

Since the DDrawCompat works fine, technically there's no error log I could upload for you.
I solve the problem by using Sims1WidescreenPatcher, there is a DDrawCompat 0.4.0 in it.
that version works just fine, solving the "alt-tab glitch" and no blurring fonts.
I don't understand how DDrawCompat or Sims1WidescreenPatcher work so maybe other thing cause this?

**Comment by narzoul** [comment]
Is this still an issue with v0.5.2?

**Comment by star2056** [comment]
I don't know, I'm a gamer more than a geek, the 0.4.0 works fine to me, so I don't want to change anything.
Sorry about no more feedback.
