### ISSUE TITLE
Final Fantasy VIII PC 2000

### ISSUE THREAD

**Issue by AlfredoDore** [narzoul/DDrawCompat#277]
in Final Fantasy VIII from 2000 (my original game) there is an error where things are off screen, also if the 8bit textures could be corrected (this error does not occur on PCem VMs) it uses direct x 6, P.S: the bottom part of the screen looks normal, but it also has problems, both the top and the bottom have this problem with things outside the screen
![image](https://github.com/narzoul/DDrawCompat/assets/90729203/adfe4758-d7c5-462f-bc34-d13c601c6558)
![image](https://github.com/narzoul/DDrawCompat/assets/90729203/02688f5a-2d98-471b-a65e-5c620f6e8b8f)

**Comment by BEENNath58** [comment]
DDrawCompat has a setting for it. Enable it in the config file. Check the wiki for the required changes

**Comment by AlfredoDore** [comment]
> DDrawCompat has a setting for it. Enable it in the config file. Check the wiki for the required changes
which of these?
![image](https://github.com/narzoul/DDrawCompat/assets/90729203/e4eed4b5-583e-4368-a8e9-9efd28888eb4)

**Comment by narzoul** [comment]
PalettizedTextures=on

**Comment by narzoul** [comment]
This was only supposed to fix the palettized textures problem. Are you saying it's still not working?

The other problem is probably unrelated to palettized textures, but I didn't have time to investigate it yet.

**Comment by AlfredoDore** [comment]
> This was only supposed to fix the palettized textures problem. Are you saying it's still not working?
> 
> The other problem is probably unrelated to palettized textures, but I didn't have time to investigate it yet.

Yes, the use of video cards is linked to the game

**Comment by AlfredoDore** [comment]
> This was only supposed to fix the palettized textures problem. Are you saying it's still not working?
> 
> The other problem is probably unrelated to palettized textures, but I didn't have time to investigate it yet.

![image](https://github.com/narzoul/DDrawCompat/assets/90729203/ef144fb9-692d-4db4-8073-b4727bf58a83)
problem solved in the new version, I'll try it in more old games
