### ISSUE TITLE
Non functional menus in Red Alert 2 after a period of play

### ISSUE THREAD

**Issue by tore29** [narzoul/DDrawCompat#284]
Hi. Similar to Tiberian Sun there are issues with Red Alert 2. 

The reproducing the issue is similarly illusive. 
1. Start a skirmish game
2. Play a while
3. Open the pause menu until the scaling starts looking a bit off.
4. If you exit the game by yourself, by winning or losing the games will visually freeze. 

```
AltTabFix = keepvidmemp
ColorKeyMethod = auto
CpuAffinity = 1
CrashDump = mini
DesktopColorDepth = 16
DisplayFilter = point
DpiAwareness = permonitor
FpsLimiter = msgloop(120)
RenderColorDepth = app
SupportedDepthFormats = 16
SupportedResolutions = 640x480, 800x600, 1024x768
VSync = off
WinVersionLie = 98
```

**Comment by narzoul** [comment]
I'm closing this as a duplicate, since I assume this is the same issue as https://github.com/narzoul/DDrawCompat/issues/282, and the same fixes should apply. If this is not the case, feel free to reopen it.
