### ISSUE TITLE
Ace Ventura (1996) 

### ISSUE THREAD

**Issue by AlfredoDore** [narzoul/DDrawCompat#285]
None of the ddraw compacts work on it, however the game works with OTVDM, couldn't you make a compilation to make it work?
the game works almost correctly, but there are flaws in the sources and playing on w 11 without an emulator is much better than on the dosbox emulator, the game is faster and the sound quality is simply better, since I use the VST midi driver 
To play, I'm reducing my monitor's resolution to the maximum, but here in the print, I took it at 1920x1080 resolution and as you can see, there are errors in the fonts, certain writings don't appear
![image](https://github.com/narzoul/DDrawCompat/assets/90729203/ecfab673-400f-41a6-8b79-699e05912d8e)

**Comment by BEENNath58** [comment]
If the game works with Otvdm it's unlikely to use DDrawCompat as it's not a 16bit component

**Comment by AlfredoDore** [comment]
> If the game works with Otvdm it's unlikely to use DDrawCompat as it's not a 16bit component

Look, there is the launcher for the W 95, maybe this will solve the problems with fonts, it would be good to investigate

**Comment by BEENNath58** [comment]
> > If the game works with Otvdm it's unlikely to use DDrawCompat as it's not a 16bit component
> 
> Look, there is the launcher for the W 95, maybe this will solve the problems with fonts, it would be good to investigate

A Win3.1 port is more likely to use GDI or WinG in my opinion, over DirectDraw. Although I should not conclude that my assumptions is correct...

**Comment by narzoul** [comment]
> > If the game works with Otvdm it's unlikely to use DDrawCompat as it's not a 16bit component
> 
> Look, there is the launcher for the W 95, maybe this will solve the problems with fonts, it would be good to investigate

What launcher? The game is 16-bit, so it can't use DirectDraw. Is there a 32-bit version somewhere?

**Comment by narzoul** [comment]
I'm assuming the answer is no.

**Comment by AlfredoDore** [comment]
I managed to use it in Launch, which apparently converts to Direct X, but it has graphical problems, where it turns black but you can remove the black by moving the pointer
![Ace](https://github.com/user-attachments/assets/db822126-a734-4a92-a295-d911b15789cf)

**Comment by AlfredoDore** [comment]
case solved, if you want to run Ace Ventura, just set the launcher compatibility to Windows XP and set its resolution to 640x480 and that's it, without graphic errors and the best thing is that you don't need a PC emulator to emulate another system and play it
![image](https://github.com/user-attachments/assets/dc9a1745-e731-4c69-873d-d68e8e262520)
