### ISSUE TITLE
Steam version of C&C RA2 Yuri's Revenge freezes/pauses when entering Skirmish menu

### ISSUE THREAD

**Issue by Rampastring** [narzoul/DDrawCompat#288]
The Steam release of C&C RA2 + Yuri's Revenge includes DDrawCompat for compatibility.

In Yuri's Revenge the menus are somewhat laggy. In particular, entering the Skirmish menu freezes the game for about half a minute on my system, and there is also minor lag when changing the skirmish options (like adding more AIs, and changing their factions, colors, and teams).

In case system specs matter, I have Ryzen 7 5700X paired with a RTX 3060 Ti.

This is not a game bug, as the issue disappears if I replace DDrawCompat with other DirectDraw replacements, like cnc-ddraw.

**Comment by tore29** [comment]
Just want to add the delay to enter the skirmish menu is minimal on a machine of the games era (Pentium III) with Win98.

**Comment by narzoul** [comment]
Possible fix: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/14615001/ddraw.zip) ([diff.txt](https://github.com/narzoul/DDrawCompat/files/14615007/diff.txt) compared to v0.5.1)

**Comment by tore29** [comment]
Hey @narzoul,

I can confirm that this release fixes the long time to enter the skirmish menu.

I have not tested the menu issues with colour depth yet.

**Comment by tore29** [comment]
menu issues with DesktopColorDepth = 16 (and the issues Windows 16BitColor compat flag too) has been fixed.

Thanks :)

**Comment by narzoul** [comment]
Fixed in v0.5.2.
