### ISSUE TITLE
Limit FPS?

### ISSUE THREAD

**Issue by alb2001** [narzoul/DDrawCompat#29]
Hello

First of all, great work
Is there a way to limit the FPS of a game? Games like Blade Runner seem to work well (right speed) but if you check the FPS they are like 1500, causing an issue on the shooting gallery where the targets won't come up. Limiting the FPS using another wrapper seems to work.

Thanks

**Comment by narzoul** [comment]
If the game uses double or triple buffering, it may be possible in a later release via a config file (not planned for the next major release, but probably the one after it). For now you could try forcing v-sync on through your graphics driver settings.

Otherwise it's not really possible to tell when a frame starts/ends in a generic way, though it may be possible to guess it with some heuristics in some cases.

**Comment by albertocastillo2001** [comment]
Thank you!
Yes, I was aware of setting it using the graphics driver, but since an older wrapper made it possible I thought it could be added into yours. Keep up the great work

**Comment by elishacloud** [comment]
First of all thank for all the work you have done on this DDrawCompat tool!  It has helped me get several games working that I could not get working before.  The latest experimental version now works with  _Command & Conquer Tiberian Sun_.

However it runs way too fast with DDrawCompat.  When using [dgVoodoo](http://dege.freeweb.hu/) it runs at the right speed.  Also I can put a frame rate limiter on it using [DxWnd](https://sourceforge.net/projects/dxwnd/).  Both of these tools seem to have a generic frame rate limiter that works for most games.  The limiter in dgVoodo has worked for every game I tested, while DxWnd works on most games the limiter did not work on [Port Royale 2](https://www.gog.com/game/port_royale_2)

I would also love to see a frame rate limiter in DDrawCompat to fix some of these issues!

**Comment by narzoul** [comment]
I added an FpsLimiter setting in v0.4.0, but it probably still won't work in all cases. I'll try to improve upon it in cases where it doesn't work.
