### ISSUE TITLE
Sacred Gold Issue with Map Rendering.

### ISSUE THREAD

**Issue by BurningDalylight** [narzoul/DDrawCompat#290]
Hi, recently I applied ddrawcompat to Sacred Gold and I having a bit of issues, for some reason there are gaps and rendering issues with log book and mini map viewing, but those issues are from a new ddrawcompat version, the old one didn't have any of those issues.
I used ddrawcompat version from (https://github.com/narzoul/DDrawCompat/issues/149) and then new drrawcompat version 0.5.1
Case in point:
![pureHD-2024-03-16-21-33-38-80](https://github.com/narzoul/DDrawCompat/assets/155431995/59ba4918-4e96-4994-b016-adb8be1c1475)
![pureHD-2024-03-16-21-42-19-33](https://github.com/narzoul/DDrawCompat/assets/155431995/65528f16-20df-46fe-8743-8b61e6fe032d)
![pureHD-2024-03-16-21-34-07-39](https://github.com/narzoul/DDrawCompat/assets/155431995/901a9d9d-7ff3-4ef3-8a86-140bbe2502b0)
![pureHD-2024-03-16-21-42-52-00](https://github.com/narzoul/DDrawCompat/assets/155431995/add83dfe-9457-4fad-afa6-cad751112c2d)
[DDrawCompat-pureHD.log](https://github.com/narzoul/DDrawCompat/files/14625143/DDrawCompat-pureHD.log)
[DDrawCompat-pureHD0.5.1.log](https://github.com/narzoul/DDrawCompat/files/14625144/DDrawCompat-pureHD0.5.1.log)
I think it may do with display, but hardly, I use Windows 7 plus I play with PureHD mod and I use 1368x768. I didn't have the problem with old version, it's the new that have issues.

**Comment by narzoul** [comment]
Fixed in v0.5.2. I only tested the unmodded GOG version, but it had similar issues, so I assume it will fix the modded one too. If not, reopen it.
