### ISSUE TITLE
The Settlers 3 History Edition, Black Screen when playing intro or other videos 

### ISSUE THREAD

**Issue by groggrogy0** [narzoul/DDrawCompat#297]
I have Ubisoft Connect version of Settlers 3 History Edition running on Windows 10
I tried DDrawCompat v0.5.1, but when game start its show black screen.

I wanted to use DDrawCompat v0.5.1 to customize settings, but in both cases with default settings and customized ones, the videos show black screen when played. You can still hear audio playing though.

The Settlers 3 History Edition comes with its own small ddraw.dll wrapper on which videos work fine. But I wish to use DDrawCompat v0.5.1 to customize settings.

**Comment by narzoul** [comment]
Is this still an issue with v0.5.2? I only have the GOG version, but it didn't have problems with the video even with v0.5.1.

**Comment by groggrogy0** [comment]
Yes, the problem still exits in 0.5.2, but now the game crashes (exits) after video playback. 
There is black screen during video playback (sound only), then few seconds of black screen, then game's main menu flashes briefly and game exits to desktop.

Basically, same as here: https://github.com/narzoul/DDrawCompat/issues/302

**Comment by narzoul** [comment]
Please check if the patched version here fixes either the crash or the intro videos: https://github.com/narzoul/DDrawCompat/issues/299#issuecomment-2094226964

If not, please upload the debug logs with it (set LogLevel=debug in DDrawCompat.ini).

**Comment by narzoul** [comment]
Is it any better with v0.5.3?
