### ISSUE TITLE
Sacred Gold New Issues

### ISSUE THREAD

**Issue by ghost** [narzoul/DDrawCompat#300]
Hi, thanks everything is working fine but couple of new problems arises:
1.ResolutionScarle option in menu is broken whenever I go up/down with App(1) or Display(1) settings the graphic artifacts starts to appear like characters disappear/appearing suddenly,even crashing the game and combine with DisplayFilter = bilinear(100) it will look something like this:
![20240422_140215](https://github.com/narzoul/DDrawCompat/assets/155431995/dd8e52cc-5b9c-4061-b3ab-945067acdd41)
It only effects loading screen  and characters.
2. By choosing RenderColorDepth 32 characters shadows bug out, doesn't happen with old version.
![pureHD-2024-04-22-12-53-11-17](https://github.com/narzoul/DDrawCompat/assets/155431995/f5a270a4-68ab-441d-b870-78cf334b96dc)
![pureHD-2024-04-22-12-53-31-02](https://github.com/narzoul/DDrawCompat/assets/155431995/afd9a6fe-ea26-4464-b0a8-44481951a2ab)
3.Also minimap is bugging when choosing dwarf class, doesn't happen with others characters, side note it only cause issues with fog of war enable not if it's transparent.
![pureHD-2024-04-22-13-13-55-53](https://github.com/narzoul/DDrawCompat/assets/155431995/6e453b76-8b43-4937-9262-e423c246a69a) 
[DDrawCompat-pureHD.log](https://github.com/narzoul/DDrawCompat/files/15062242/DDrawCompat-pureHD.log)
P.S. Pure HD is mod for Sacred Gold Edition, basically making playable in widescreen and you can find at SacredGoldPcgamingwiki website, in case if you wonder why there is PureHD Log.

**Comment by narzoul** [comment]
I cannot reproduce the first 2 issues. Can you give some more info on how to reproduce them? What are your settings for DDrawCompat and Sacred (Settings.cfg)? Are these issues also present if you don't use the overlay? What if you don't use pureHD? By "characters" do you mean player models or text?

The last one I can reproduce, assuming you mean the transparent triangle at the bottom of the map. But that looks the exact same without DDrawCompat too. Are you sure it's not just a bug in the game? Do you have any evidence that it didn't always look that way?

**Comment by narzoul** [comment]
> Second issues is happening due to DepthFormat if I go say 16 or 32, then the issues with shadow occurs, if choosing 24, then there's no issue whatsoever.

Ok, you initially wrote RenderColorDepth, that's why I couldn't reproduce it.

The game uses stencil buffers for the shadows (and maybe other things), which is only available with 24 bit depth formats. So both 16 and 32 bit depth buffers will break stencil buffering effects. There's nothing that can be done about it. There shouldn't be any need to tinker with this setting anyway.
