### ISSUE TITLE
Rich4 DDrawCompat-v0.5.2 displays a black screen and crashes

### ISSUE THREAD

**Issue by horxd33** [narzoul/DDrawCompat#302]
Problem Description

1. You can enter the game, there is sound, but the screen is black
In the DDrawCompat-v0.5.2-debug-previous-builds version

v0.5.1-6-g45d755cb (can enter the game normally)

v0.5.1-7-g7f7cfcf9 (this version starts to display a black screen)

2. Crash when opening the game but not entering the game screen
In DDrawCompat-v0.5.2 & DDrawCompat-v0.5.2-debug-previous-builds versions

v0.5.1-15-gc344ec34 (shows black screen, but no crash problem)

v0.5.1-16-gd5a89cad (This version started to crash)

DDrawCompat-v0.5.2 (also has crash problem)

The following are relevant logs
https://mega.nz/folder/wLRgFTAZ#kEZzw4DiAYGUOMMJ7OIi_w

1. You can enter the game, there is sound, but the screen is black
v0.5.1-6-g45d755cb (can enter the game normally)
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-6-g45d755cb).log
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-6-g45d755cb-debug_1).log
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-6-g45d755cb-debug_2).log

v0.5.1-7-g7f7cfcf9 (this version starts to display a black screen)
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-7-g7f7cfcf9).log
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-7-g7f7cfcf9-debug_1).log
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-7-g7f7cfcf9-debug_2).log

2. Crash when opening the game but not entering the game screen
v0.5.1-15-gc344ec34 (shows black screen, but no crash problem)
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-15-gc344ec34).log
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-15-gc344ec34-debug_1).log
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-15-gc344ec34-debug_2).log

v0.5.1-16-gd5a89cad (This version started to crash)
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-16-gd5a89cad).log
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-16-gd5a89cad-debug_Crash dump).dmp
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug-previous-builds_v0.5.1-16-gd5a89cad-debug_Crash dump).log

DDrawCompat-v0.5.2 (also has crash problem)
DDrawCompat-Rich4(DDrawCompat-v0.5.2).log
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug_Crash dump).dmp
DDrawCompat-Rich4(DDrawCompat-v0.5.2-debug_Crash dump).log

**Comment by narzoul** [comment]
Thanks for the report. Since it's the same issue as the other one, I'll close this one as a duplicate.

**Comment by narzoul** [comment]
Fixed in v0.5.3.
