### ISSUE TITLE
Sims 1 - When forcing ResolutionScale and using Alt+Tab, all 3D models will appear black, including UI

### ISSUE THREAD

**Issue by mrpenguinb** [narzoul/DDrawCompat#304]
The game looks so much better with Sims in high resolution! ❤ However it has this remaining issue ^^^
Can this be resolved in DDrawCompat? Or is it something else that can't be worked around?
Config used: 
```
SoftwareDevice=hal
PalettizedTextures=on
ResolutionScaleFilter=bilinear
ResolutionScale=2560x1440
```
When forcing ResolutionScale and Alt+Tab is performed, all 3D models will appear black, and the UI will disappear.

![Normal](https://github.com/narzoul/DDrawCompat/assets/13060086/97189a33-66b1-46eb-ba81-11df9662358d)

![Black](https://github.com/narzoul/DDrawCompat/assets/13060086/a03a57c2-16d4-48a0-9f69-c91b0306d2b7)

**Comment by narzoul** [comment]
Use [AltTabFix](https://github.com/narzoul/DDrawCompat/wiki/Configuration#alttabfix)=keepvidmem

**Comment by mrpenguinb** [comment]
> Use [AltTabFix](https://github.com/narzoul/DDrawCompat/wiki/Configuration#alttabfix)=keepvidmem

Whoops... keep forgetting that that is a configuration option in DDrawCompat. Thank you!
