### ISSUE TITLE
Program only runs in background on W11 Insider Dev Build 26120.461

### ISSUE THREAD

**Issue by OpenRift412** [narzoul/DDrawCompat#309]
When running a program that's using DDrawCompat, the window won't actually appear, nor will there be any sound. Looking in task manager, the process seems to appear under the "Background processes" section. I've tested this with multiple games and get the same result.

I know this is a bit impractical to be submitting a bug from an Insider build, but this has happened before with dgVoodoo where certain games were having issues with it in Beta builds, Microsoft didn't bother fixing it, so after several months, problem finally exists in the main release build and _then_ they fixed it. I think it would be wise to at least fire up a VM with said version or something to have a look and see if anything could be done ahead of time.

**Comment by narzoul** [comment]
I explicitly put in the [README](https://github.com/narzoul/DDrawCompat?tab=readme-ov-file#support) that Insider builds are not supported. Neither are VMs. If and when it shows up in an actual release, I'll look into it.

**Comment by OpenRift412** [comment]
@narzoul 

So today I installed the 24H2 update on my laptop in the Release Preview Channel, which is an update that's already fully out for new ARM devices this month from what I'm reading online. I don't know if that makes it more relevant to you, but I thought I'd let you know. 

I suspect it may have something to do with the directdraw version that's included in the System32 folder, as it's now the same version that my main desktop (that was originally having the problem in the dev channel) is running. 

The ddraw version in question is dated April 1st 2024, is 616 KB, and is version number 10.0.26100.1.

Before my laptop took the update, the file had the same date and version number, but was 527 KB. With this version, games seemed to start up just fine.

**Comment by narzoul** [comment]
I don't have any ARM devices. Even if I did, I doubt DDrawCompat would work on them at all.

Is there any indication in debug logs about where the problem is?

**Comment by OpenRift412** [comment]
Here's a test with the Steam version of Command & Conquer using 0.5.2. I can't see anything particularly wrong, but maybe you'll see something I don't?

[DDrawCompat-C&C95.log](https://github.com/user-attachments/files/15946561/DDrawCompat-C.C95.log)

**Comment by narzoul** [comment]
The log is cut off at an odd place, for one. But more importantly, those aren't debug logs.

Please set LogLevel=debug, and maybe also CrashDump=full in DDrawCompat.ini. In case this produces a dmp file, attach that too, along with the log.

**Comment by OpenRift412** [comment]
> The log is cut off at an odd place, for one. But more importantly, those aren't debug logs.
> 
> Please set LogLevel=debug, and maybe also CrashDump=full in DDrawCompat.ini. In case this produces a dmp file, attach that too, along with the log.
> 
> Edit: if it doesn't crash automatically, please save a crash dump from Task Manager instead.

I created a memory dump, as it was called in Task Manager. Here's the dump and debug log:
[C&C95_dump.zip](https://github.com/user-attachments/files/15948391/C.C95_dump.zip)
[DDrawCompat-C&C95.log](https://github.com/user-attachments/files/15948392/DDrawCompat-C.C95.log)

**Comment by narzoul** [comment]
Thanks! It's some problem with dbgeng again. I got rid of that dependency already, so the next release might actually fix this.

**Comment by Squall-Leonhart** [comment]
> I don't have any ARM devices. Even if I did, I doubt DDrawCompat would work on them at all.
> 
> Is there any indication in debug logs about where the problem is?

Windows for ARM has full x86 compatibility, but ddi support for anything dx9 and older will be served by 9on12, which has lot of issues.

**Comment by narzoul** [comment]
Is it any better with v0.5.3 now?

**Comment by OpenRift412** [comment]
> Is it any better with v0.5.3 now?

Yep, it works! Thank you!
