### ISSUE TITLE
Dune 2000 graphic issue

### ISSUE THREAD

**Issue by Shaokhan65** [narzoul/DDrawCompat#31]
Hi,

when I use your ddraw.dll along with Dune 2000, I get [this](https://gyazo.com/313212f14b1dd87f71df1d058e103eba) when I run it.

It is similar to [what happens](https://gyazo.com/50ec333927c1e503cc8307871d61b27e) when I alt tab and tab back on Windows 10 (I think it also does on 8, but certainly this does not happen on W7):

And [this](https://gyazo.com/ec1d2dedee6b09fd94b20366c5b9d295) is what it should look like.

After some testing with the Compatibility Fixes I found out I can replicate the same problem by turning on AliasDXDC. [This](https://gyazo.com/de9766fab9140f4331a56ae4e4078441) is what it does.

Also my friend has Mac, when he uses this ddraw.dll, his Alt key stops working properly for some reason.

Can you advise what I can do to avoid these problems with your ddraw.dll?

**Comment by elishacloud** [comment]
@Shaokhan65, I have been working on a project called [dxwrapper](https://github.com/elishacloud/dxwrapper) that can convert DirectDraw to Direct3D9.  The latest updates seem to work with Dune 2000.

You can download the update here: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/3365382/ddraw.zip)

Just unzip the files into the Dune 2000 folder overwriting any existing file.

_Note: in some cases you may need to reboot the computer before you can run Dune 2000._

**Comment by narzoul** [comment]
I can't reproduce this with the latest experimental release. I assume it's been fixed already. If it's not the case. please reopen this.
