### ISSUE TITLE
I've got some balls (1999)

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#310]
The free game is available here: https://www.jonneweb.net/pelit/file/580/i've-got-some-balls/#google_vignette

The game seems to crash after a SetTexture call. On Windows XP, it doesn't occur. I tested it on Windows 7, Windows 10 and Windows 11 and it crashes everywhere

**Comment by narzoul** [comment]
Yeah, I remember wasting some time trying to debug it a few years ago, and I wasted some more time now. I'm positive the game is just corrupting memory left and right, and it's nearly impossible to track down where it begins. But I'm sure it has nothing to do with DDrawCompat, so I'm not going to waste more time on it.

**Comment by BEENNath58** [comment]
In case you are interested in playing this game, or somebody wants to enjoy it, here's a remake: https://github.com/thefinalcutbg/IveGotSomeBalls
