### ISSUE TITLE
The learning company works with 8+ but vista+ failed thru vmware player.

### ISSUE THREAD

**Issue by MicahMoo11** [narzoul/DDrawCompat#311]
I am a private community with other 22 people who are trying to remaster the learning company by unofficial modified software concerns, back in the day our community was at archive.org. But we were banned due to people saying that we were giving people viruses. but in reality, it was vastly different than the originals. Due to some catalog is modified software. but our 22 people here are editors, Even expanding.

VMware Tools 12 adds support for WDM 1.2.
Also known as VMware Player 17. Which fixes your code for DDrawCompat v0.5.2. Although it breaks clue finders 0.5.1 works. Sadly you made it clear from this response that running Windows in any sort of virtualized/emulated environment, e.g. in a virtual machine or through Wine

How is this related, sadly from this link https://docs.vmware.com/en/VMware-Tools/12.4.0/rn/vmware-tools-1240-release-notes/index.html

This is the last 32-bit Windows even 64-bit Windows 7. After that drivers it will be frozen. So as a community even though I'm the owner, those drivers probably are working with over 400 learning company games. They work today with Windows 8+. But for some reason vista and 7 do not launch through VMware Player. We expect wide 1.0 and 1.1 issues. We were thinking of adding your .dll to all of our projects but. I feel uncomfortable as we have to make two separate packages for Vista+ and 8+ which will cripple our development or significantly delay our remastering for 4 years. As for DirectDraw, your code is the most stable with our code. We saw 4 years ago that DirectDraw from Windows 9 series VS Vista-11 are quite different that is why deterioration with old games that rely upon DirectDraw might happen. We were trying to fix it without bandages until we found your software which fixes 80% of the issues.

If you do not want to fix VMware player bug. We will try other things. Please consider.

**Comment by narzoul** [comment]
Not supported means not supported. No exceptions.

**Comment by MicahMoo11** [comment]
Last response, I as an owner i fully understand they might be technical limitations thru vmware. Back in the day, even I was running windows 11. But I stopped useing it due to iv seen that windows 7 was the last version that meantune very amount of compatibility with Microsoft. And with newer laptops cannot run even windowd 8.1. Without major issues or compromise. Although we did got 10th generation processes working but very unstable. (We still use it if vmware player fails us).

I still support windows 11 23h2, but I run Microsoft visual studio 2022 thru windows 7 64-bit. But games from the 90's can go so far. That is why we moved to Linux. As it is very unlikely for a remaster. Again thick you for atless reading it. Who knows maybe in the future, with some miracle, mightiv been fixed. I will look at this page years down the line, It had great potential.

Until than we will fixed the directdrew with our own custom patches. Even thru Microsoft is being quote difficult over the years with newer systems. 

If you read this which I dought, Thick you from Wright Micah.

**Comment by MicahMoo11** [comment]
Hello, all this might be my last point as of ddrawcompat, 0.6.0 now fully works with Windows Vista even RTM although GDI is fully broken unlike sp2+ may work.

When I 1st made this post to find a developer the fix TLC, sadly all wrappers were fully broken. Even dxwrapper was the last in the party https://github.com/elishacloud/dxwrapper/releases/tag/v1.2.7500.25 also works. The thing is even at the time DDrawCompat v0.5.1. Nobody with Intel, AMD, and NVIDIA got it to work with Vista. At that time, I came into the picture tested the virtualized/emulated environment 5 and found out that only Windows 8+ worked. Windows Vista that nobody got to work. Windows 7 was unstable with very old hardware. That is why I made the post to fix TLC and for Narzoul to investigate what is going on with wddm 1.0 & 1.1 vs wddm 1.2. for me it was best as FunkyFr3sh came to the post, https://github.com/FunkyFr3sh/cnc-ddraw/issues/316, and later on I made this site below https://github.com/FunkyFr3sh/cnc-ddraw/issues/327

My only trust is TLC. That other post is a proxy to my other communities. With very problematic games, even FunkyFr3sh is fully fixed except for 2 based on oversight on my end. Others, like Dr. Seuss, are somewhat stable.

I only tested 
Carmen Sandiego ThinkQuick (bugged GDI) but fully works with ddrawcompat.
& Dr. Seuss(TM) Kindergarten yes? But advised Windows 7 for GDI salability

Buzz Lightyear of Star Command and Toy Story 2. There is no working wrapper at this time. The closest at this time is wined3d, and recently, ddrawcmpat 0.6.0 is starting to work but not as great as wined3d.

[DDrawCompat Disney Vista tests.zip](https://github.com/user-attachments/files/19452758/DDrawCompat.Disney.Vista.tests.zip)

[DDrawCompat (TLC) Vista tests.zip](https://github.com/user-attachments/files/19452761/DDrawCompat.TLC.Vista.tests.zip)

My point of view is this https://github.com/FunkyFr3sh/cnc-ddraw/issues/316#issuecomment-2588189853 (it’s old but still relevert now). I'm happy that Windows Vista was fully fixed. Sadly, I will never fully trust this developer. A lot of people pointed out that if you wanted Natzoul to fix Windows Vista. You should say that ddrawcompat starting 0.4.0 and above is fully broken. Then what you did at the original post was messy and confusion for what you're trying to accomplish. For that, it was somewhat my fault. However FunkyFR3sh 1st comment was “I'm not sure if this is spam or a bad translation - Please post this again without translation and I'll translate on my own”. The key difference is this developer never just close GitHub. That is how yikes the original post was. I advise all people to look even at dx-wrapper, as yes it has low computers with games. But ddrawcompat is quite customable, even with older handwear mostly GDI that even ddrawcmpat 0.6.0 is yikes. 

Sadly Jecub R community has to GitHub narzoul themselves to figure out what’s up. Even than this developer might not fix it due to the extended Kernal side of things. Again, narzoul thinks for the Windows Vista fix. Despite my trust issues.
