### ISSUE TITLE
sonic world dx shows a black screen in 0.5.2

### ISSUE THREAD

**Issue by yeeevan** [narzoul/DDrawCompat#312]
sonic world dx (a sonic fan game that uses blitz3d as its engine) shows a black screen in 0.5.2 but still seems to be playable since i can hear in game sound. 0.5.1 plays normally

GPU: GTX 1660 Ti

Windows version: 10, 21H2

log:
[DDrawCompat-Sonic World DX.log](https://github.com/narzoul/DDrawCompat/files/15282650/DDrawCompat-Sonic.World.DX.log)

**Comment by narzoul** [comment]
This should fix it: https://github.com/narzoul/DDrawCompat/issues/298#issuecomment-2094362559

**Comment by yeeevan** [comment]
it does! thank you!

**Comment by narzoul** [comment]
Fixed in v0.5.3.

**Comment by narzoul** [comment]
First, don't use "that ddraw.zip" (I'm assuming you're referring to the attached version in the link above). Use the latest release:
https://github.com/narzoul/DDrawCompat/releases

If it doesn't work with that either, please attach debug logs (LogLevel=debug in DDrawCompat.ini).
It would be better to open a separate issue for it, though.

**Comment by Wetzel402** [comment]
[DDrawCompat-Sonic World DX.log](https://github.com/user-attachments/files/26167008/DDrawCompat-Sonic.World.DX.log)

I'm having trouble getting this to work also. I get a black windows and never further. Currently running Sonic World DX 1.2.4 on Windows 11. Is there something specific you did in your config file to get it working?

Thanks!

**Comment by narzoul** [comment]
@Wetzel402 It looks like it was broken by 1075bb3f3e69401d04727849899b349e47b46acf.

This small patch fixes it for me, does it work for you?
[ddraw.zip](https://github.com/user-attachments/files/26168003/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/26168004/diff.txt) compared to v0.7.1)

Later the game crashes now with a memory access violation after the first logo screen, but now it happens even with v0.5.3 and it doesn't seem related to DDrawCompat. It also worked when I tested it a few minutes ago, I'm not sure what changed, but it looks more like a random crash in the game...

**Comment by Wetzel402** [comment]
Memory access violation is well documented by the Sonic World team so I'm sure it's related to the game and not DDrawCompat. Someone on the discord recommended using [Magpie](https://github.com/Blinue/Magpie) which fixes my problem.

**Comment by narzoul** [comment]
Does this mean that the patch I posted above didn't solve the black window problem either? Or it now gets past the black window and crashes after the logo like for me?

**Comment by Wetzel402** [comment]
I didn't give the patch a try. I assumed it was added to mainline DDrawCompat and that I had it already.
