### ISSUE TITLE
Issues with Command & Conquer: Tiberian Sun

### ISSUE THREAD

**Issue by S4rafan** [narzoul/DDrawCompat#314]
Hello,

First of all I want to thank you for the wonderful wrapper. It solves issues that even dgVoodoo2 wasn't able to solve. I'm aware that some issues are normal when you're using such tools, but I decided to share my experiences with Tiberian Sun.

The Steam version of the game is bundled with the 0.5.1 version of DDrawCompat. It works very good in fullscreen, especially if you modify a few settings. However I decided to run Tiberian Sun in windowed mode to take advantage of Lossless Scaling tool (I want to upscale 1280x720 resolution to 1920x1080). This is where I've encountered some issues. After playing the game in windowed mode for a few minutes the wrapper expands the game menu horizontally (the one visible after hitting Escape) and messes up the save and load game list. This makes the particular save entries either invisible or crashes whole menu completely (it disappears and you're unable to select anything). In fullscreen everything is fine, but I can't use Lossless Scaling for obvious reasons.

Of course I decided to tinker a little. I tried to use the newest version of DDrawCompat (0.5.2). This one doesn't mess the menu accessible during gameplay, but freezes the main menu screen visible after launching the game. It's still possible to select the appropriate options using Alt+Tab and hovering the mouse cursor around frozen image, so it's not a gamebreaking bug. The menu during gameplay works without any issues on this version.

I want to emphasize that the issues I'm experiencing aren't correlated with Lossless Scaling, because they appear also when scaling is disabled. I would be grateful if you could look into these issues. For now I'll stick to the newest version and use Lossless Scaling.

Best regards,
Sarafan

**Comment by narzoul** [comment]
Windowed mode being broken in 0.5.2 is a known issue. Until the next release, you can try the temporary fix here:
https://github.com/narzoul/DDrawCompat/issues/298#issuecomment-2094362559

**Comment by S4rafan** [comment]
Thank you, this worked perfectly. Now the main menu works without any freezes. Also there are no problems with menu and vanishing save entries when playing the game. :)

**Comment by narzoul** [comment]
Fixed in v0.5.3.
