### ISSUE TITLE
SurfaceRepository::getWindowedSrc crashes in v0.5.2 on integrated GPUs

### ISSUE THREAD

**Issue by CookiePLMonster** [narzoul/DDrawCompat#315]
We're encountering a regression in v0.5.2 compared to v0.5.1, where two PCs with integrated GPUs are now crashing on startup inside a `SurfaceRepository::getWindowedSrc` function. As far as I can tell, it's because `this`, and thus `g_primaryRepository`, is `nullptr`.

I received a crashdump from this issue. This session used a regular `v0.5.2-Release` build, so symbols will match:
[Buccaneer.exe.18456.dmp.zip](https://github.com/narzoul/DDrawCompat/files/15368882/Buccaneer.exe.18456.dmp.zip)

As far as I can tell, primary surface repository is something that has been added in v0.5.2, so perhaps this crash is indicative of a bug in this implementation.

**Comment by narzoul** [comment]
Sounds similar to another issue I've seen recently. See if this fixes it: https://github.com/narzoul/DDrawCompat/issues/299#issuecomment-2070885134

**Comment by CookiePLMonster** [comment]
Thank you! I forwarded this info to QA and also asked to include a DDrawCompat log together with the crash dump **if** this DLL doesn't help.

**Comment by CookiePLMonster** [comment]
@narzoul I got a confirmation from QA that this fix helps and it does not regress the other configurations previously unaffected by this bug, thank you 🙂

We are going to ship with a self-compiled v0.5.2 + this fix with an appropriate version bump to 0.5.2.1, since I need to also store the corresponding the PDB of this `ddraw.dll` and thus I can't just use your test DLL.

**Comment by narzoul** [comment]
Fixed in v0.5.3.
