### ISSUE TITLE
Command and Conquer Gold & Red Alert have scroll speed too fast

### ISSUE THREAD

**Issue by raptor264** [narzoul/DDrawCompat#321]
The game works very well with DDrawCompat... in fact it does not crash but the mouse speed is too fast and the ddraw.ini in the game folder does not respond to the new ddraw.dll provided in addition to changing said setting to slower within the game is not enough.

**Comment by narzoul** [comment]
I don't know what is ddraw.ini, but DDrawCompat doesn't use it. It must be some leftover of a previous DirectDraw wrapper you were using, so there is no point in editing it when using DDrawCompat.

You need to limit the FPS using the FpsLimiter=msgloop setting of DDrawCompat. You can experiment with it also in-game by pressing Shift-F11. Read the [Configuration wiki](https://github.com/narzoul/DDrawCompat/wiki/Configuration) for details.

**Comment by raptor264** [comment]
Yes. What you told me completely resolved it. It works 100%. With this, c&c gold, red alert, red alert 2 +expansion and tiberian sun+ expansion games are fully functional without errors or glitches.
