### ISSUE TITLE
Jane's Fighters Anthology crashes

### ISSUE THREAD

**Issue by raptor264** [narzoul/DDrawCompat#322]
After a normal installation and applying the official patch 1.02... the game in the menus works but when loading a mission or wanting to see a plane in references it directly crashes. If I don't apply the patch and leave it as it is, the game also crashes with or without DDrawCompat. I am using compatibility mode as well.

**Comment by narzoul** [comment]
The game works fine without any compatibility modes for me, with or without the patch, and with or without DDrawCompat. It's recommended to use ThreadPriorityBoost=on for DDrawCompat to fix the stuttery cursor issue.

The game's entirely software rendered with very basic use of DirectDraw, so I think your crash is unlikely to be related to ddraw, but let's check anyway. Please set CrashDump=full and LogLevel=debug in DDrawCompat.ini, reproduce the crash (e.g. with Create Quick Mission), then compress and upload the DDrawCompat log file and dmp file.

**Comment by raptor264** [comment]
here it is... what's the problem? I really don't know what it is because it happens even before having DDrawCompat in the game directory. https://drive.google.com/file/d/1ytTVwiL15EVYelfOQyacP5yMOpXZ_Nys/view?usp=sharing

**Comment by narzoul** [comment]
Based on your crash dump, it crashes when FA.exe is trying to execute code from a memory area outside of the executable file or any of its loaded modules. So it may be a DEP ([Data Execution Prevention](https://support.microsoft.com/en-us/topic/what-is-data-execution-prevention-dep-60dabc2b-90db-45fc-9b18-512419135817)) issue. You can try to enable the DisableNX shim for FA.exe in Compatibility Administrator to see if it fixes it.

I wonder why it's not an issue for me, even though according to my Windows Security settings, DEP is set to "Use default (On)".

**Comment by raptor264** [comment]
The game works at 99.99% due to the supposed lack of multiplayer. I put some fixes and other things on it, it practically comes back to life in its entirety along with its respective manual. Thank you very much friend, thanks to DisableNX I can enjoy a classic. You are a genius and I learned many new things that I applied to other programs thanks to you. thank you so much.
