### ISSUE TITLE
Clock Tower

### ISSUE THREAD

**Issue by AlfredoDore** [narzoul/DDrawCompat#323]
The game works, but I can't put it in full screen

**Comment by narzoul** [comment]
As far as I understand it's a windowed-only game, it doesn't have a fullscreen mode. DDrawCompat doesn't have any features to display windowed applications in fullscreen mode or vice versa, and it's unlikely to have them in the near future, if ever.

There are better tools for this, such as DxWnd. There are instructions on how to set it up at [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Clock_Tower#Borderless_fullscreen_windowed). Alternatively, you can ask for help on DxWnd forums, there seems to be a topic for this game already here: https://sourceforge.net/p/dxwnd/discussion/general/thread/d900d059/
