### ISSUE TITLE
Figthers Anthology Out of Memory error and others

### ISSUE THREAD

**Issue by raptor264** [narzoul/DDrawCompat#326]
It is supposed to be a common bug in the game and it happens after spending a long time in the game, even with DDrawCompat. Is there a way or any shim that can be applied to fix this error? should I use 4gb_patch? Is there a shim or something to improve multiplayer other than with the application to patch Aguada? Do you know of other fixes for this game even in sound?.

**Comment by narzoul** [comment]
I don't know. Please don't use this place as a generic tech support forum for all things unrelated to DirectDraw. There are better places for such discussions, such as [Vogons](https://www.vogons.org).
