### ISSUE TITLE
0.5.2 Regression; not working at all

### ISSUE THREAD

**Issue by PlayNeth** [narzoul/DDrawCompat#329]
Got myself a new laptop recently and haven't had the best of luck with the latest version, none of the games I've tested work, they just instant close upon boot.

0.5.1 Seems to be working perfectly on this thing though.

Here's a log from a random game:
[DDrawCompat-nerf.log](https://github.com/user-attachments/files/15843510/DDrawCompat-nerf.log)

Laptop specs:
CPU: Celeron n4020
GPU: UHD 600
OS: Windows 10 21H2

**Comment by narzoul** [comment]
Use the fix here: https://github.com/narzoul/DDrawCompat/issues/299#issuecomment-2070885134

Closing this as a duplicate. Reopen if it doesn't fix the issue.
