### ISSUE TITLE
Rogue Spear alt tab black screen

### ISSUE THREAD

**Issue by Volcanotron** [narzoul/DDrawCompat#332]
hello again narzoul, I don't remember if we talked about how to fix the alt tab black screen in fullscreen mode or not.

loading into the level is fine but if you alt tab in fullscreen mode the viewing area goes black but it still keeps the bar at the bottom viewable. exiting back to the menu and re-entering the level again fixes it which is okay for singleplayer but not good for the multiplayer in the event it happens to someone there.

this doesn't happen if i use window mode and put the program through "Borderless Gaming" to make it borderless fullscreen
also thanks for implementing a fps cap function into DDrawcompat its very helpful 

https://github.com/Codeusa/Borderless-Gaming
![Untitled](https://github.com/narzoul/DDrawCompat/assets/37210517/f23ca722-dd28-4413-9806-974eb0063d2b)

**Comment by narzoul** [comment]
Have you tried the [AltTabFix](https://github.com/narzoul/DDrawCompat/wiki/Configuration#alttabfix)=keepvidmem setting?

**Comment by Volcanotron** [comment]
alight that was a lot easier to fix than i was expecting, which is good thank you
i did need to add it to the DDrawCompatOverlay-RogueSpear  file
 located in AppData\Local\VirtualStore\Program Files (x86)\Red Storm Entertainment\Rogue Spear

 after a lot of confusion as to why things weren't working i finally got the hang of how it works. thanks a lot for all the work you do
