### ISSUE TITLE
An old Direct3D problem with Nocturne (plus Blair Witch Trilogy)

### ISSUE THREAD

**Issue by Zerodarkage** [narzoul/DDrawCompat#336]
![image](https://github.com/narzoul/DDrawCompat/assets/26642587/a130d326-d68a-4d00-8bb2-43eab1293a9c)
Using Direct 3D mode causes this anomaly on some parts of the 4 games. I don't have a clue why...
It's like some effect is not working correctly. Some levels the char disappears completely...

Any way to fix that with an option or do you need the debug log?

**Comment by narzoul** [comment]
Do you have a save game or some instructions on how to quickly reproduce the issue?

**Comment by Zerodarkage** [comment]
> Do you have a save game or some instructions on how to quickly reproduce the issue?

[BUG.zip](https://github.com/user-attachments/files/16082222/BUG.zip)
Unzip in Save folder

or

Start 
Choose Volume 2 - Tomb of the Underground God
Press ESC and choose the option to skip cutscene 
Start walking south
Next screen kill the first enemy
Next is the screen of the screenshot
Just walk on the right side o the train

**Comment by Zerodarkage** [comment]
![image](https://github.com/narzoul/DDrawCompat/assets/26642587/2b41cb75-ff06-430b-894d-6f5be22a6dc9)
[BW2_BUG.zip](https://github.com/user-attachments/files/16082812/BW2_BUG.zip)
Unzip in Save folder

Another example of the bug in Blair Witch Volume Two - The Legend of Coffin Rock

**Comment by Zerodarkage** [comment]
![image](https://github.com/narzoul/DDrawCompat/assets/26642587/cd9835b2-ec9c-4e24-b9dd-12e7bc1588e5)
I found something interesting! The bug does not happen in DDrawCompat-v0.3.0!

**Comment by narzoul** [comment]
Thanks, I can reproduce the issue with your save game. I was worried it was going to be specific to old Intel GPU drivers, but luckily that doesn't seem to be the case. I'll try to figure it out.

**Comment by narzoul** [comment]
This should fix it: [ddraw.zip](https://github.com/user-attachments/files/16216350/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/16216351/diff.txt) compared to v0.5.3)

**Comment by Zerodarkage** [comment]
> This should fix it: [ddraw.zip](https://github.com/user-attachments/files/16216350/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/16216351/diff.txt) compared to v0.5.3)

Yes!!! It's fixed!!! Thank You Very Much!!!

**Comment by Zerodarkage** [comment]
Do you think any compatibility mode option is needed for Nocturne and Blair Witch Trilogy??? (I did some tests and seems to run fine without any of them)

**Comment by narzoul** [comment]
If it runs fine, then no.

**Comment by narzoul** [comment]
Fixed in v0.5.4.
