### ISSUE TITLE
Doom 95 news wad oficial Doom I+II

### ISSUE THREAD

**Issue by AlfredoDore** [narzoul/DDrawCompat#345]
Some wads in the new version work perfectly, while others don't. I even found a wad that leaves the screen at 16:9. Wouldn't it be possible to fix this in DDRAW?
![image](https://github.com/user-attachments/assets/e7027c5a-e24b-4b05-8a00-d86dd7c7920c)

**Comment by narzoul** [comment]
This game doesn't use DirectDraw.
