### ISSUE TITLE
Virtual Pool 3 crashes on startup

### ISSUE THREAD

**Issue by mackdle** [narzoul/DDrawCompat#346]
Log:

00:11:09.688 Process path: C:\VP3\vp3.exe
00:11:09.688 Loading DDrawCompat dynamically from C:\VP3\DDRAW.dll
00:11:09.688 Environment variable __COMPAT_LAYER = ""
00:11:09.688 Loading global config file: C:\ProgramData\DDrawCompat\DDrawCompat.ini
00:11:09.688   File not found, skipping
00:11:09.688 Loading user config file: C:\Users\Parker\AppData\Local\DDrawCompat\DDrawCompat.ini
00:11:09.688   File not found, skipping
00:11:09.688 Loading directory config file: C:\VP3\DDrawCompat.ini
00:11:09.688   File not found, skipping
00:11:09.688 Loading process config file: C:\VP3\DDrawCompat-vp3.ini
00:11:09.688   File not found, skipping
00:11:09.688 Loading overlay config file: C:\VP3\DDrawCompatOverlay-vp3.ini
00:11:09.688   File not found, skipping
00:11:09.688 Final configuration:
00:11:09.688   [default] AlignSysMemSurfaces     = on
00:11:09.688   [default] AltTabFix               = off
00:11:09.688   [default] AlternatePixelCenter    = off
00:11:09.688   [default] Antialiasing            = off
00:11:09.688   [default] BltFilter               = point
00:11:09.688   [default] ColorKeyMethod          = auto
00:11:09.688   [default] ConfigHotKey            = shift+f11
00:11:09.688   [default] ConfigRows              = allrw, allro
00:11:09.688   [default] ConfigTransparency      = alpha(90)
00:11:09.688   [default] CpuAffinity             = 1
00:11:09.688   [default] CpuAffinityRotation     = on
00:11:09.688   [default] CrashDump               = off
00:11:09.688   [default] DepthFormat             = app
00:11:09.688   [default] DesktopColorDepth       = initial
00:11:09.688   [default] DesktopResolution       = desktop
00:11:09.688   [default] DisplayAspectRatio      = app
00:11:09.688   [default] DisplayFilter           = bilinear(0)
00:11:09.688   [default] DisplayRefreshRate      = app
00:11:09.688   [default] DisplayResolution       = desktop
00:11:09.688   [default] DpiAwareness            = permonitor
00:11:09.688   [default] FontAntialiasing        = app
00:11:09.688   [default] ForceD3D9On12           = off
00:11:09.688   [default] FpsLimiter              = off
00:11:09.688   [default] FullscreenMode          = borderless
00:11:09.688   [default] GdiStretchBltMode       = app
00:11:09.688   [default] LogLevel                = info
00:11:09.688   [default] PalettizedTextures      = off
00:11:09.688   [default] RemoveBorders           = off
00:11:09.688   [default] RenderColorDepth        = 32
00:11:09.688   [default] ResolutionScale         = app(1)
00:11:09.688   [default] ResolutionScaleFilter   = point
00:11:09.688   [default] SoftwareDevice          = rgb
00:11:09.688   [default] SpriteDetection         = off
00:11:09.688   [default] SpriteFilter            = app
00:11:09.688   [default] SpriteTexCoord          = app
00:11:09.688   [default] StatsAggregateTime      = 3
00:11:09.688   [default] StatsColumns            = label, cur, avg, min, max
00:11:09.688   [default] StatsHotKey             = shift+f12
00:11:09.688   [default] StatsPosX               = right
00:11:09.688   [default] StatsPosY               = top
00:11:09.688   [default] StatsRows               = label, presentrate, fliprate, blitcount, lockcount
00:11:09.688   [default] StatsTransparency       = alpha(75)
00:11:09.688   [default] StatsUpdateRate         = 5
00:11:09.688   [default] SupportedDepthFormats   = all
00:11:09.688   [default] SupportedResolutions    = native, 640x480, 800x600, 1024x768
00:11:09.688   [default] SupportedTextureFormats = all
00:11:09.688   [default] SurfacePatches          = none
00:11:09.688   [default] TerminateHotKey         = ctrl+alt+end
00:11:09.688   [default] TextureFilter           = app
00:11:09.688   [default] ThreadPriorityBoost     = off
00:11:09.688   [default] VSync                   = app
00:11:09.688   [default] VertexBufferMemoryType  = sysmem
00:11:09.688   [default] VertexFixup             = gpu
00:11:09.688   [default] WinVersionLie           = off
00:11:09.690 Initial DPI awareness: unaware
00:11:09.690 DPI awareness was successfully changed to "permonitor" via SetProcessDpiAwarenessContext
00:11:09.690 Primary CPU group number: 0
00:11:09.690 Physical to logical CPU core mapping for efficiency class 1:
00:11:09.690   Physical core #1: 1, 2
00:11:09.690   Physical core #2: 3, 4
00:11:09.690   Physical core #3: 5, 6
00:11:09.690   Physical core #4: 7, 8
00:11:09.690   Physical core #5: 9, 10
00:11:09.690   Physical core #6: 11, 12
00:11:09.690   Physical core #7: 13, 14
00:11:09.690   Physical core #8: 15, 16
00:11:09.690 Physical to logical CPU core mapping for efficiency class 0:
00:11:09.690   Physical core #1: 17
00:11:09.690   Physical core #2: 18
00:11:09.690   Physical core #3: 19
00:11:09.690   Physical core #4: 20
00:11:09.690   Physical core #5: 21
00:11:09.690   Physical core #6: 22
00:11:09.690   Physical core #7: 23
00:11:09.690   Physical core #8: 24
00:11:09.690 Current CPU affinity: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24
00:11:09.690 Applying configured CPU affinity: 1
00:11:09.690 CPU affinity rotation is enabled
00:11:09.690 DDrawCompat loaded successfully
00:11:09.691 Installing display mode hooks
00:11:09.691 Installing registry hooks
00:11:09.691 Installing Direct3D driver hooks
00:11:09.694 Hooking user mode display driver: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_cc569e59ca39c5fe\nvldumd.dll+0x25960
00:11:09.727 Supported resource formats:
00:11:09.727   {D3DDDIFMT_X1R5G5B5,0x48e10f,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_A1R5G5B5,0xe007,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_A4R4G4B4,0xe007,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_R5G6B5,0x48ed0f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_X8R8G8B8,0x58ed0f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_A8R8G8B8,0x58e10f,0x8b,0x8b,0}
00:11:09.727   {FOURCC(NV12),0x4007000,0x0,0x0,12}
00:11:09.727   {FOURCC(444S),0x4007000,0x0,0x0,24}
00:11:09.727   {FOURCC(S410),0x4007000,0x0,0x0,16}
00:11:09.727   {FOURCC(P010),0x4007000,0x0,0x0,16}
00:11:09.727   {FOURCC(NV24),0x4007000,0x0,0x0,12}
00:11:09.727   {FOURCC(YV12),0x4007000,0x0,0x0,12}
00:11:09.727   {FOURCC(UYVY),0x4007000,0x0,0x0,16}
00:11:09.727   {FOURCC(YUY2),0x4007000,0x0,0x0,16}
00:11:09.727   {FOURCC(AI44),0x5000,0x0,0x0,8}
00:11:09.727   {FOURCC(AYUV),0x5000,0x0,0x0,32}
00:11:09.727   {FOURCC(AIP8),0x5000,0x0,0x0,8}
00:11:09.727   {FOURCC(AV12),0x5000,0x0,0x0,12}
00:11:09.727   {FOURCC(PLFF),0x4000,0x0,0x0,0}
00:11:09.727   {FOURCC(NVMD),0x4000,0x0,0x0,0}
00:11:09.727   {FOURCC(NVDP),0x4000,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_A8P8,0x5000,0x0,0x0,16}
00:11:09.727   {D3DDDIFMT_R8,0x40400f,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_G8R8,0xd,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_V8U8,0x10001,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_X8L8V8U8,0x10001,0x0,0x0,0}
00:11:09.727   {FOURCC(DXT1),0x8007,0x0,0x0,0}
00:11:09.727   {FOURCC(DXT2),0x8007,0x0,0x0,0}
00:11:09.727   {FOURCC(DXT3),0x8007,0x0,0x0,0}
00:11:09.727   {FOURCC(DXT4),0x8007,0x0,0x0,0}
00:11:09.727   {FOURCC(DXT5),0x8007,0x0,0x0,0}
00:11:09.727   {FOURCC(NVCS),0xd,0x0,0x0,0}
00:11:09.727   {FOURCC(NVHU),0x5,0x0,0x0,0}
00:11:09.727   {FOURCC(NVHS),0x5,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_D16,0xc1,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_D24X8,0xc1,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_D24S8,0xc1,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_D32F_LOCKABLE,0xc1,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_S8D24,0xc1,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_X8D24,0xc1,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_Q8W8V8U8,0x5,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_L8,0x40800f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_A8,0xf,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_L16,0x40000f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_A8L8,0x8007,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_G16R16,0x40400f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_A16B16G16R16,0x40600f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_V16U16,0x7,0x0,0x0,0}
00:11:09.727   {FOURCC(NVDB),0x4000,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_BINARYBUFFER,0x4000,0x0,0x0,0}
00:11:09.727   {FOURCC(NULL),0x100009,0x8b,0x8b,0}
00:11:09.727   {FOURCC(ATI1),0x1005,0x0,0x0,8}
00:11:09.727   {FOURCC(ATI2),0x1005,0x0,0x0,8}
00:11:09.727   {FOURCC(INTZ),0x10c1,0x0,0x0,32}
00:11:09.727   {D3DDDIFMT_P8,0x4400,0x0,0x0,0}
00:11:09.727   {FOURCC(SSAA),0x4000,0x0,0x0,0}
00:11:09.727   {FOURCC(ATOC),0x4000,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_A2B10G10R10,0x48610f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_A2R10G10B10,0x486d0f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_A8R8G8B8,0xc8610f,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_A8R8G8B8,0x448610f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_X8R8G8B8,0x4486d0f,0x8b,0x8b,0}
00:11:09.727   {FOURCC(3x11),0x40700f,0x8b,0x8b,32}
00:11:09.727   {FOURCC(3x16),0x407d0f,0x8b,0x8b,64}
00:11:09.727   {D3DDDIFMT_A16B16G16R16F,0x48610f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_G16R16F,0x40400f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_R16F,0x40400f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_R32F,0x40400f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_G32R32F,0x40400f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_A32B32G32R32F,0x48600f,0x8b,0x8b,0}
00:11:09.727   {D3DDDIFMT_R16F,0xc0400f,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_G16R16F,0xc0400f,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_A16B16G16R16F,0xc0400f,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_R32F,0xc0400f,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_G32R32F,0xc0400f,0x0,0x0,0}
00:11:09.727   {D3DDDIFMT_A32B32G32R32F,0xc0400f,0x0,0x0,0}
00:11:09.727 Supported z-buffer bit depths: 16, 24
00:11:09.727 Supported MSAA modes: msaa(3), msaa2x(0), msaa4x(0), msaa8x(0)
00:11:09.748 Dynamic vertex buffers are available
00:11:09.748 Dynamic index buffers are available
00:11:09.799 Installing DirectDraw hooks
00:11:09.801 Installing Direct3D hooks
00:11:09.802 Installing GDI hooks
00:11:09.805 Finished installing hooks

**Comment by narzoul** [comment]
I had a look, but I didn't see any issues related to ddraw or DDrawCompat. The game crashes after jumping to an invalid memory address and trying to execute code there. I don't really have time for patching problematic games like this, so I'll close this issue.
