### ISSUE TITLE
Theocracy Create DirectDraw failed error message

### ISSUE THREAD

**Issue by szombi** [narzoul/DDrawCompat#349]
Hey! 

I just found your tool. I am trying to find something that can run Theocracy in windowed mode (info: https://www.pcgamingwiki.com/wiki/Theocracy) This is a pretty old game. 
I tried all install methods on the wiki and only the `Method 4` worked with a manifest. When I try to start the game I see an error: `Create DirectDraw failed`. I didn't create any configuration for DDrawCompat, so I went with the default ones, and I attached the logs file. I'm using Windows 10 with the latest updates. I tried to check the old issues here in Git Hub, but I didn't find any error message like this. 
Any idea about this error? Thanks in advance! 

![image](https://github.com/user-attachments/assets/a1b04f53-8fdd-4d96-82c5-5d7374932a36)
[DDrawCompat-theocracy-0.6.85.log](https://github.com/user-attachments/files/16737377/DDrawCompat-theocracy-0.6.85.log)

**Comment by narzoul** [comment]
The game is using ddrawex.dll (first time I see that), which seems to have a version check for the ddraw.dll file, but it's checking DDrawCompat's dll instead of the system dll. I fixed it in v0.5.4.

Note that DDrawCompat doesn't have any features to force fullscreen games to windowed mode, and probably won't have in the near future either. You should try something like DxWnd for that.

**Comment by IllustriousProsperus** [comment]
**_Update_**:

if the game is installed in **_"C:\Theocracy"_** and start the exe **"theocracy-0.6.85.exe"** with ddraw 0.54, the game will start (sometimes) BUT you will not hear the audio of the videos and not of the audio tracks, BUT if you rename the executable to **"theocracy.exe"** the game will start, you will hear the audio of the videos and audio tracks but it will crash with the infamous **_"Create DirectDraw failed"_** error.

IF the game is installed in **_"F:\Theocracy"_** and start the exe **"theocracy-0.6.85.exe"** you will hear the audio of the videos and audio tracks but it will crash with **_"Create DirectDraw failed"_** error and if you rename the executable to **"theocracy.exe"** the game will start, you will hear the audio of the videos and audio tracks but it will crash with **_"Create DirectDraw failed"_** error. 

Weird uh?

**Comment by narzoul** [comment]
It sounds like you did not set up the manifest correctly if you're getting DirectDraw errors still. You should verify if DirectDraw is getting used at all, e.g. try opening any of the overlay or check the log file's date.
The rest of the issues might just be the Win11 24H2 CpuAffinity bug: https://github.com/narzoul/DDrawCompat/issues/387#issuecomment-2439487701

**Comment by IllustriousProsperus** [comment]
> It sounds like you did not set up the manifest correctly if you're getting DirectDraw errors still. You should verify if DDrawCompat is getting used at all, e.g. try opening either of the overlays or check the log file's date. The rest of the issues might just be the Win11 24H2 CpuAffinity bug: [#387 (comment)](https://github.com/narzoul/DDrawCompat/issues/387#issuecomment-2439487701)


I was wrong, both the regular ddraw and the one from #387 and other ddraws are completely ignored and I get the exact same error. (Create DirectDraw failed no longer appears???). Game crashes instantly when you reach the menu. It only works and not always, if you use Windows 95 compatibility (the audio and movie tracks are silent), another very badly programmed game.

![Image](https://github.com/user-attachments/assets/3361e91d-e75f-4621-afdc-0a10582268ad)

**Comment by narzoul** [comment]
Yes, your screenshot shows that DDrawCompat is still not applied, as you don't have the old-school window borders.

If you move or rename the executable, you must do the same with the manifest file, and also update the timestamp of the executable again with the PowerShell command mentioned in the wiki.

Take care to rename the manifest file correctly. If your Windows File Explorer is hiding file extensions by default, disable that setting to make sure the extension is correctly visible.

Or just use these in this attachment, which I've already renamed:
[Theocracy_manifests.zip](https://github.com/user-attachments/files/18607392/Theocracy_manifests.zip)

Then update the timestamps, e.g. if the game is installed in C:\Theocracy, then from PowerShell:
`Get-Item -Path C:\Theocracy\theocracy.exe | % {$_.LastWriteTime = (Get-Date)}`
`Get-Item -Path C:\Theocracy\theocracy-0.6.85.exe | % {$_.LastWriteTime = (Get-Date)}`

**Comment by IllustriousProsperus** [comment]
with the "manifest" files the game works, so I can say that the game is fixed. For the cpu bug... I read it once but I couldn't test it that with Stalker 1, with win 11 24h2 if set with 1 core but with a specific core, the number 7, the game worked without problems, maybe it's possible apply this function with ddraw?

**Comment by narzoul** [comment]
It is already possible to set any CPU affinity with DDrawCompat. That's what the CpuAffinity setting is for.
