### ISSUE TITLE
Resolution Scaling for Resident Evil 2 GOG

### ISSUE THREAD

**Issue by leold1975** [narzoul/DDrawCompat#356]
The Resolution Scaling for the GOG version of Resident Evil 2 doesn't work. The game keeps the resolution 320x240 in a 640x480 screen. FMV are playing fullscreen though.

I think it has something to do with GOG's tinkering with the exe. It would be really great if DDrawCompat would run with this version.

This is a part of the log:

18:38:25.779 Supported z-buffer bit depths: 16, 24
18:38:25.779 Supported MSAA modes: msaa(3), msaa2x(0), msaa4x(0), msaa8x(0)
18:38:25.832 Dynamic vertex buffers are available
18:38:25.832 Dynamic index buffers are available
18:38:25.893 Installing DirectDraw hooks
18:38:25.894 Installing Direct3D hooks
18:38:25.897 Installing GDI hooks
18:38:25.903 Finished installing hooks
18:38:25.992 Using resource format: D3DDDIFMT_R5G6B5, primary, anymem -> vidmem
18:38:25.992 Using resource format: D3DDDIFMT_R5G6B5, render target, anymem -> vidmem
18:38:25.993 Using resource format: D3DDDIFMT_X8D24, depth buffer, vidmem
18:38:25.993 Using Direct3D device type: IID_IDirect3DHALDevice
18:38:25.993 Using feature: enumerating hardware texture formats via IDirect3DDevice2
18:38:25.993 Using resource format: D3DDDIFMT_R5G6B5, texture, sysmem
18:38:25.994 Using resource format: D3DDDIFMT_R5G6B5, texture, anymem -> vidmem
18:38:28.016 Auto-detected ColorKeyMethod: native
18:38:31.263 ERROR: Failed to create the real primary surface: 0x887600e1
18:38:31.263 Using resource format: D3DDDIFMT_R5G6B5, primary, anymem (FAILED)

**Comment by narzoul** [comment]
Make sure both 320x240 and 640x480 are added to [SupportedResolutions](https://github.com/narzoul/DDrawCompat/wiki/Configuration#supportedresolutions), otherwise the game doesn't scale up to full screen for some reason. Maybe I'll add 320x240 by default in the future, since a few games still seem to use it.

These settings should work well as a base:
```
AlternatePixelCenter = on
DisplayRefreshRate = desktop
SpriteDetection = zconst
SupportedResolutions = 320x240, 640x480
```

Then you can change Antialiasing, ResolutionScale and TextureFilter as you like.

**Comment by leold1975** [comment]
**A huge thank you** for your help, narzoul! The game runs fullscreen now!
