### ISSUE TITLE
The Devil Inside (Videos not working anymore)

### ISSUE THREAD

**Issue by Zerodarkage** [narzoul/DDrawCompat#359]
I need help! I did a clean install copied the files and the fixes! (Yours  and Audio) but videos are not working anymore...

Here is a Debug Log of The Devil Inside with Patch #1 (Plus DSOAL and ogg-winmm):
[DDrawCompat-Devil.log.zip](https://github.com/user-attachments/files/16923459/DDrawCompat-Devil.log.zip)

I don't understand what changed! If this problem has nothing to do with your wrapper! I'm lost! xD

I'm using the Patch#1 EXE without any changes! :)

Your Wrapper fixes:
- Most of the Graphics!
- DDraw error!
- Videos (Intro, etc)
- Transparency issues (Helicopter looks beautiful!)
- Random crashes! (Most of then except for my setup because secondary fixes)
- Keyboard and Mouse works correctly!

Thanks for all that and much more! Your Wrapper is my favorite one! 
Because it just works! The dgVoodoo2 is awesome too!

_Originally posted by @Zerodarkage in https://github.com/narzoul/DDrawCompat/issues/352#issuecomment-2336752882_

I have to close this one for now! I suspect something went wrong with my sound drivers!

**Comment by narzoul** [comment]
Are you using a no-cd patch? If yes, don't forget to copy the Datas\Movies folder from the CD to the same directory in your install folder.

**Comment by Zerodarkage** [comment]
> Are you using a no-cd patch? If yes, don't forget to copy the Datas\Movies folder from the CD to the same directory in your install folder.

I forgot about the NOCD... 
Thanks!!! :D

**Comment by ThatDudeYouMetThatOneTime** [comment]
Hi, I know this an older and closed thread, but I tried following the steps Zerodarkage laid out in their 2nd post. However, when I try to go boot the game, it keeps on asking me for the CD, despite having it mounted virtually, and doesn't let me progress past the title screen. I tried using both DaemonTools Lite and WinCDEmu for mounting the game, the base version from my abadonware, but no dice. 

There was ONE thing I was confused about, and not sure where to find though. I was sure where to find the 2 "DSOAL r556" DLLs mentioned in one of the steps, so I had to skip that one. 

At this point, I might just say "screw it" and try buying a physical copy to make my own ISO of, to see if the game will accept that, cause I CANNOT for the life of me get past this disc-check, even with the no-CD patch I found (it doesn't seem to work anymore sadly). 

Any help you guys, or someone else who finds this thread could give me would be GREATLY appreciated. The Devil Inside seems like a really unique game, and I'd hate to not be able to ever fully experience it because of dumb technical issues.

**Comment by Zerodarkage** [comment]
Hey! Tris this links!

DSOAL (Fix sound problems)
https://github.com/ThreeDeeJay/dsoal/releases

Devil Inside (NOCD EXE) - Scroll to extras and get "Windows 10 fix English version 56 MB"
https://www.myabandonware.com/game/the-devil-inside-cl6

ogg-winmm ("CD AUDIO EMULATOR") 
https://github.com/ayuanx/ogg-winmm/releases

Hope this helps!

**Comment by ThatDudeYouMetThatOneTime** [comment]
> Hey! Tris this links!
> 
> DSOAL (Fix sound problems) https://github.com/ThreeDeeJay/dsoal/releases
> 
> Devil Inside (NOCD EXE) - Scroll to extras and get "Windows 10 fix English version 56 MB" https://www.myabandonware.com/game/the-devil-inside-cl6
> 
> ogg-winmm ("CD AUDIO EMULATOR") https://github.com/ayuanx/ogg-winmm/releases
> 
> Hope this helps!


Oh cool, thank you VERY MUCH for getting back to me! I'm about to try the stuff from your links and see how they go. I'm not really sure about how to use the ogg-winmm thing, because it mentions "encoding" the music tracks to .ogg files. I'm not the most technically competent person, therefore I'm a little worried about screwing something up there. Do you know of any decent video guides for using "ogg-winmm"? 

Also, I have tried the NOCD exe before, but it didn't seem to work for me cause the game still kept asking for a disc. However, the NOCD exe works *on 86Box when emulating Windows 98 SE,* so I'm not sure what the problem is there. 

One more thing (sorry to keep piling on the questions): Which folder should I grab the 2 DLLs from DSOAL from? The regular "DSOAL" folder, or the "DSOAL + HRTF" folder? On top of that, since I'm using a 64-bit Windows 10, should I then grab *the 64-bit versions of the DLLs,* or no? 

Another thing I should probably mention. For me, when running the game natively, the sound and music seem to be working just fine. So, should I just ignore the DSOAL DLLs to begin with?

**Comment by Zerodarkage** [comment]
<img width="313" height="456" alt="Image" src="https://github.com/user-attachments/assets/d42eb5b5-4053-4f13-a7ab-9c1a632463b6" />

I use PowerISO to RIP musics from CD/ISO straight to OGG with the correct name! (TrackXX.ogg where XX is the track number).
After ripping put the files on a MUSIC folder and move to the "game" folder! (Screenshot) plus the DLL and INI files ("game" folder).
The CD audio is only used for ambience music!

DSOAL you should always verify if your game is 32-bit or 64-bit (Devil Inside is 32-bit game) so you use 32-bit dlls.
I always use the standard DSOAL version (Using DSOAL sometimes is optional xD).

About the NOCD not working for you... No idea why xD.

**Comment by ThatDudeYouMetThatOneTime** [comment]
Okay, now I have a DIFFERENT problem. The game now boots fine enough to the title screen, and even the first two cutscenes play fine. However, it ALWAYS crashes right before its supposed to go into gameplay. I'm at a bit of a loss here now. 

I appreciate you being communicative to me throughout this process. As someone who has ignored their own old github posts before, after I personally fixed an issue for myself or got too lazy, I appreciate you taking the time to respond.

**Comment by ThatDudeYouMetThatOneTime** [comment]
So, I know I've AT LEAST done the following to my Devil Inside install so far. I have (not necessarily in this order):

- Used the Windows 10 fix
- Used your recommended custom DLL
- Copied the "Datas" folder from the ISO
- Used DSOAL r556's 2 DLLs
- Ripped the music from the ISO's "music" folder

The no-CD patch hasn't done anything for me so far, so at this point I'm unsure of what to try next. I DID try disabling some Nvidia overlay stuff, but that didn't seem to do anything.

**Comment by Zerodarkage** [comment]
You could try apply the official patch first! Maybe this helps with the NOCD exe!
https://www.patches-scrolls.de/patch/1235/7/41570/download
I think is worth a try!

**Comment by ThatDudeYouMetThatOneTime** [comment]
> You could try apply the official patch first! Maybe this helps with the NOCD exe! https://www.patches-scrolls.de/patch/1235/7/41570/download I think is worth a try!

Yeah, I've tried the official patch, but for some reason it just IMMEDIATELY closes itself after I point it to where the game is installed without actually patching the game. 

Now, I DO have a couple other installs of this game on my PC from failed attempts to get it working. Could that maybe be causing some sort of file conflict?

**Comment by Zerodarkage** [comment]
Well, I don't think Devil Inside uses the "Windows Registry". Hmmm... Could you try this version!? See if it works for you xD
https://drive.google.com/file/d/1g_3oUEYnfW9DrnPHVjTmP6RJPxRGnEgJ/view?usp=sharing

**Comment by ThatDudeYouMetThatOneTime** [comment]
> Well, I don't think Devil Inside uses the "Windows Registry". Hmmm... Could you try this version!? See if it works for you xD https://drive.google.com/file/d/1g_3oUEYnfW9DrnPHVjTmP6RJPxRGnEgJ/view?usp=sharing

Yeah, no luck so far with that version. It still crashes after the first two cutscenes.

**Comment by Zerodarkage** [comment]
Do you have K-Lite Codec pack installed? I fixed so many games by just installing K-Lite!
https://www.codecguide.com/

**Comment by ThatDudeYouMetThatOneTime** [comment]
> Do you have K-Lite Codec pack installed? I fixed so many games by just installing K-Lite! https://www.codecguide.com/

I'll try that next, thanks!

**Comment by ThatDudeYouMetThatOneTime** [comment]
> Do you have K-Lite Codec pack installed? I fixed so many games by just installing K-Lite! https://www.codecguide.com/

Which version would you recommend I grab, "Standard," "Full," or "Mega"?

**Comment by Zerodarkage** [comment]
> > Do you have K-Lite Codec pack installed? I fixed so many games by just installing K-Lite! https://www.codecguide.com/
> 
> Which version would you recommend I grab, "Standard," "Full," or "Mega"?

I always use MEGA!

**Comment by ThatDudeYouMetThatOneTime** [comment]
> > > Do you have K-Lite Codec pack installed? I fixed so many games by just installing K-Lite! https://www.codecguide.com/
> > 
> > 
> > Which version would you recommend I grab, "Standard," "Full," or "Mega"?
> 
> I always use MEGA!

Welp, unless there's some non-standard options I need to enable with K-Lite, no luck with that either. :(

**Comment by Zerodarkage** [comment]
WOW! Everything failed... 
Try this game! It uses the same engine! Just to see if it works!
https://drive.google.com/file/d/1ti01DdnJhpgX_HWPJvdwDHZn73QpLU6X/view?usp=sharing

**Comment by ThatDudeYouMetThatOneTime** [comment]
> WOW! Everything failed... Try this game! It uses the same engine! Just to see if it works! https://drive.google.com/file/d/1ti01DdnJhpgX_HWPJvdwDHZn73QpLU6X/view?usp=sharing

Alright, I'll see what happens. Perhaps afterwards I'll just make 1 or 2 more FRESH attempts with getting this running, before I call it quits and just continue playing through the game with somewhat sluggish performance on 86Box. 

That, or I'll try and get it running on my Steam Deck through QEMU or something.

**Comment by ThatDudeYouMetThatOneTime** [comment]
> WOW! Everything failed... Try this game! It uses the same engine! Just to see if it works! https://drive.google.com/file/d/1ti01DdnJhpgX_HWPJvdwDHZn73QpLU6X/view?usp=sharing


Yeah, so, bad news: That game crashed BEFORE EVEN LOADING A CUTSCENE. It kept crashing after loading once I clicked New Game and the difficulty selection.

**Comment by Zerodarkage** [comment]
> > WOW! Everything failed... Try this game! It uses the same engine! Just to see if it works! https://drive.google.com/file/d/1ti01DdnJhpgX_HWPJvdwDHZn73QpLU6X/view?usp=sharing
> 
> Yeah, so, bad news: That game crashed BEFORE EVEN LOADING A CUTSCENE. It kept crashing after loading once I clicked New Game and the difficulty selection.

Well... Maybe something in your hardware is causing the problem... Maybe not...
I'm out of ideas xD

P.S.
One last thing! Have you tried to re-install Directx!?
https://www.microsoft.com/en-us/download/details.aspx?id=8109

EDIT:
And try Windows SP2 Compatibility!

**Comment by ThatDudeYouMetThatOneTime** [comment]
> > > WOW! Everything failed... Try this game! It uses the same engine! Just to see if it works! https://drive.google.com/file/d/1ti01DdnJhpgX_HWPJvdwDHZn73QpLU6X/view?usp=sharing
> > 
> > 
> > Yeah, so, bad news: That game crashed BEFORE EVEN LOADING A CUTSCENE. It kept crashing after loading once I clicked New Game and the difficulty selection.
> 
> Well... Maybe something in your hardware is causing the problem... Maybe not... I'm out of ideas xD
> 
> P.S. One last thing! Have you tried to re-install Directx!? https://www.microsoft.com/en-us/download/details.aspx?id=8109
> 
> EDIT: And try Windows SP2 Compatibility!


Okay, I will try this later, thanks!

**Comment by ThatDudeYouMetThatOneTime** [comment]
> > > WOW! Everything failed... Try this game! It uses the same engine! Just to see if it works! https://drive.google.com/file/d/1ti01DdnJhpgX_HWPJvdwDHZn73QpLU6X/view?usp=sharing
> > 
> > 
> > Yeah, so, bad news: That game crashed BEFORE EVEN LOADING A CUTSCENE. It kept crashing after loading once I clicked New Game and the difficulty selection.
> 
> Well... Maybe something in your hardware is causing the problem... Maybe not... I'm out of ideas xD
> 
> P.S. One last thing! Have you tried to re-install Directx!? https://www.microsoft.com/en-us/download/details.aspx?id=8109
> 
> EDIT: And try Windows SP2 Compatibility!

Yeah, I'm sorry...Reinstalling DirectX didn't work out either. Well, thank you again for taking the time to try and help me play this game natively on my PC. I'm gonna move on to something else now, like trying DxWnd or DgVooDoo. 

I did stumble on *a* tutorial on youtube from a channel called "WORG FIRSTLOOK," but they have rather despicably made the tutorial a paid "members only" video. Pfft, what a crook. XD

**Comment by Zerodarkage** [comment]
You are welcome! I hope you find a solution! Good luck!
