### ISSUE TITLE
Yuri's Revenge - Manual Changes Not Taking Effect

### ISSUE THREAD

**Issue by TonyDrandretti** [narzoul/DDrawCompat#362]
Hi,

I am attempting to change the aspect ratio to match that of my PC. When doing so I am following the configuration guide and changes made to DDrawCompat-gamemd aren't carrying over on launch (it seems to restore to default). 
The same is happening when attempting to add more resolutions to supportedresolutions. 

I think I may be doing something wrong but some guidance would be appreciated.

**Comment by narzoul** [comment]
Please attach your DDrawCompat log file and config files.

**Comment by narzoul** [comment]
See also some tips here: #365
