### ISSUE TITLE
PBA Bowling Tour 2

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#363]
The game crashes here and there, I am not sure where the issue is.

On Windows 7, all the crashes were related to D3DIM.DLL (natively)
On Windows 11, all the crashes natively were on nvd3dum.dll
With DDrawCompat 0.5.4 on Win11, it turned to ntdll.dll

I don't know if DDrawCompat can help

**Comment by narzoul** [comment]
Not likely. There are random memory corruptions and I couldn't find where they come from. The most common one with DDrawCompat is corruption of an STL map container's structure, which causes a null pointer access later. But I've seen many other random places where it blows up, including corrupting the constant strings where the function names are stored for debug logging. I don't have more time to try to track it down, and I'm pretty sure it's not related to ddraw, so I'm closing this.
