### ISSUE TITLE
The Fifth Element - Black screen after 0.5.1

### ISSUE THREAD

**Issue by geracerejo** [narzoul/DDrawCompat#368]
Previous versions worked but FOG is not right.

**Comment by narzoul** [comment]
The game works fine for me with v0.5.4, including fog, on all 3 GPUs I could test. What GPU are you using? Please attach the DDrawCompat log file using LogLevel=debug (in DDrawCompat.ini) with v0.5.4, and also a screenshot of what the fog looks like with v0.5.1 at the start of a new game.

Also, if you could determine which commit between v0.5.1 and v0.5.2 broke the game for you, that could be very useful. You can download a separate build of all such commits under the v0.5.2 release. Direct link here:
https://github.com/narzoul/DDrawCompat/releases/download/v0.5.2/DDrawCompat-v0.5.2-debug-previous-builds.7z
