### ISSUE TITLE
Fork Request for Win9x and WinXP

### ISSUE THREAD

**Issue by musemice** [narzoul/DDrawCompat#369]
Hey there,

I am using ddrawcompat for many years now and I deeply appreciate the work you are putting into this project.
One feature that caught my eye is the emulation of 8bit palletized textures, used in Final Fantasy 7 and 8. Enabling it enables us to play those games with DX hardware renderer in Win10. Without it, we are stuck with software renderer.

In the retro scene, palettized textures are discussed a lot, although there are not too many games affected. However, the Final Fantasy series are still very popular ones.

Is it possible to create a fork of ddrawcompat for Win9x and WinXp, but only for the palletized textures feature / conversion?
Many of us retro gamers want to play those games on retro hardware, but the 8 bit palletized textures are not supported on some newer Ati and Nvidia cards. Voodoos are expensive these days.

Thanks in advance! And keep up the great work!

**Comment by narzoul** [comment]
Is it possible? Sure, anyone can fork it and do whatever they want with it. Is it possible to "just" delete 95% of the code and expect it to work on Win9x/XP with palettized texture support? No. you'd definitely have to rewrite parts of it. For example, converting palettized textures to 32-bit textures happens in shaders through WDDM driver hooks, which is not available on anything older than Vista, so it would have to be reimplemented on the CPU. Moreover, very old GPUs might not support 32-bit textures at all (I think the Voodoos didn't, for example). And from what I recall, FF8 uses combined 8 bit alpha + 8 bit palette textures, so it may not be possible to emulate without 32-bit texture support. It may work with loss of precision if something like A4R4G4B4 is supported. You'd likely have to add support for different formats on different GPUs, depending on the available capabilities.

If you're asking if I'll do it, then no. I have neither the time, nor the interest in supporting old hardware and OSes.

**Comment by musemice** [comment]
Thank you for the detailed background of the 8bit texture conversion! As you maybe notice, I lack knowlege of programming. For me, the work you do is pure magic! I also would never ask anyone to do it, if it is extensive and time consuming. It is probably not worth the effort. And if 32-bit texture support is a must have, than we would be limited the other way around.

I admire the work you have put in ddrawcompat so far, considering the complexity of the earlier Direct Draw and Direct 3D implementations in games. Back in the day, you would need a certain graphic adapter with a certain driver to be able to run some stuff. The fiddeling around with hardware and drivers was an essntial pain we had to suffer back in the day in the time of Win 95/98.

Interestingly, the Ati Rage Series had some palletized texture "emulation" in the driver options as well as table fog, which actually works quite good. I think, that S3 took a smilar approach in their Savage series. Maybe I will look into this more deeply.
