### ISSUE TITLE
DLL File?

### ISSUE THREAD

**Issue by pcwilliam** [narzoul/DDrawCompat#37]
The insrutctions say to copy the DLL file and insert that into a certain place. When I unzip the download, the master folder contains a lot of other folders, including a dll folder, but there is no actuall dll file or a file that says ddraw.dll.

Can anyone tell me what I'm doing wrong or am not aware of?

**Comment by narzoul** [comment]
I think you're downloading the source code rather than the binary releases.
The binary releases are on this page: https://github.com/narzoul/DDrawCompat/releases
Look for the ddraw.zip files.
