### ISSUE TITLE
Windows 11 24H2 Causing Black Screen and Freeze When Exiting Red Alert 2 and Yuri's Revenge

### ISSUE THREAD

**Issue by Wenxj1021** [narzoul/DDrawCompat#372]
DDrawCompat encountered some issues on Windows 11 24H2. When exiting the games Red Alert 2 and Yuri's Revenge, the screen goes black and freezes, and the only way to exit is by using Task Manager in a newly created desktop to close the game process. This issue only appears on the 24H2 system version, while everything works fine on 23H2. Moreover, both version v0.53 and v0.54 have this problem.

**Comment by Wenxj1021** [comment]
According to the debug log, the game freezes at the function RealPrimarySurface::updatePresentationParams().

**Comment by narzoul** [comment]
It is not an issue with DDrawCompat. It is an issue with running the game on a single CPU core for some reason. I don't recommend reproducing it without DDrawCompat though, as the issue tends to be worse then, locking up most of the system and making it difficult or impossible to end the process through Task Manager. With DDrawCompat, you should be able to shut it down with TerminateHotKey, or it will automatically terminate if you try to attach a debugger or increase the processor affinity to multiple cores.

I'd recommend using CpuAffinity=all as a workaround, though I don't know if that causes any other problems with this game.

**Comment by Wenxj1021** [comment]
> It is not an issue with DDrawCompat. It is an issue with running the game on a single CPU core for some reason. I don't recommend reproducing it without DDrawCompat though, as the issue tends to be worse then, locking up most of the system and making it difficult or impossible to end the process through Task Manager. With DDrawCompat, you should be able to shut it down with TerminateHotKey, or it will automatically terminate if you try to attach a debugger or increase the processor affinity to multiple cores.
> 
> I'd recommend using CpuAffinity=all as a workaround, though I don't know if that causes any other problems with this game.

Thank you for the suggestion! I tried setting CpuAffinity=all, and it indeed solved the issue. So far, I haven't noticed any negative side effects, and the game seems to perform well overall. Thanks again for your help!

**Comment by Wenxj1021** [comment]
Thank you for the suggestion! I tried setting CpuAffinity=all, and it indeed solved the issue. So far, I haven't noticed any negative side effects, and the game seems to perform well overall. Thanks again for your help!
