### ISSUE TITLE
Bust-A-Move\Puzzle Bobble games are extremely slow

### ISSUE THREAD

**Issue by mrpenguinb** [narzoul/DDrawCompat#378]
Before anything else is mentioned, using dgVoodoo doesn't resolve the performance issues I have with Puzzle Bobble 1,2,3, or 4.

It seems to be NVIDIA-specific, from testing on multiple computers. I've even tried dxwrapper and the settings it provides to no avail.

I know this isn't technically related to DDrawCompat, but wondering if you can offer any solutions or reasons why this is happening...
For your information, Shift + F11 shows DDrawCompat's menus.

[Example of performance issues: ](https://youtu.be/rKIjKmzPoNQ)
[Example of how the game should play: ](https://youtu.be/CNXB6SU5GfU?t=9)

**Comment by narzoul** [comment]
Runs completely fine with default settings on my 3060Ti. Does the game have decreased flip rate according to the stats overlay (shift+f12)? It seems to be internally limited to ~62 FPS.
Have you tried CpuAffinity=all? Can you share debug logs?

**Comment by narzoul** [comment]
Your game seems to spend an abnormally long time enumerating DirectInput devices or something after each flip. I'm just guessing based on the registry keys accessed. Mine accesses DirectInput keys also, but "only" a few hundred instead of thousands like yours, and it finishes up significantly faster. Even with debug logs enabled I get ~31 FPS.

Try disconnecting unnecessary devices. There may also be some DirectInput wrappers that could help, but I'm not really familiar with those (nor with DirectInput in general). Maybe this one? https://github.com/riverar/IndirectInput

**Comment by mrpenguinb** [comment]
Thank you! Turns out my Logitech dongle shows about 5-10 devices...
![image](https://github.com/user-attachments/assets/b79b77ae-d05f-4507-b0e7-75eef70989b1)

I'll have to investigate why that is, or else just use a wired keyboard in future.

**Comment by elishacloud** [comment]
Some games call `EnumDevice()` too often (like every frame).  This can cause slowness and stuttering.  I added a device enum cache to give the game cached data rather than calling the slow function all the time.  See [here](https://github.com/elishacloud/dxwrapper/issues/303) for an example.

**Comment by mrpenguinb** [comment]
> Some games call `EnumDevice()` too often (like every frame). This can cause slowness and stuttering. I added a device enum cache to give the game cached data rather than calling the slow function all the time. See [here](https://github.com/elishacloud/dxwrapper/issues/303) for an example.

Is the fix you provided for the DeviceLookupCacheTime crashing merged into dxwrapper now? 
Your tool is very useful for quickly experimenting with various wrappers without moving a bunch of different .DLLs around.
It's just an intimidating tool to get the hang of, Notepad ++ helps alleviate that by showing each section/wrapper clearly.

**Comment by elishacloud** [comment]
> Is the fix you provided for the DeviceLookupCacheTime crashing merged into dxwrapper now?

Yes, the fix was checked in here:  [30e42a2](https://github.com/elishacloud/dxwrapper/commit/30e42a21b66bf2bbe116ce31b23345d00250be0e)
