### ISSUE TITLE
Can't load the DLL

### ISSUE THREAD

**Issue by sourcerunner** [narzoul/DDrawCompat#38]
Hello, I' m using this patch for Red Alert 2. I put ddraw.dll in the same directory as the executable file, but nothing really changed, and the ddraw.log didn't appear. I think maybe the DLL file isn't loaded at all? Why does this happen?

I'm using Windows 10, thx.

**Comment by narzoul** [comment]
You can use tools like [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to check which DLLs are loaded by a process, and also to verify if the game executable is where you think it is. What does it show?

I have the game from Origin and it works fine with DDrawCompat here on Windows 10.

**Comment by sourcerunner** [comment]
Yes, thanks for telling me the perfect tool, I find the problem. The executable is game.exe, and it loads the  `C:\Windows\SysWOW64\ddraw.dll`, which is undesirable.

The solution is to delete the `ddraw.dll` entry in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\KnownDLLs` in the registry, so the program can find the patched version of `ddraw.dll`.

Thanks again, for helping me, and for your brilliant job!
