### ISSUE TITLE
Hype the Time Quest

### ISSUE THREAD

**Issue by IllustriousProsperus** [narzoul/DDrawCompat#380]
With the executable **"MaiD3Dvr_bleu.exe**" with the standard **"ddraw.dll"**, the game starts with cutscenes, but the main screen remains black with background audio. IF I rename the exe with something else from **"MaiD3Dvr_bleu.exe"** to **"HYPE.exe"** for d3d and then with the hex editor, I change the name of the **"ddraw.dll"** to **"dhype.dll"** , it works **_perfectly_** with a minor graphic defect, probably caused by the increase of the resolution. (the game does not allow changing resolution fixed at 640x480)
![Screenshot (59)](https://github.com/user-attachments/assets/ae56a4a9-7cd0-4349-8436-f798f39bed67)
![Screenshot (62)](https://github.com/user-attachments/assets/a8eca26e-6eb1-41cb-8df5-bc1cbea82491)

**Comment by narzoul** [comment]
Try ResolutionScaleFilter=bilinear.

**Comment by IllustriousProsperus** [comment]
> Try ResolutionScaleFilter=bilinear.
Perfect! now the game can be played without problems
![Screenshot (100)](https://github.com/user-attachments/assets/2a20e6a6-0073-4af1-8460-c85d94bf6a3b)
