### ISSUE TITLE
Problem with midnight club 2

### ISSUE THREAD

**Issue by Jospw32** [narzoul/DDrawCompat#388]
Hello, I came to report a problem I have, you see, on pcgamingwiki I saw that in the game solutions to avoid the game from closing was to use this plugin, question, I paste the file in the root folder of the game (where the executable is) I enter the game and I see that no .ini file is created, I have tried your solutions that you have on your wiki and nothing.

**Comment by narzoul** [comment]
I think PCGamingWiki is wrong, this game doesn't use DirectDraw at all, at least not on my system. It uses Direct3D 9 (it's actually correctly mentioned later in the API section), so DDrawCompat won't help with it.

I didn't see any use of DirectShow either, at least not before the game crashes. I'm closing this as D3D9 is not supported by DDrawCompat.

**Comment by Jospw32** [comment]
Well, at least thanks for clearing my doubts.
