### ISSUE TITLE
Silent Hunter 2

### ISSUE THREAD

**Issue by IllustriousProsperus** [narzoul/DDrawCompat#391]
The game starts, the mouse works without problems, but after starting the mission, the game settles at 2fps, if I try to record the game with the amd Record & Stream, the fps rises to 25fps maybe 30fps. Tested with GoG and original version.

Recorded with the amd Record & Stream

https://github.com/user-attachments/assets/e01135c3-c4ed-49a3-a3b8-256349bcb86c

**Comment by narzoul** [comment]
Works fine for me after using SupportedDepthFormats=16 to avoid a crash at startup.

Did you add DDrawCompat to the Sim directory as well? The missions themselves use a separate executable (Sim.exe) there. It won't be hooked unless you put ddraw.dll there also.

**Comment by IllustriousProsperus** [comment]
> Works fine for me after using SupportedDepthFormats=16 to avoid a crash at startup.
> 
> Did you add DDrawCompat to the Sim directory as well? The missions themselves use a separate executable (Sim.exe) there. It won't be hooked unless you put ddraw.dll there also.

I hadn't really noticed the executable in the other folder! Basically, the "ddraw.dll" dll must be in both folders

****"C:\Silent Hunter II\Shell"**
**_AND_**
**"C:\Silent Hunter II\Sim"****

**Solved!**
