### ISSUE TITLE
Force the game to run stretch fullscreen

### ISSUE THREAD

**Issue by Alexhob123** [narzoul/DDrawCompat#396]
Hi there!
I'm running 800x600 game on 1920x1080 with DDrawCompat.
Everything works fine except the black border appear on the right and left side.

how do i get this to be stretched

**Comment by narzoul** [comment]
Use the [DisplayAspectRatio](https://github.com/narzoul/DDrawCompat/wiki/Configuration#displayaspectratio)=display setting. Read the top of the same wiki page on how to change configuration.

**Comment by Alexhob123** [comment]
i have changed it but nothing happens
