### ISSUE TITLE
Braveheart

### ISSUE THREAD

**Issue by IllustriousProsperus** [narzoul/DDrawCompat#399]
With ddrawcompat instant crash

Log and crash dump

https://mega.nz/folder/jMElBYJR#sLgNoorHbVrWvSXITC46dg

With dgvoodoo2 2.83.2
Menu only but buggy, no intro movies, every attempt to click on any options causes a crash, the mouse pointer is not present due to a ".cur" cursor bug.

![Crash](https://github.com/user-attachments/assets/74d87989-6b4e-4c23-b1af-b5d60ea52d55)

**Comment by BEENNath58** [comment]
See if this restores the cursor:
[cursor.zip](https://github.com/user-attachments/files/17706776/cursor.zip)

**Comment by BEENNath58** [comment]
> that cursor fix taken from dxwnd doesn't work for me personally, I used another cursor (cursor number 3 in the original exes are missing!) and I can see it and unfortunately the game crashes anyway...

Apparently the issue used to occur in DDC and dgVooodoo2 only but not WineD3D:
https://sourceforge.net/p/dxwnd/discussion/general/thread/6d514e9029/#d941

No idea on what's the issue that causes the crash

**Comment by narzoul** [comment]
This should fix the crash:
[ddraw.zip](https://github.com/user-attachments/files/17715197/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/17715198/diff.txt) compared to v0.5.4)

Game works apart from the missing cursor. Videos only work sometimes, seems to depend on some unknown luck factor, I don't want to get into that more now.
I started a campaign but no idea what to do from there. Isn't there supposed to be some 3D part in the game somewhere?

> See if this restores the cursor: [cursor.zip](https://github.com/user-attachments/files/17706776/cursor.zip)

This doesn't work for me.

**Comment by IllustriousProsperus** [comment]
> This should fix the crash: [ddraw.zip](https://github.com/user-attachments/files/17715197/ddraw.zip) ([diff.txt](https://github.com/user-attachments/files/17715198/diff.txt) compared to v0.5.4)
> 
> Game works apart from the missing cursor. Videos only work sometimes, seems to depend on some unknown luck factor, I don't want to get into that more now. I started a campaign but no idea what to do from there. Isn't there supposed to be some 3D part in the game somewhere?
> 
> > See if this restores the cursor: [cursor.zip](https://github.com/user-attachments/files/17706776/cursor.zip)
> 
> This doesn't work for me.

**_Fixed!_**
 
The videos have the infamous rpl video format (tomb raider classic, soul reaver, fighting force)  
However I tried the game with pcem and noticed two things, that the screens have a "fading" effect, maybe that's what was causing the crash? (with the your latest fix the fading is ignored) and as you can see the cursor is the black and white one so I also think that that is in fact the buggy cursor!

**_with ddraw compat fixed_**

![brave (1)](https://github.com/user-attachments/assets/99cd6646-cea5-4bde-ae10-06166f3379eb)

![brave (2)](https://github.com/user-attachments/assets/3ec3ad8d-d415-44c8-bc64-e13e3a49aff3)

![brave (3)](https://github.com/user-attachments/assets/7fcc45ba-a4f7-484b-bec8-5a62eacba4a1)

**_rpl video dlls_**

![rpl dll](https://github.com/user-attachments/assets/d3e3d96f-0076-40f3-8a91-73b7c86f9eaa)

https://github.com/user-attachments/assets/fd0908d2-2c5e-45ed-bff0-1e2b6e4500fe

**_p.s._**
to see the 3D village you have to press CTRL and double left click on the city, F1 to advance with time

**Comment by narzoul** [comment]
> I still don't understand how the "fpslimiter" works, I have to set it to 30fps

Your logs show you're still setting parameters incorrectly. You should use it like this:
FpsLimiter=flipend(30)

Or just use the config overlay and export the settings from there.

**Comment by IllustriousProsperus** [comment]
> > I still don't understand how the "fpslimiter" works, I have to set it to 30fps
> 
> Your logs show you're still setting parameters incorrectly. You should use it like this: FpsLimiter=flipend(30)
> 
> Or just use the config overlay and export the settings from there.

Done thanks, now the map is controllable

reading the string anyway
**_"flipstart(MaxFPS: 10..200 | 60)"_**
Written like this it seems that something should be inserted after **_"|"_**, in the configuration instructions I would put some "examples".
