### ISSUE TITLE
Blackscreen in KillingTime

### ISSUE THREAD

**Issue by Centuri0n086** [narzoul/DDrawCompat#406]
Launching Killing time, the first movie plays. But after the screen goes black and all my pcs fans rev up.
the app has to be killed pretty quickly via task manager other wise the whole pc freezes. I can see the app is not responding before I force close it.

Windows 11 24H2
I9 14900K
4090

**Comment by narzoul** [comment]
It's probably the Windows 11 24H2 single core affinity bug. Can you try the patch I posted here? https://github.com/narzoul/DDrawCompat/issues/387

**Comment by Centuri0n086** [comment]
Yep CPUAffinity=All worked
