### ISSUE TITLE
Is it possible to force a native fullscreen game to windowed?

### ISSUE THREAD

**Issue by zhm86** [narzoul/DDrawCompat#407]
Is it possible to force a native fullscreen game to windowed? Thanks.

**Comment by narzoul** [comment]
There are no plans for windowed mode in the near future (too much effort). You can try DxWnd for such purposes.

At best I could add a very limited "windowed" mode with a non-movable/non-resizable window stuck at the top left corner of the screen, without window borders, if there is any interest in that. That's essentially similar to borderless fullscreen mode, but it wouldn't cover the right and/or bottom sides of the desktop.

**Comment by zhm86** [comment]
Thanks.
Then I will try to modify SetCooperativeLevel and something else.
I used cnd-ddraw and dxwnd, both of them caused screen flicker while holding left mouse button in minimap in some games.
But your DDrawCompat works very well.
