### ISSUE TITLE
Query: can old DX over modern MSHybrid laptops run on dGPU

### ISSUE THREAD

**Issue by BEENNath58** [narzoul/DDrawCompat#411]
I will be moving to a laptop solution soon, probably more inclined towards Intel due to my purposes. That leaves me with a very new IGDTrinity driver to handle.

Intel GPU may do well with DDC, or alone somewhat, but will have performance issues somewhere or other

dGPU will be a modern NVIDIA 4060/70 or 5K series. As of technology right now, will it be possible to run pre DX7 games over dGPU?

The options I see are MUX Switch, and Adv Optimus. The latter defines it doesn't work with DX9 (old DX rely on DX9 ?)

MUX Switch is what I am unsure of: it **seems to remove** the iGPU from the Control Panel completely, so that means it will give control over to the dGPU and not the iGPU. Is this the option that can swiftly allow me to play a game over Intel and NVIDIA on a single device?

**Comment by narzoul** [comment]
I have no idea. Never had any NVIDIA laptops myself.

**Comment by BEENNath58** [comment]
Alright, thanks. I had been researching some myself and got to this:
https://www.reddit.com/r/LenovoLegion/comments/rka6d3/optimus_mux_and_advanced_optimus_explanations_for/

You can close the thread, just so you can see this if its valuable in some way
