### ISSUE TITLE
Grand Theft Auto (1997) interesting find

### ISSUE THREAD

**Issue by FabioBi** [narzoul/DDrawCompat#412]
The original (1997) and the freeware edition (2002) works good only if you use the fixed mss32.dll from the user Alienx999 in this thread: 
https://gtaforums.com/topic/873594-is-there-any-way-to-fix-the-radiomusic-bug-in-gta-1/?tab=comments#comment-1069541939/
Otherwise the framerate is very poor.

**Comment by BEENNath58** [comment]
What's the context of the thread here?

**Comment by FabioBi** [comment]
It's strange, that dll fixes the radio/music goes silent after some time but fixes the framerate too.

**Comment by narzoul** [comment]
I guess it's related to the audio using too much CPU or something, which doesn't play nicely with single core affinity. Try using CpuAffinity=all, should fix the framerate issues as well.

**Comment by FabioBi** [comment]
CpuAffinity=all fixes the framerate issue but not the radio goes silent after some time of playing.

**Comment by narzoul** [comment]
That's all it's supposed to fix. Audio issues are out of scope for DDrawCompat.
