### ISSUE TITLE
In game hangs following recent Windows 11 Home update

### ISSUE THREAD

**Issue by ejahnke** [narzoul/DDrawCompat#417]
Hello there!

Thank you for all your work on ddraw. It has allowed me to keep playing some of my old Win95 games!

Following a recent upgrade of Windows 11 Home to version Version 10.0.26100 Build 26100, a legacy game that I used to play without issues constantly hangs to the point where I need to sign out or kill the process.... it doesn't crash but just hangs.

I am running v0.5.4

I saw the Oct 6th updates to v0.5.3. Unsure if this affects me or not. Based on documentation it shouldn't

I am attaching relevant logs during the hang event

[DDrawCompat-manager.log](https://github.com/user-attachments/files/18241453/DDrawCompat-manager.log)

**Comment by narzoul** [comment]
I assume this is the same as https://github.com/narzoul/DDrawCompat/issues/387, please try the solutions posted there.

**Comment by ejahnke** [comment]
The resolution for issue #387 seems to have worked for me as well!
