### ISSUE TITLE
Siege of Avalon: Seems bitmap DC is "upside-down" in experimental

### ISSUE THREAD

**Issue by SteveNew** [narzoul/DDrawCompat#42]
I did find a glitch that seemed to have slipped in recently - in Siege of Avalon - the screenshot done with the save game is upside-down and when shooting arrows - these are mirror horizontal - it seems in both case to be something with blt on the raw bitmap DC - so I have currently "fixed" it in my [fork of Siege of Avalon](https://github.com/SteveNew/Siege-of-Avalon-Open-Source) code - to use negative height on the screenshot and subtract Y-value from the height of the arrow bmp. But I would be happy if you had any chance to solve the issue in your ddraw.dll - because there might be other issues - that that I haven't circumvented yet :) Thanks for doing the great job.

**Comment by narzoul** [comment]
The upside-down save game screenshots should be fixed now. I don't have a save game where I can shoot arrows yet. Could you please check if that is also fixed?

**Comment by SteveNew** [comment]
All seems good and fine - thanks - considered fixed :)
