### ISSUE TITLE
Arcanum: OSaMO - DDrawCompat can't find display mode in full screen

### ISSUE THREAD

**Issue by mkasst** [narzoul/DDrawCompat#43]
Initially installed the Arcanum patches in Windows 10 1807 - as of the 1903 update a few days ago, my configuration no longer worked, and Arcanum would barely blink on screen before crashing. The logs from ddraw indicate that there's an issue finding the "display mode:"

`7516 21:24:29.246 Process path: D:\Games\GOG\Arcanum\Arcanum.exe`
`7516 21:24:29.247 Environment variable __COMPAT_LAYER = "HighDpiAware"`
`7516 21:24:29.247 Loading DDrawCompat from D:\Games\GOG\Arcanum\DDRAW.dll`
`7516 21:24:29.248 DDrawCompat loaded successfully`
`7516 21:24:29.270 Installing registry hooks`
`7516 21:24:29.271 Installing Direct3D driver hooks`
`7516 21:24:29.271 Installing DirectDraw hooks`
`7516 21:24:29.401 Installing Direct3D hooks`
`7516 21:24:29.404 Installing GDI hooks`
`7516 21:24:29.411 Finished installing hooks`
`7516 21:24:29.421 Failed to find the requested display mode: 1920x1080x16`
`7516 21:24:29.429 Detaching DDrawCompat`
`7516 21:24:29.524 DDrawCompat detached successfully`

After reconfiguring the patch to run in windowed, everything seemed to work again (aside from the noted differences in functionality between windowed and full screen implementations of the wrapper.)

I think this may be related to what was occurring in issue #15 but it's a little out of my depth. Feel free to correct me and close the issue if I've mistaken this as a DDrawCompat issue when it's some other part of the mod. I will try to verify if this occurs on another machine with the same patch version but different hardware. This case occurred on a machine with an nVidia GTX670 with driver version 430.64 

And thank you for all your hard work on this!

**Comment by narzoul** [comment]
I have similar issues after upgrading to the latest Windows 10 version manually. It looks like at least "DXPrimaryEmulation -DisableMaxWindowedMode" is broken (again) - it is now uselessly slow (with or without DDrawCompat). But there are other issues as well. I imagine this mess will take a while to fix, but I'll try to work on it with top priority...

**Comment by mkasst** [comment]
I did notice some additional performance slowdown in game when I was playing in windowed, but I chalked that up to the differences between windowed and fullscreen. Happy to do some testing if there's any useful data I can collect for you.

**Comment by narzoul** [comment]
It looks like the issue wasn't nearly as bad as I expected. Some functions were moved out to separate libraries by the Windows update and they left behind forwarding references in the export table that were not hooked properly. I put a workaround in place that should hold out at least until the next major Windows update. :)

I also can't reproduce the slowdown with "DXPrimaryEmulation -DisableMaxWindowedMode" anymore, either natively or with DDrawCompat. Maybe I just needed a system reboot for that.

Although I never encountered the error log you posted about the display mode previously, I'm still hopeful this fix will work for you too. Please check the latest experimental release and let me know if it resolved the issue.

**Comment by mkasst** [comment]
I can confirm the fix seems to be working extremely well - quite possibly better than the version I was running before. I'll close the issue, and if I find any new issues I'll let you know. Thank you again for your work - it's an absolute godsend to keep these old games running.
