### ISSUE TITLE
[Divine Divinity] issue with experimental build 11.08.2019

### ISSUE THREAD

**Issue by YoungLolita** [narzoul/DDrawCompat#52]
Hi narzoul,

first of all thank you for your great working ddraw wrapper that improves the performance of this game so much!!! It seems like your experimental build still improves the performance in comparison to the stable v0.2.1 release. But it also has a bug. When you open the config tool of the game to set the resolution, the window of the config tool becomes bugged after some time. I'm playing the retail version 1.0034A, because the digital distributed version 1.0062A is less polished. I have to say your ddraw wrapper is the only working one available for this game!

I would like when you would make a new stable release.

Thank you again and best regards!

**Comment by narzoul** [comment]
This should already be fixed in latest experimental release.
