### ISSUE TITLE
Performance Issue on Windows 10

### ISSUE THREAD

**Issue by die4teoffenbarung** [narzoul/DDrawCompat#56]
Hi,
so a few players [www.d4o.info] got FPS/Performance issues on Windows 10 after patching the last  problems with second screen and the Windows 7 runtime issue. Possible you have an idea whats causing this, before was all good for them and they had no perofrmance issue at all.
Anyway I'm still waiting for a Log-File, do you need any additional stuff beside the Log?

Thanks and best regards!

**Comment by die4teoffenbarung** [comment]
I'm still waiting for a response, so... can't be that problematic at all, i'll just get back to you if i got new informations. ^^

**Comment by narzoul** [comment]
Any update on this? Are there still performance issues with the latest release?
