### ISSUE TITLE
Can't compile. d3dumddi.h missing in latest versions of Windows SDK

### ISSUE THREAD

**Issue by Rule110** [narzoul/DDrawCompat#57]
Hi narzoul,

I can't compile your source code because the d3dumddi.h header file is missing from the latest versions of the Windows 10 SDK.

I think it was removed back in v10.0.14393. The latest versions of the SDK in Visual Studio 2019 don't seem to have this header file. v10.0.17763 is missing it.

How can one go about compiling your source now? Should I switch back to an older Visual Studio, or is there a quick fix I'm missing?

Regards,
Rory

**Comment by narzoul** [comment]
It might be part of the WDK, not  the SDK. Try installing the corresponding Windows Driver Kit also.
https://docs.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads
I think you need "WDK for Windows 10, version 1809" from this page.

**Comment by Rule110** [comment]
Hi narzoul,

Thanks for the help. It compiles now. For anyone else wondering I downloaded the latest WDK (version 1903) from here:
https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

The problem now is that my dll when compiled is 10 times the size of your dll (the one that comes with Tiberian Sun). The game also is laggy and slow when I use my compiled version.

Do you know what could be causing my compile size to be so large and for the game to run so slow with it?

Regards,
Rory

**Comment by narzoul** [comment]
Sounds like you're compiling the debug build. Is your ddraw.log file also larger than 1-2 kbytes? If yes, then definitely that is the problem.
You can change the build type from the drop-down menu at the top of the Visual Studio window (that should have "Debug" selected now).

Note that each build type's dll goes into a separate directory, which is named the same way as the build type.

**Comment by narzoul** [comment]
By the way, the latest commit is usually already built and released under the Code/Releases page here on GitHub (it's the "experimental" version), so you don't need to build it yourself unless you also want to modify the code or build from an older commit.

**Comment by noabody** [comment]
I was curious to build this project and with the many changes MS keeps making I actually found it easier to use the Microsoft [EWDK](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) which can be natively mounted in Windows 10.
Navigate to that location and double-click LaunchBuildEnv.cmd

The WindowsTargetPlatformVersion is the numbered folder located at 
 - [isomount]:\Program Files\Windows Kits\10\Include\\[numbered folder]

Just substitute that number into the build command:

```
msbuild /p:PlatformToolset=v142;WindowsTargetPlatformVersion=10.0.19041.0;Platform=win32;Configuration=Release /t:Clean,Build dxwrapper.sln
```

**Comment by AliaskaRuS** [comment]
[d3dumddi.zip](https://github.com/narzoul/DDrawCompat/files/10371390/d3dumddi.zip)
