### ISSUE TITLE
Game Laghaim Freze after 1-5 min

### ISSUE THREAD

**Issue by Jailobeam** [narzoul/DDrawCompat#58]
Hey you are doing a great job

The Game (Laghaim) run very fine with the latest experimental release
but its Freeze after 1-5 min log says
0:05:48.804 ERROR: Resource::copySubResource failed: 0x887a0005

do you have an idea how to solve it?

[ddraw.log](https://github.com/narzoul/DDrawCompat/files/3776574/ddraw.log)

**Comment by narzoul** [comment]
Sounds like a driver crash or similar. I'll try to reproduce it later but it's probably related to NVIDIA drivers, which I can't check at the moment... Have you updated your drivers recently?

Are you on Windows 7 or 10? Is the game windowed or full screen? Are you sure the same issue doesn't happen without DDrawCompat?

If you could reproduce the issue and upload the logs produced by the ReleaseWithDebugLogs build, that could be helpful. In this case, please make sure you don't type in your password and don't enable "show password" or similar, as those might be visible in the log. Use a saved password or a dummy account/password that you don't mind getting compromised.

**Comment by Jailobeam** [comment]
Hey 
Yes im on Win 10 and the Game is windowed (1024x768 )
Game FPS without DDrawCompact 15-20 FPS no Crashes
With Compact 40+ FPS Crash after 1~5 min
Driver is Up to Date Nvidia 440.97   Card is the GTX 980 M 8gb
I tried with Debug but the game have max 1-2 FPS and Dont Crash, log was over 4gb without crash :(

**Comment by narzoul** [comment]
Which client do you use? The one at laghaim.online does not freeze for me.
Also, how do you display the fps?

**Comment by Jailobeam** [comment]
https://lholdschool.de/
FPS with Nvidia or Fraps

**Comment by narzoul** [comment]
Same with that client. No freezes.

However, using Fraps definitely causes the display to freeze, all the time from starting the game (but not with the error log you have). It updates only a single frame when deactivating/reactivating the window. But this is a long standing known incompatibility with overlay tools like this (see e.g. issue #13).

I hope you're not running Fraps or similar tools all the time. If you do, please try running the game with those closed.

Does only the screen freeze, but the game and sounds continue working? Or does the client crash and close completely?

**Comment by Jailobeam** [comment]
Now for Test
Nvidia Overlay OFF
Fraps OFF 
I report how it works

**Comment by Jailobeam** [comment]
No same Problem
Game Freez but dont close


 
[ddraw.log](https://github.com/narzoul/DDrawCompat/files/3780932/ddraw.log)

**Comment by Shiyoda** [comment]
Hi,

this is my log, with the exact same problem. Especially when you press ALT or ALT + F in Game and hover over the items which dropped. It will instantly close the client.

[ddraw.log](https://github.com/narzoul/DDrawCompat/files/3780946/ddraw.log)

**Comment by Shiyoda** [comment]
I tried it again. This time without pressing ALT or ALT + F(ALT + Shift) for a while. I only got some stuttering while playing. It began instantly after connecting to the server. The lag spikes were there for 1-2 seconds in an interval of maybe 20 seconds.

After i pressed ALT + Shift to show the items which dropped. Then i had around 5minutes zu play and the game freezed and after a while my computer does the same.

[ddraw.log](https://github.com/narzoul/DDrawCompat/files/3780973/ddraw.log)

**Comment by Jailobeam** [comment]
Yes narzoul you are right on intel works with some display bugs but no freezes

do you think it is possible fix it for Nvidia ?

**Comment by narzoul** [comment]
I have an older Nvidia card lying around somewhere (GTX 760), I might swap it in over the weekend or so and see if I can reproduce the issue that way. Hopefully it's fixable.

**Comment by Shiyoda** [comment]
@narzoul 

Think this is the latest of the old drivers for GTX 760 which was released in 2014: https://www.geforce.com/drivers/results/77224

Maybe try that out if you switching the cards.

**Comment by narzoul** [comment]
I think I managed to fix it... please test the latest experimental release and let me know how it goes.

**Comment by Jailobeam** [comment]
incredible
It's going very well for 1.5 hours

will test it further

Thank you so much
