### ISSUE TITLE
The latest dev build works perfectly with DevHunter (the Easter Egg in Excel 2000)

### ISSUE THREAD

**Issue by jeffli678** [narzoul/DDrawCompat#59]
Thanks for your efforts of creating DDrawCompat! I have recently extracted the DevHunter game from Excel 2000 and sought to make it run on Windows 10. I tried several compatibility layers and only this one works! I will soon create a repo to share what I have done. 

P.S.: The last stable build also works, but produces amusing graphics rather than the correct ones.

**Comment by TAbdiukov** [comment]
i believe we a may need a wiki for working/non working games for this matter. Otherwisde, I usually post to PCGamingwiki

**Comment by narzoul** [comment]
Thanks for the feedback! Since this isn't really an issue, I'll close it now. I'll think about adding a wiki, though I haven't really got time to maintain one, and I'm not sure there are enough interested people who would want to do it or even use it, either.
