### ISSUE TITLE
Blade Master

### ISSUE THREAD

**Issue by MarkSpizu** [narzoul/DDrawCompat#60]
Hi. Can you try this game? I don't know why it doesn't work. Thanks!

https://archive.org/details/swizzle_demu_Bm10

**Comment by narzoul** [comment]
This is a Direct3D 8 game, so it's not supported by DDrawCompat.

**Comment by MarkSpizu** [comment]
How can I get in touch with you in private?

**Comment by narzoul** [comment]
I generally don't provide support in private. If it's related to DDrawCompat, then please open an issue here on GitHub.

**Comment by MarkSpizu** [comment]
I wanted in private to send you a game. Then see if you can find a download for this game: Pickman Saves The Kingdom
