### ISSUE TITLE
Hi again related to my game called O2JAM

### ISSUE THREAD

**Issue by jcgo16** [narzoul/DDrawCompat#69]
`1e58 11:44:00.764 Process path: G:\Games\O2Jam\O2Jam Interval\OTwo.exe
1e58 11:44:00.765 Environment variable __COMPAT_LAYER = "Disable8And16BitModes 256Color"
1e58 11:44:00.765 Loading DDrawCompat statically from G:\Games\O2Jam\O2Jam Interval\DDRAW.dll
1e58 11:44:00.766 DDrawCompat loaded successfully
1e58 11:44:01.096 Installing registry hooks
1e58 11:44:01.096 Installing Direct3D driver hooks
1e58 11:44:01.096 Installing display mode hooks
1e58 11:44:01.108 Hooking user mode display driver: C:\WINDOWS\System32\DriverStore\FileRepository\u0354308.inf_amd64_48534036afa0f0d8\B354265\aticfx32.dll
1e58 11:44:01.151 Installing DirectDraw hooks
1e58 11:44:01.154 Installing Direct3D hooks
1e58 11:44:01.157 Installing GDI hooks
1e58 11:44:01.236 Finished installing hooks
1e58 11:44:02.125 Incorrect z-buffer bit depth capabilities detected for "AMD Radeon RX 5600 XT" / Direct3D HAL; changed from "16, 32" to "16, 24"
1e58 11:44:35.752 Detaching DDrawCompat due to process termination
1e58 11:44:35.752 DDrawCompat detached successfully
`

Players reported to me that the game is not compatible with new RDNA from AMD
on rx 580, 690 works ok and no need for any fixes

http://o2jam.com.ph

**Comment by narzoul** [comment]
What does "not compatible" mean exactly? There is nothing out of the ordinary in those logs.

**Comment by jcgo16** [comment]
its showing this pink artifacts on windows 10, with rx 5700

https://imgur.com/a/BuYX2k9

on rx 580 it is not present

**Comment by narzoul** [comment]
Well, this is a mess... I can't get the game to use DDrawCompat actually. Whenever I launch it throw the patcher it actually deletes ddraw.dll. In the "Game Render Option" settings, there is a "DDrawCompat Dev Release 2019", but selecting it and pressing Save Settings seems to have no effect either. If I close the settings window and open it again, it resets the "Current Render Setting" to empty.

Also, based on the log you posted above, the game is set to run in 256 color mode. Why is that? I don't think it's supposed to run in 256 colors at all. It might well be responsible for the pink artifacts.

**Comment by jcgo16** [comment]
Ahmm my bad, just check the Linux Compatibility so it wont override the DLL and exe settings

Sorry about that, don't worry about the Game Render Option *not completed yet*
https://imgur.com/a/yMKXEDD

**Comment by narzoul** [comment]
As far as I can tell, some other wrapper is also present in the game installation by default, which is used to set the windowed mode I guess. Are there pink artifacts when only DDrawCompat is used? Please rename dinput.dll to something else and test that too.

Also, which version of DDrawCompat was used? Is it the latest experimental release or an older experimental one?

**Comment by jcgo16** [comment]
i used experimental and the game suddenly close, btw no any dll files and no registry edit stuff, just plain

[DDrawCompat-OTwo.log](https://github.com/narzoul/DDrawCompat/files/4674620/DDrawCompat-OTwo.log)

**Comment by narzoul** [comment]
I still don't see any graphics related errors in your log. I'm trying to compare it to mine, but the surface creation order seems to be different, probably because I'm using a different client version now. Can you please upload a new log with the latest game client and latest experimental release (ReleaseWithDebugLogs version)?

**Comment by narzoul** [comment]
This is already fixed according to #79.
