### ISSUE TITLE
d8bf209d7ab402ed4d776274c0b2d67fe2f1ed37 Missing files in commit

### ISSUE THREAD

**Issue by die4teoffenbarung** [narzoul/DDrawCompat#70]
Latest commit has some missing files, I think.

```
Cannot open source file: 'D3dDdi\Log\CommonLog.cpp' & 'D3dDdi\Log\CommonLog.h'
```

**Comment by narzoul** [comment]
Yes, I noticed this as well. I added the missing files now.

I wish I knew how it happened though. The files were shown as "ignored" in Visual Studio and "git status" didn't list them either, even though they weren't in the .gitignore file. I just unignored them via Visual Studio.
