### ISSUE TITLE
Laghaim UI error

### ISSUE THREAD

**Issue by Darlan93** [narzoul/DDrawCompat#71]
Hi, I'm having some issues with this version of **Laghaim**, the game works without the dll, but with 10 to 15 fps at most, it's much smoother with the dll on the folder but then I get this:
![Game-2020-06-19-09-10-06-271](https://user-images.githubusercontent.com/67152835/85133642-737d4880-b211-11ea-98e8-d6c7846f5068.gif)
The UI is mostly missing and you can see the icons are just going crazy.
The game also runs fine when I toggle the UI off, without the dll. So I wonder if that's a bug that they need to fix or if you can fix it...

This is the game's website:
laghaimrevolution2.com

**Comment by Darlan93** [comment]
If it helps here's the log.

1c30 09:12:08.558 Process path: C:\Users\PC\Desktop\Laghaim Revolution 2\Game.exe
1c30 09:12:08.558 Environment variable __COMPAT_LAYER = "RunAsAdmin Win7RTM Installer"
1c30 09:12:08.558 Loading DDrawCompat statically from C:\Users\PC\Desktop\Laghaim Revolution 2\DDRAW.dll
1c30 09:12:08.560 Disabling external hook to DirectDrawCreateEx in apphelp.dll
1c30 09:12:08.560 DDrawCompat loaded successfully
1c30 09:12:08.638 Installing registry hooks
1c30 09:12:08.638 Installing Direct3D driver hooks
1c30 09:12:08.638 Installing display mode hooks
1c30 09:12:08.652 Hooking user mode display driver: C:\Windows\System32\DriverStore\FileRepository\u0346453.inf_amd64_bc963e4e92e4ff40\B346420\aticfx32.dll
1c30 09:12:08.662 Installing DirectDraw hooks
1c30 09:12:08.663 Installing Direct3D hooks
1c30 09:12:08.665 Installing GDI hooks
1c30 09:12:08.707 Finished installing hooks
1c30 09:12:08.733 Incorrect z-buffer bit depth capabilities detected for "AMD Radeon(TM) RX Vega 11 Graphics" / Direct3D HAL; changed from "16, 32" to "16, 24"
1c30 09:12:08.733 Incorrect z-buffer bit depth capabilities detected for "AMD Radeon(TM) RX Vega 11 Graphics" / Direct3D T&L HAL; changed from "16, 32" to "16, 24"
1c30 09:14:26.673 Detaching DDrawCompat due to process termination
1c30 09:14:26.673 DDrawCompat detached successfully

**Comment by narzoul** [comment]
I'm not sure I understand you correctly. Does it have the same issue with the icons when not using DDrawCompat?

Strange. I can't reproduce it with the latest experimental release, on AMD Radeon RX 480, Windows 10 v2004. What are your system specs and game settings? Full screen or windowed, 16/32 bit, etc.

Also try running it without any compatibility settings on Game.exe (works fine for me with neither Win 7 compatibility nor "run as admin", but you seem to have both set) and without any overlays/recorders like Bandicam running, as those are known to interfere with DDrawCompat.

**Comment by narzoul** [comment]
Their latest FB post, 14 hours ago, says "Corrected the problem with the interface in windows 10", maybe it's referring to this? Have you patched your game to the latest version already?

**Comment by Darlan93** [comment]
>Does it have the same issue with the icons when not using DDrawCompat?

No.

>What are your system specs and game settings?

Windows 10, 16gb ram, Ryzen 5 2400g with integrated AMD Radeon(TM) RX Vega 11. Windowed, 32bit.

>Also try running it without any compatibility settings on Game.exe

Took it out, same problem.

>Their latest FB post, 14 hours ago, says "Corrected the problem with the interface in windows 10"

It's looking more and more like it's just a 'me' problem after all...

**Comment by narzoul** [comment]
If the issue doesn't happen without DDrawCompat, then most likely it is a problem with DDrawCompat. I guess the driver for integrated AMD GPUs works a bit differently. Unfortunately I don't have such a setup available for testing now so it's impossible for me to find the problem alone.

Is your GPU driver up to date?

If you can help me narrow down the issue to the exact git commit that first introduced it, that would be most helpful as a starting point. If you can't build DDrawCompat yourself, I can provide the test builds here.

If you're willing to do more testing, please start with these 3 versions that should already be available to you:
1. v0.2.1: https://github.com/narzoul/DDrawCompat/releases/tag/v0.2.1
2. Latest experimental release: https://github.com/narzoul/DDrawCompat/releases/tag/experimental
3. Older experimental release available in the game's install directory in the "Windows10 unpack this.rar" file

Please report back which ones have the issue and which ones don't.

**Comment by Darlan93** [comment]
Yes I updated my GPU driver while trying to solve the issue.

The only ones that do anything to the game are the experimental releases, having v0.2.1 (or older) on the folder is the same as playing the game without it.

Both experimental releases display the same issue.

**Comment by narzoul** [comment]
I was finally able to do some testing on a laptop with Vega 8 and had some issues there also, though it's different from yours. I couldn't get past the character selection screen because the UI was missing there.

I fixed that in the latest experimental release, please check if it fixes your issue also.

**Comment by Darlan93** [comment]
You did it! I was also having the same issue with the character selection screen, forgot about that cause I knew where I had to click and already had a character. Thank you!
