### ISSUE TITLE
No issue here, THIS WORKS GREAT!!!! (Update: I have an issue)

### ISSUE THREAD

**Issue by RichNagel** [narzoul/DDrawCompat#83]
I signed up with GitHub just to post this message. I don't have any issues. I've been trying to get Papyrus' NASCAR Racing 3 and NASCAR Legends to work with Windows 10 for FIVE DAYS now. After discovering and trying out DDrawCompat, the games WORK PERFECTLY!!!! WOOHOO!!!! THANK YOU SO MUCH for this excellent program :)

**Comment by RichNagel** [comment]
(UPDATE) Unfortunately I found an issue. Note that I'm using the experimental version, as the release version caused strange problems with the mouse cursor in the games when moving the cursor over the various menu options. In the release version there were also long pauses when going from one game screen to another. This is why I was using the experimental version.

Anyhow, the problem that I'm seeing is that the gauges in the car cockpit have no needles. Everything else seems to work fine, just no needles for the gauges.

I don't know if this helps, but here are the contents of the "DDrawCompat-NASCAR Racing 3.log" file:

2290 15:09:53.353 Process path: C:\Games\RACING\NASCAR3\NASCAR Racing 3.exe
2290 15:09:53.353 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation"
2290 15:09:53.353 Loading DDrawCompat dynamically from C:\Games\RACING\NASCAR3\DDRAW.dll
2290 15:09:53.360 DDrawCompat loaded successfully
2290 15:09:53.361 Installing display mode hooks
2290 15:09:53.361 Installing registry hooks
2290 15:09:53.361 Installing Direct3D driver hooks
2290 15:09:53.363 Installing Win32 hooks
2290 15:09:53.403 Hooking user mode display driver: C:\WINDOWS\System32\DriverStore\FileRepository\u0359160.inf_amd64_2abe2598d9a3141f\B358802\aticfx32.dll
2290 15:09:53.418 Dynamic vertex buffers are available
2290 15:09:53.418 Dynamic index buffers are available
2290 15:09:53.420 Checking source color key support: passed
2290 15:09:53.427 Installing DirectDraw hooks
2290 15:09:53.430 Installing Direct3D hooks
2290 15:09:53.436 Installing GDI hooks
2290 15:09:53.492 Finished installing hooks
2290 15:09:53.539 Incorrect z-buffer bit depth capabilities detected for "AMD Radeon (TM) R9 360" / Direct3D HAL; changed from "16, 32" to "16, 24"
2290 15:10:45.050 Detaching DDrawCompat due to process termination
2290 15:10:45.051 DDrawCompat detached successfully

Attached is a screenshot showing the problem.

![n3ss04](https://user-images.githubusercontent.com/3600484/103379681-773d3200-4ab4-11eb-9552-005ff8c43616.jpg)

**Comment by narzoul** [comment]
Looks like this is an old issue with the hardware D3D renderer in this game, there are mentions of it on other forums too, e.g:
https://www.neoseeker.com/forums/262/t1591744-no-needles-on-instruments/
https://www.zeus-software.com/forum/viewtopic.php?t=648

I'll check it later, maybe it can be worked around somehow.
It works with the renderer set to "None" in the graphics options though.

**Comment by narzoul** [comment]
Fixed in the latest experimental release.
