### ISSUE TITLE
Text missing

### ISSUE THREAD

**Issue by ViperPGA2000** [narzoul/DDrawCompat#84]
This fixes previous Win 10 graphic issues with PGA 2000, thanks! The only issue now is the text becomes invisible in the menus as shown below. The white square should have text options but they are invisible.

https://i.postimg.cc/5NJHhBBQ/pga.jpg

**Comment by narzoul** [comment]
Thanks, I'll look into it. In the meantime, you can probably run this game without DDrawCompat, as natively it seems to have the same graphic issues as Star Wars Rebellion mentioned in issue #22. In particular, see these two comments: https://github.com/narzoul/DDrawCompat/issues/22#issuecomment-609489578 and https://github.com/narzoul/DDrawCompat/issues/22#issuecomment-616197074.

**Comment by ViperPGA2000** [comment]
@narzoul, you are awesome! I did the DXWrap.dll hex edit and from a quick test everything appears to be working perfectly.
Thanks, very greatly appreciated! The work you are doing is just fantastic!

**Comment by narzoul** [comment]
Fixed in the latest experimental release.
