### ISSUE TITLE
Strange Window Borders

### ISSUE THREAD

**Issue by alekasm** [narzoul/DDrawCompat#86]
Hi again, I posted this previously but decided to post it again. For some reason in SimCopter the window borders have strange colors and border styles. Sometimes the colors change:

![image](https://user-images.githubusercontent.com/45739284/105539690-14aa1100-5cc3-11eb-9464-1b4718bac7c7.png)
![error](https://user-images.githubusercontent.com/45739284/105539695-170c6b00-5cc3-11eb-938a-c7bbf39014d7.png)

Not a huge issue because ddrawcompat fixes a bunch of other issues, so once again thank you for working on this over the years.

**Comment by narzoul** [comment]
Fixed in the latest experimental release. Also fixed an issue where the main window didn't update properly after closing a file dialog.
