### ISSUE TITLE
Help me~

### ISSUE THREAD

**Issue by snowy5719** [narzoul/DDrawCompat#87]
![image](https://user-images.githubusercontent.com/7158875/107134011-963fa700-6931-11eb-9ad1-4984620724b9.png)
I am trying to use DDrawCompat for our game.
Why does this happen?
We are using a 256 color palette.
Can I get some help?

**Comment by narzoul** [comment]
Please send a link to the game so I can reproduce and debug the issue properly. I can't just magically guess what's wrong by looking at a picture.
Does it display correctly without DDrawCompat? Is this on Windows 10?

**Comment by snowy5719** [comment]
i greatly appreciate your kind words.
but i've already solved the problem.
thanks, nazzoul.

**Comment by poikilos** [comment]
> i greatly appreciate your kind words.
> but i've already solved the problem.
> thanks, nazzoul.

If you answer his original questions and post your solution, that will help others.
