### ISSUE TITLE
Low FPS on a DX7 game

### ISSUE THREAD

**Issue by Trollgobler** [narzoul/DDrawCompat#89]
The latest experimental release is the only one that runs the game, but in an extremely low framerate. The game isnt very well known, but it's a classic in my country. I am attaching the log in the hopes that it might give you some insight.
[DDrawCompat-B2000.log](https://github.com/narzoul/DDrawCompat/files/6216571/DDrawCompat-B2000.log)

**Comment by narzoul** [comment]
Thanks. I can reproduce the issue with other palettized games on Intel HD actually. I'll try to fix it for the next release.

**Comment by Trollgobler** [comment]
Great! Might I ask when's the next release coming? 😁

**Comment by narzoul** [comment]
If I find the issue quickly enough, then maybe tonight, otherwise probably sometime next week.

**Comment by Trollgobler** [comment]
That's great! Thank you so much :)

**Comment by narzoul** [comment]
I've updated the experimental release, that should fix the issue now. Feel free to reopen if it doesn't.

**Comment by Trollgobler** [comment]
It works! Thank you very much! I actually tried a LOT of ddraw
implementations and this is the only one that has worked. I hope you have a
great upcoming week!
