### ISSUE TITLE
Latest release game won't launch

### ISSUE THREAD

**Issue by WrathX** [narzoul/DDrawCompat#90]
Hello. I've been trying out all your experimental releases for a long time with the game Project Visitor and with each release the game ran better and better. For some reason with this latest release 0.3.0 the game suddenly doesn't launch at all now. Not sure what changed. Still have copies of the older versions to run the game.

**Comment by narzoul** [comment]
Try renaming/removing the dbghelp.dll file in the executable's directory. Windows should have a newer version of the file preinstalled anyway, and this old version seems to cause problems for the new dbgeng.dll dependency of DDrawCompat. (Although this dependency was already introduced with the previous experimental release on March 28, maybe you didn't test that one?)

**Comment by WrathX** [comment]
That was exactly the issue thank you! You are correct about not testing the March 28th one. after posting yesterday I had realized that I had missed trying that one. Thanks again!
