### ISSUE TITLE
Thank you so much for new version :)

### ISSUE THREAD

**Issue by BK-2-0-1** [narzoul/DDrawCompat#91]
Just tested it now in very old game (the nations/alien nations) and it works like a charm. 

Thank you so much. Best wishes⭐

**Comment by BK-2-0-1** [comment]
Btw - recording did not work before (in OBS), but now everything absolutely fine (just a very little issues with cursor, but it's not a problem really).

So once again thank you, it really helps a lot and gives you the opportunity to play cool old games ( ͡° ͜ʖ ͡°)

**Comment by narzoul** [comment]
Thanks for the feedback!

What do you mean by cursor issues? I don't seem to have any in either game.

**Comment by BK-2-0-1** [comment]
It's like cursor disappear for a millisecond, as i said its not problem at all. in original version of game it looks like the box around cursor and when you move it - cursor creates copy of itself, and it's very hard to play like this (obviously).

i can show you a gif, for a clearer understanding:
![666](https://user-images.githubusercontent.com/68499416/115125345-310ece80-9fd0-11eb-9fb4-274446abd3e4.gif)

**Comment by narzoul** [comment]
Ok, I saw it a few times now for a few seconds, but only rarely, and so far only when OBS was running/capturing in the background. Does it happen when OBS is not running?

By the way, I only managed to capture a black screen + audio with Game Capture (Capture any fullscreen application). How did you set it up to capture video correctly?

**Comment by BK-2-0-1** [comment]
Yeah, OBS change nothing, just capture as it is.

game capture also does not work for me. and i dont know how to launch game in windows. so... I just record fullscreen ¯\_( ͡° ͜ʖ ͡°)_/¯

**Comment by narzoul** [comment]
I think I didn't get as much flickering because my desktop refresh rate was set to 144 Hz. After setting it to 60 Hz, I'm getting constant flickering also. I added some fix related to this in v0.3.1. It isn't perfect, but it should significantly reduce the flickering. Please test it and let me know how it goes!

**Comment by BK-2-0-1** [comment]
Okay, i will :)

**Comment by BK-2-0-1** [comment]
Checked it out. Everything works perfectly. No cursor lags anymore, game can still be recorded without any troubles. Thank you so much for it :)

**Comment by narzoul** [comment]
Thanks for the feedback!
