### ISSUE TITLE
Defect report

### ISSUE THREAD

**Issue by nyankop** [narzoul/DDrawCompat#93]
After deactivating the game window in version 0.3.0, reactivating it freezes the screen.
Also, after a while, you will not be able to enter text in the in-game chat.
I'm glad this version is very comfortable, but I can't play it due to these issues.

**Comment by narzoul** [comment]
Ok, but which game is it?

**Comment by nyankop** [comment]
Sorry I forgot the name of the game, it's an online game called TalesWeaver.
I'm playing an emulation server with a past version, not the latest one.

**Comment by narzoul** [comment]
I could only check out the official Japanese client, but it doesn't seem to support DirectDraw anymore, it runs on Direct3D 9 only. As far as I can see it doesn't support alt-tabbing either though. Does it work for you without DDrawCompat? Has it worked correctly with a previous version of DDrawCompat?

**Comment by nyankop** [comment]
The version I'm playing is about 13 years old. At that time, I believe it used DirectRaw and Direct3D.
Alt+Tab did not work in fullscreen mode, but it does work in windowed mode.
I think the only site where you can play the version from that time is in China now.
http://www.mhtw.org/
The site is here.
DDrawCompat has used some of the past versions, but has not seen any improvement.

Please note that some of the text is not correct due to the use of translation sites.

**Comment by narzoul** [comment]
That site doesn't have a TalesWeaver client, only 2 other games. I don't think the Chinese server for this game exists anymore.

**Comment by nyankop** [comment]
It's an emulator-server, so it's definitely this site.
http://www.mhtw.org/html/notice/download.html
This is the 2.31GB client on this page.
The name of the game is slightly different, but this is Tales Weaver.
I'm currently playing this.

**Comment by narzoul** [comment]
Ok, so after downloading and extracting the client, how do you actually start the game?

**Comment by narzoul** [comment]
I fiddled around with it for a while in a VM, but it looks like the only way to start it is via the MHWT(...).exe file, which Microsoft Defender flags as a PUA and refuses to run, and I'm not inclined to overrule it. It's suspicious according to many other scanners too:
https://www.virustotal.com/gui/file/fac811dfb8555c282f2418bc1763c95a772659c6010d121ef98d6ba02494f7d7/detection

Sorry, but I won't take the risk. I cannot support this game.
