### ISSUE TITLE
Splash screen issue with Star Trek Armada 1

### ISSUE THREAD

**Issue by elishacloud** [narzoul/DDrawCompat#94]
Thank you for the latest release!  It fixes a lot of issues.  However, it seems to cause one minor issue with Star Trek Armada 1.  The splash screen is messed up.  See screenshots below.

Running DDrawCompat v0.3.0:

![Armada-splash-bad](https://user-images.githubusercontent.com/25625456/115810923-a5b48500-a3a3-11eb-9df0-bbbcb68bc355.png)

How it is supposed to look:

![Armada-splash-good](https://user-images.githubusercontent.com/25625456/115810944-af3ded00-a3a3-11eb-9d6f-25868174c6ba.png)

**Comment by narzoul** [comment]
Fixed in v0.3.1.
