### ISSUE TITLE
Buttons disappear in Gangsters Organized Crime

### ISSUE THREAD

**Issue by elishacloud** [narzoul/DDrawCompat#95]
Great work on all the fixes for Gangsters Organized Crime.  This updated v0.3.0 definitely works better than any other wrapper for this game.  However, there is still one issue left.

If you start the game and immediately enter the Options menu then all the default selected buttons are invisible.  However, once you click a different button then the these buttons become visible again.  See GIF below:

![Gangsters Organized Crime](https://user-images.githubusercontent.com/25625456/115812635-8834ea80-a3a6-11eb-8615-96d9beb3292b.gif)

**Comment by narzoul** [comment]
Fixed in v0.3.1.
