### ISSUE TITLE
thanks for 0.31

### ISSUE THREAD

**Issue by midtown96** [narzoul/DDrawCompat#99]
Thanks!
The new fix works fine for mm1 but in mm2 I still cant see the introvideo.
Is it any problems with introvideos?
Sorry for I forgot to tell you that with introvideos when I told you about the problem with mm1.

**Comment by elishacloud** [comment]
It is probably because of missing or unregistered codex.  Try the steps here:  https://www.vogons.org/viewtopic.php?p=922530#p922530

**Comment by narzoul** [comment]
Apart from the possible codec issue, there is a bug in DDrawCompat too. It doesn't hook delay-loaded functions correctly if they haven't been loaded (called) before hooking. It was broken when I replaced Detours.

I'm not planning another release for a while now, but here's a quick fix you can test in the meantime: [ddraw.zip](https://github.com/narzoul/DDrawCompat/files/6497228/ddraw.zip) (diff compared to v0.3.1: [diff.txt](https://github.com/narzoul/DDrawCompat/files/6497229/diff.txt))

**Comment by midtown96** [comment]
Thank you very much!
That quick fix works perfect for both mm1 and mm2.
And the introvideo works fine.

**Comment by narzoul** [comment]
The fix has been added to v0.4.0 now.
